using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace xPort5.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.Article.
    /// Date Created:   2020-03-02 02:12:08
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class Article
    {
        private Guid key = Guid.Empty;
        private Guid articleId = Guid.Empty;
        private string sKU = String.Empty;
        private string articleCode = String.Empty;
        private string articleName = String.Empty;
        private string articleName_Chs = String.Empty;
        private string articleName_Cht = String.Empty;
        private Guid categoryId = Guid.Empty;
        private Guid ageGradingId = Guid.Empty;
        private Guid colorId = Guid.Empty;
        private Guid originId = Guid.Empty;
        private string remarks = String.Empty;
        private string colorPattern = String.Empty;
        private string barcode = String.Empty;
        private decimal unitCost;
        private Guid currencyId = Guid.Empty;
        private int status = 0;
        private DateTime createdOn = DateTime.Parse("1900-1-1");
        private Guid createdBy = Guid.Empty;
        private DateTime modifiedOn = DateTime.Parse("1900-1-1");
        private Guid modifiedBy = Guid.Empty;
        private bool retired;
        private DateTime retiredOn = DateTime.Parse("1900-1-1");
        private Guid retiredBy = Guid.Empty;

        /// <summary>
        /// Initialize an new empty Article object.
        /// </summary>
        public Article()
        {
        }

        /// <summary>
        /// Initialize a new Article object with the given parameters.
        /// </summary>
        public Article(Guid articleId, string sKU, string articleCode, string articleName, string articleName_Chs, string articleName_Cht, Guid categoryId, Guid ageGradingId, Guid colorId, Guid originId, string remarks, string colorPattern, string barcode, decimal unitCost, Guid currencyId, int status, DateTime createdOn, Guid createdBy, DateTime modifiedOn, Guid modifiedBy, bool retired, DateTime retiredOn, Guid retiredBy)
        {
            this.articleId = articleId;
            this.sKU = sKU;
            this.articleCode = articleCode;
            this.articleName = articleName;
            this.articleName_Chs = articleName_Chs;
            this.articleName_Cht = articleName_Cht;
            this.categoryId = categoryId;
            this.ageGradingId = ageGradingId;
            this.colorId = colorId;
            this.originId = originId;
            this.remarks = remarks;
            this.colorPattern = colorPattern;
            this.barcode = barcode;
            this.unitCost = unitCost;
            this.currencyId = currencyId;
            this.status = status;
            this.createdOn = createdOn;
            this.createdBy = createdBy;
            this.modifiedOn = modifiedOn;
            this.modifiedBy = modifiedBy;
            this.retired = retired;
            this.retiredOn = retiredOn;
            this.retiredBy = retiredBy;
        }

        /// <summary>
        /// Loads a Article object from the database using the given ArticleId
        /// </summary>
        /// <param name="articleId">The primary key value</param>
        /// <returns>A Article object</returns>
        public static Article Load(Guid articleId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@ArticleId", articleId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spArticle_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    Article result = new Article();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a Article object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A Article object</returns>
        public static Article LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spArticle_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    Article result = new Article();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a collection of Article objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the Article objects in the database.</returns>
        public static ArticleCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] { };
            return LoadCollection("spArticle_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of Article objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the Article objects in the database ordered by the columns specified.</returns>
        public static ArticleCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spArticle_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of Article objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the Article objects in the database.</returns>
        public static ArticleCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spArticle_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of Article objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the Article objects in the database ordered by the columns specified.</returns>
        public static ArticleCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spArticle_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of Article objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the Article objects in the database.</returns>
        public static ArticleCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            ArticleCollection result = new ArticleCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    Article tmp = new Article();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a Article object from the database.
        /// </summary>
        /// <param name="articleId">The primary key value</param>
        public static void Delete(Guid articleId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@ArticleId", articleId) };
            SqlHelper.Default.ExecuteNonQuery("spArticle_DelRec", parameterValues);
        }


        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) articleId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) sKU = reader.GetString(1);
                if (!reader.IsDBNull(2)) articleCode = reader.GetString(2);
                if (!reader.IsDBNull(3)) articleName = reader.GetString(3);
                if (!reader.IsDBNull(4)) articleName_Chs = reader.GetString(4);
                if (!reader.IsDBNull(5)) articleName_Cht = reader.GetString(5);
                if (!reader.IsDBNull(6)) categoryId = reader.GetGuid(6);
                if (!reader.IsDBNull(7)) ageGradingId = reader.GetGuid(7);
                if (!reader.IsDBNull(8)) colorId = reader.GetGuid(8);
                if (!reader.IsDBNull(9)) originId = reader.GetGuid(9);
                if (!reader.IsDBNull(10)) remarks = reader.GetString(10);
                if (!reader.IsDBNull(11)) colorPattern = reader.GetString(11);
                if (!reader.IsDBNull(12)) barcode = reader.GetString(12);
                if (!reader.IsDBNull(13)) unitCost = reader.GetDecimal(13);
                if (!reader.IsDBNull(14)) currencyId = reader.GetGuid(14);
                if (!reader.IsDBNull(15)) status = reader.GetInt32(15);
                if (!reader.IsDBNull(16)) createdOn = reader.GetDateTime(16);
                if (!reader.IsDBNull(17)) createdBy = reader.GetGuid(17);
                if (!reader.IsDBNull(18)) modifiedOn = reader.GetDateTime(18);
                if (!reader.IsDBNull(19)) modifiedBy = reader.GetGuid(19);
                if (!reader.IsDBNull(20)) retired = reader.GetBoolean(20);
                if (!reader.IsDBNull(21)) retiredOn = reader.GetDateTime(21);
                if (!reader.IsDBNull(22)) retiredBy = reader.GetGuid(22);
            }
        }

        public void Delete()
        {
            Delete(this.ArticleId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != ArticleId)
                    this.Delete();
                Update();
            }
        }

        public Guid ArticleId
        {
            get { return articleId; }
            set { articleId = value; }
        }

        public string SKU
        {
            get { return sKU; }
            set { sKU = value; }
        }

        public string ArticleCode
        {
            get { return articleCode; }
            set { articleCode = value; }
        }

        public string ArticleName
        {
            get { return articleName; }
            set { articleName = value; }
        }

        public string ArticleName_Chs
        {
            get { return articleName_Chs; }
            set { articleName_Chs = value; }
        }

        public string ArticleName_Cht
        {
            get { return articleName_Cht; }
            set { articleName_Cht = value; }
        }

        public Guid CategoryId
        {
            get { return categoryId; }
            set { categoryId = value; }
        }

        public Guid AgeGradingId
        {
            get { return ageGradingId; }
            set { ageGradingId = value; }
        }

        public Guid ColorId
        {
            get { return colorId; }
            set { colorId = value; }
        }

        public Guid OriginId
        {
            get { return originId; }
            set { originId = value; }
        }

        public string Remarks
        {
            get { return remarks; }
            set { remarks = value; }
        }

        public string ColorPattern
        {
            get { return colorPattern; }
            set { colorPattern = value; }
        }

        public string Barcode
        {
            get { return barcode; }
            set { barcode = value; }
        }

        public decimal UnitCost
        {
            get { return unitCost; }
            set { unitCost = value; }
        }

        public Guid CurrencyId
        {
            get { return currencyId; }
            set { currencyId = value; }
        }

        public int Status
        {
            get { return status; }
            set { status = value; }
        }

        public DateTime CreatedOn
        {
            get { return createdOn; }
            set { createdOn = value; }
        }

        public Guid CreatedBy
        {
            get { return createdBy; }
            set { createdBy = value; }
        }

        public DateTime ModifiedOn
        {
            get { return modifiedOn; }
            set { modifiedOn = value; }
        }

        public Guid ModifiedBy
        {
            get { return modifiedBy; }
            set { modifiedBy = value; }
        }

        public bool Retired
        {
            get { return retired; }
            set { retired = value; }
        }

        public DateTime RetiredOn
        {
            get { return retiredOn; }
            set { retiredOn = value; }
        }

        public Guid RetiredBy
        {
            get { return retiredBy; }
            set { retiredBy = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;

            SqlHelper.Default.ExecuteNonQuery("spArticle_InsRec", "@ArticleId", out returnedValue, parameterValues);

            articleId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();

            SqlHelper.Default.ExecuteNonQuery("spArticle_UpdRec", parameterValues);
        }

        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[23];
            prams[0] = GetSqlParameter("@ArticleId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.ArticleId);
            prams[1] = GetSqlParameter("@SKU", ParameterDirection.Input, SqlDbType.VarChar, 16, this.SKU);
            prams[2] = GetSqlParameter("@ArticleCode", ParameterDirection.Input, SqlDbType.VarChar, 32, this.ArticleCode);
            prams[3] = GetSqlParameter("@ArticleName", ParameterDirection.Input, SqlDbType.NVarChar, 255, this.ArticleName);
            prams[4] = GetSqlParameter("@ArticleName_Chs", ParameterDirection.Input, SqlDbType.NVarChar, 255, this.ArticleName_Chs);
            prams[5] = GetSqlParameter("@ArticleName_Cht", ParameterDirection.Input, SqlDbType.NVarChar, 255, this.ArticleName_Cht);
            prams[6] = GetSqlParameter("@CategoryId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.CategoryId);
            prams[7] = GetSqlParameter("@AgeGradingId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.AgeGradingId);
            prams[8] = GetSqlParameter("@ColorId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.ColorId);
            prams[9] = GetSqlParameter("@OriginId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.OriginId);
            prams[10] = GetSqlParameter("@Remarks", ParameterDirection.Input, SqlDbType.NVarChar, 255, this.Remarks);
            prams[11] = GetSqlParameter("@ColorPattern", ParameterDirection.Input, SqlDbType.NVarChar, 255, this.ColorPattern);
            prams[12] = GetSqlParameter("@Barcode", ParameterDirection.Input, SqlDbType.VarChar, 16, this.Barcode);
            prams[13] = GetSqlParameter("@UnitCost", ParameterDirection.Input, SqlDbType.Decimal, 9, this.UnitCost);
            prams[14] = GetSqlParameter("@CurrencyId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.CurrencyId);
            prams[15] = GetSqlParameter("@Status", ParameterDirection.Input, SqlDbType.Int, 4, this.Status);
            prams[16] = GetSqlParameter("@CreatedOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.CreatedOn);
            prams[17] = GetSqlParameter("@CreatedBy", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.CreatedBy);
            prams[18] = GetSqlParameter("@ModifiedOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.ModifiedOn);
            prams[19] = GetSqlParameter("@ModifiedBy", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.ModifiedBy);
            prams[20] = GetSqlParameter("@Retired", ParameterDirection.Input, SqlDbType.Bit, 1, this.Retired);
            prams[21] = GetSqlParameter("@RetiredOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.RetiredOn);
            prams[22] = GetSqlParameter("@RetiredBy", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.RetiredBy);
            return prams;
        }

        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }

        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[]
            {
                GetSqlParameterWithoutDirection("@ArticleId", SqlDbType.UniqueIdentifier, 16, this.ArticleId),
                GetSqlParameterWithoutDirection("@SKU", SqlDbType.VarChar, 16, this.SKU),
                GetSqlParameterWithoutDirection("@ArticleCode", SqlDbType.VarChar, 32, this.ArticleCode),
                GetSqlParameterWithoutDirection("@ArticleName", SqlDbType.NVarChar, 255, this.ArticleName),
                GetSqlParameterWithoutDirection("@ArticleName_Chs", SqlDbType.NVarChar, 255, this.ArticleName_Chs),
                GetSqlParameterWithoutDirection("@ArticleName_Cht", SqlDbType.NVarChar, 255, this.ArticleName_Cht),
                GetSqlParameterWithoutDirection("@CategoryId", SqlDbType.UniqueIdentifier, 16, this.CategoryId),
                GetSqlParameterWithoutDirection("@AgeGradingId", SqlDbType.UniqueIdentifier, 16, this.AgeGradingId),
                GetSqlParameterWithoutDirection("@ColorId", SqlDbType.UniqueIdentifier, 16, this.ColorId),
                GetSqlParameterWithoutDirection("@OriginId", SqlDbType.UniqueIdentifier, 16, this.OriginId),
                GetSqlParameterWithoutDirection("@Remarks", SqlDbType.NVarChar, 255, this.Remarks),
                GetSqlParameterWithoutDirection("@ColorPattern", SqlDbType.NVarChar, 255, this.ColorPattern),
                GetSqlParameterWithoutDirection("@Barcode", SqlDbType.VarChar, 16, this.Barcode),
                GetSqlParameterWithoutDirection("@UnitCost", SqlDbType.Decimal, 9, this.UnitCost),
                GetSqlParameterWithoutDirection("@CurrencyId", SqlDbType.UniqueIdentifier, 16, this.CurrencyId),
                GetSqlParameterWithoutDirection("@Status", SqlDbType.Int, 4, this.Status),
                GetSqlParameterWithoutDirection("@CreatedOn", SqlDbType.DateTime, 8, this.CreatedOn),
                GetSqlParameterWithoutDirection("@CreatedBy", SqlDbType.UniqueIdentifier, 16, this.CreatedBy),
                GetSqlParameterWithoutDirection("@ModifiedOn", SqlDbType.DateTime, 8, this.ModifiedOn),
                GetSqlParameterWithoutDirection("@ModifiedBy", SqlDbType.UniqueIdentifier, 16, this.ModifiedBy),
                GetSqlParameterWithoutDirection("@Retired", SqlDbType.Bit, 1, this.Retired),
                GetSqlParameterWithoutDirection("@RetiredOn", SqlDbType.DateTime, 8, this.RetiredOn),
                GetSqlParameterWithoutDirection("@RetiredBy", SqlDbType.UniqueIdentifier, 16, this.RetiredBy)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("articleId: " + articleId.ToString()).Append("\r\n");
            builder.Append("sKU: " + sKU.ToString()).Append("\r\n");
            builder.Append("articleCode: " + articleCode.ToString()).Append("\r\n");
            builder.Append("articleName: " + articleName.ToString()).Append("\r\n");
            builder.Append("articleName_Chs: " + articleName_Chs.ToString()).Append("\r\n");
            builder.Append("articleName_Cht: " + articleName_Cht.ToString()).Append("\r\n");
            builder.Append("categoryId: " + categoryId.ToString()).Append("\r\n");
            builder.Append("ageGradingId: " + ageGradingId.ToString()).Append("\r\n");
            builder.Append("colorId: " + colorId.ToString()).Append("\r\n");
            builder.Append("originId: " + originId.ToString()).Append("\r\n");
            builder.Append("remarks: " + remarks.ToString()).Append("\r\n");
            builder.Append("colorPattern: " + colorPattern.ToString()).Append("\r\n");
            builder.Append("barcode: " + barcode.ToString()).Append("\r\n");
            builder.Append("unitCost: " + unitCost.ToString()).Append("\r\n");
            builder.Append("currencyId: " + currencyId.ToString()).Append("\r\n");
            builder.Append("status: " + status.ToString()).Append("\r\n");
            builder.Append("createdOn: " + createdOn.ToString()).Append("\r\n");
            builder.Append("createdBy: " + createdBy.ToString()).Append("\r\n");
            builder.Append("modifiedOn: " + modifiedOn.ToString()).Append("\r\n");
            builder.Append("modifiedBy: " + modifiedBy.ToString()).Append("\r\n");
            builder.Append("retired: " + retired.ToString()).Append("\r\n");
            builder.Append("retiredOn: " + retiredOn.ToString()).Append("\r\n");
            builder.Append("retiredBy: " + retiredBy.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }

        #region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            string[] textField = { TextField };
            LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            if (SwitchLocale)
            {
                TextField = GetSwitchLocale(TextField);
            }
            ddList.Items.Clear();

            ArticleCollection source;

            if (OrderBy == null || OrderBy.Length == 0)
            {
                OrderBy = TextField;
            }
            // Filter the retired records
            if (WhereClause.Length > 0)
            {
                WhereClause += " AND Retired = 0";
            }
            else
            {
                WhereClause = "Retired = 0";
            }

            if (WhereClause.Length > 0)
            {
                source = Article.LoadCollection(WhereClause, OrderBy, true);
            }
            else
            {
                source = Article.LoadCollection(OrderBy, true);
            }

            Common.ComboList sourceList = new Common.ComboList();

            if (BlankLine)
            {
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
            }

            foreach (Article item in source)
            {
                bool filter = false;
                if (ParentFilter.Trim() != String.Empty)
                {
                    filter = true;
                    if (item.CategoryId != Guid.Empty)
                    {
                        filter = IgnorThis(item, ParentFilter);
                    }
                }
                if (!(filter))
                {
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.ArticleId));
                }
            }

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";

            if (ddList.Items.Count > 0)
            {
                ddList.SelectedIndex = 0;
            }
        }

        #endregion


        private static bool IgnorThis(Article target, string parentFilter)
        {
            bool result = true;
            parentFilter = parentFilter.Replace(" ", "");       // remove spaces
            parentFilter = parentFilter.Replace("'", "");       // remove '
            string[] parsed = parentFilter.Split('=');          // parse

            if (target.CategoryId == Guid.Empty)
            {
                PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
                string filterField = (string)pi.GetValue(target, null);
                if (filterField.ToLower() == parsed[1].ToLower())
                {
                    result = false;
                }
            }
            else
            {
                Article parentTemplate = Article.Load(target.CategoryId);
                result = IgnorThis(parentTemplate, parentFilter);
            }
            return result;
        }

        private static string GetFormatedText(Article target, string[] textField, string textFormatString)
        {
            for (int i = 0; i < textField.Length; i++)
            {
                PropertyInfo pi = target.GetType().GetProperty(textField[i]);
                textFormatString = textFormatString.Replace("{" + i.ToString() + "}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
            }
            return textFormatString;
        }

        private static string[] GetSwitchLocale(string[] source)
        {
            switch (Common.Config.CurrentLanguageId)
            {
                case 2:
                    source[source.Length - 1] += "_Chs";
                    break;
                case 3:
                    source[source.Length - 1] += "_Cht";
                    break;
            }
            return source;
        }
    }


    /// <summary>
    /// Represents a collection of <see cref="Article">Article</see> objects.
    /// </summary>
    public class ArticleCollection : BindingList<Article>
    {
    }
}
