using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace xPort5.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.ArticleCustomer.
    /// Date Created:   2020-03-02 02:12:36
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class ArticleCustomer
    {
        private Guid key = Guid.Empty;
        private Guid articleCustomerId = Guid.Empty;
        private Guid articleId = Guid.Empty;
        private Guid customerId = Guid.Empty;
        private bool defaultRec;
        private string custRef = String.Empty;
        private Guid currencyId = Guid.Empty;
        private decimal fCLPrice;
        private decimal lCLPrice;
        private decimal unitPrice;
        private DateTime dateRevised = DateTime.Parse("1900-1-1");
        private string notes = String.Empty;
        private DateTime createdOn = DateTime.Parse("1900-1-1");
        private Guid createdBy = Guid.Empty;
        private DateTime modifiedOn = DateTime.Parse("1900-1-1");
        private Guid modifiedBy = Guid.Empty;
        private bool retired;
        private DateTime retiredOn = DateTime.Parse("1900-1-1");
        private Guid retiredBy = Guid.Empty;

        /// <summary>
        /// Initialize an new empty ArticleCustomer object.
        /// </summary>
        public ArticleCustomer()
        {
        }

        /// <summary>
        /// Initialize a new ArticleCustomer object with the given parameters.
        /// </summary>
        public ArticleCustomer(Guid articleCustomerId, Guid articleId, Guid customerId, bool defaultRec, string custRef, Guid currencyId, decimal fCLPrice, decimal lCLPrice, decimal unitPrice, DateTime dateRevised, string notes, DateTime createdOn, Guid createdBy, DateTime modifiedOn, Guid modifiedBy, bool retired, DateTime retiredOn, Guid retiredBy)
        {
            this.articleCustomerId = articleCustomerId;
            this.articleId = articleId;
            this.customerId = customerId;
            this.defaultRec = defaultRec;
            this.custRef = custRef;
            this.currencyId = currencyId;
            this.fCLPrice = fCLPrice;
            this.lCLPrice = lCLPrice;
            this.unitPrice = unitPrice;
            this.dateRevised = dateRevised;
            this.notes = notes;
            this.createdOn = createdOn;
            this.createdBy = createdBy;
            this.modifiedOn = modifiedOn;
            this.modifiedBy = modifiedBy;
            this.retired = retired;
            this.retiredOn = retiredOn;
            this.retiredBy = retiredBy;
        }

        /// <summary>
        /// Loads a ArticleCustomer object from the database using the given ArticleCustomerId
        /// </summary>
        /// <param name="articleCustomerId">The primary key value</param>
        /// <returns>A ArticleCustomer object</returns>
        public static ArticleCustomer Load(Guid articleCustomerId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@ArticleCustomerId", articleCustomerId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spArticleCustomer_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    ArticleCustomer result = new ArticleCustomer();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a ArticleCustomer object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A ArticleCustomer object</returns>
        public static ArticleCustomer LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spArticleCustomer_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    ArticleCustomer result = new ArticleCustomer();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a collection of ArticleCustomer objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the ArticleCustomer objects in the database.</returns>
        public static ArticleCustomerCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] { };
            return LoadCollection("spArticleCustomer_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of ArticleCustomer objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the ArticleCustomer objects in the database ordered by the columns specified.</returns>
        public static ArticleCustomerCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spArticleCustomer_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of ArticleCustomer objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the ArticleCustomer objects in the database.</returns>
        public static ArticleCustomerCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spArticleCustomer_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of ArticleCustomer objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the ArticleCustomer objects in the database ordered by the columns specified.</returns>
        public static ArticleCustomerCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spArticleCustomer_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of ArticleCustomer objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the ArticleCustomer objects in the database.</returns>
        public static ArticleCustomerCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            ArticleCustomerCollection result = new ArticleCustomerCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    ArticleCustomer tmp = new ArticleCustomer();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a ArticleCustomer object from the database.
        /// </summary>
        /// <param name="articleCustomerId">The primary key value</param>
        public static void Delete(Guid articleCustomerId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@ArticleCustomerId", articleCustomerId) };
            SqlHelper.Default.ExecuteNonQuery("spArticleCustomer_DelRec", parameterValues);
        }


        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) articleCustomerId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) articleId = reader.GetGuid(1);
                if (!reader.IsDBNull(2)) customerId = reader.GetGuid(2);
                if (!reader.IsDBNull(3)) defaultRec = reader.GetBoolean(3);
                if (!reader.IsDBNull(4)) custRef = reader.GetString(4);
                if (!reader.IsDBNull(5)) currencyId = reader.GetGuid(5);
                if (!reader.IsDBNull(6)) fCLPrice = reader.GetDecimal(6);
                if (!reader.IsDBNull(7)) lCLPrice = reader.GetDecimal(7);
                if (!reader.IsDBNull(8)) unitPrice = reader.GetDecimal(8);
                if (!reader.IsDBNull(9)) dateRevised = reader.GetDateTime(9);
                if (!reader.IsDBNull(10)) notes = reader.GetString(10);
                if (!reader.IsDBNull(11)) createdOn = reader.GetDateTime(11);
                if (!reader.IsDBNull(12)) createdBy = reader.GetGuid(12);
                if (!reader.IsDBNull(13)) modifiedOn = reader.GetDateTime(13);
                if (!reader.IsDBNull(14)) modifiedBy = reader.GetGuid(14);
                if (!reader.IsDBNull(15)) retired = reader.GetBoolean(15);
                if (!reader.IsDBNull(16)) retiredOn = reader.GetDateTime(16);
                if (!reader.IsDBNull(17)) retiredBy = reader.GetGuid(17);
            }
        }

        public void Delete()
        {
            Delete(this.ArticleCustomerId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != ArticleCustomerId)
                    this.Delete();
                Update();
            }
        }

        public Guid ArticleCustomerId
        {
            get { return articleCustomerId; }
            set { articleCustomerId = value; }
        }

        public Guid ArticleId
        {
            get { return articleId; }
            set { articleId = value; }
        }

        public Guid CustomerId
        {
            get { return customerId; }
            set { customerId = value; }
        }

        public bool DefaultRec
        {
            get { return defaultRec; }
            set { defaultRec = value; }
        }

        public string CustRef
        {
            get { return custRef; }
            set { custRef = value; }
        }

        public Guid CurrencyId
        {
            get { return currencyId; }
            set { currencyId = value; }
        }

        public decimal FCLPrice
        {
            get { return fCLPrice; }
            set { fCLPrice = value; }
        }

        public decimal LCLPrice
        {
            get { return lCLPrice; }
            set { lCLPrice = value; }
        }

        public decimal UnitPrice
        {
            get { return unitPrice; }
            set { unitPrice = value; }
        }

        public DateTime DateRevised
        {
            get { return dateRevised; }
            set { dateRevised = value; }
        }

        public string Notes
        {
            get { return notes; }
            set { notes = value; }
        }

        public DateTime CreatedOn
        {
            get { return createdOn; }
            set { createdOn = value; }
        }

        public Guid CreatedBy
        {
            get { return createdBy; }
            set { createdBy = value; }
        }

        public DateTime ModifiedOn
        {
            get { return modifiedOn; }
            set { modifiedOn = value; }
        }

        public Guid ModifiedBy
        {
            get { return modifiedBy; }
            set { modifiedBy = value; }
        }

        public bool Retired
        {
            get { return retired; }
            set { retired = value; }
        }

        public DateTime RetiredOn
        {
            get { return retiredOn; }
            set { retiredOn = value; }
        }

        public Guid RetiredBy
        {
            get { return retiredBy; }
            set { retiredBy = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;

            SqlHelper.Default.ExecuteNonQuery("spArticleCustomer_InsRec", "@ArticleCustomerId", out returnedValue, parameterValues);

            articleCustomerId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();

            SqlHelper.Default.ExecuteNonQuery("spArticleCustomer_UpdRec", parameterValues);
        }

        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[18];
            prams[0] = GetSqlParameter("@ArticleCustomerId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.ArticleCustomerId);
            prams[1] = GetSqlParameter("@ArticleId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.ArticleId);
            prams[2] = GetSqlParameter("@CustomerId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.CustomerId);
            prams[3] = GetSqlParameter("@DefaultRec", ParameterDirection.Input, SqlDbType.Bit, 1, this.DefaultRec);
            prams[4] = GetSqlParameter("@CustRef", ParameterDirection.Input, SqlDbType.NVarChar, 32, this.CustRef);
            prams[5] = GetSqlParameter("@CurrencyId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.CurrencyId);
            prams[6] = GetSqlParameter("@FCLPrice", ParameterDirection.Input, SqlDbType.Decimal, 9, this.FCLPrice);
            prams[7] = GetSqlParameter("@LCLPrice", ParameterDirection.Input, SqlDbType.Decimal, 9, this.LCLPrice);
            prams[8] = GetSqlParameter("@UnitPrice", ParameterDirection.Input, SqlDbType.Decimal, 9, this.UnitPrice);
            prams[9] = GetSqlParameter("@DateRevised", ParameterDirection.Input, SqlDbType.DateTime, 8, this.DateRevised);
            prams[10] = GetSqlParameter("@Notes", ParameterDirection.Input, SqlDbType.NVarChar, 255, this.Notes);
            prams[11] = GetSqlParameter("@CreatedOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.CreatedOn);
            prams[12] = GetSqlParameter("@CreatedBy", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.CreatedBy);
            prams[13] = GetSqlParameter("@ModifiedOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.ModifiedOn);
            prams[14] = GetSqlParameter("@ModifiedBy", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.ModifiedBy);
            prams[15] = GetSqlParameter("@Retired", ParameterDirection.Input, SqlDbType.Bit, 1, this.Retired);
            prams[16] = GetSqlParameter("@RetiredOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.RetiredOn);
            prams[17] = GetSqlParameter("@RetiredBy", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.RetiredBy);
            return prams;
        }

        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }

        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[]
            {
                GetSqlParameterWithoutDirection("@ArticleCustomerId", SqlDbType.UniqueIdentifier, 16, this.ArticleCustomerId),
                GetSqlParameterWithoutDirection("@ArticleId", SqlDbType.UniqueIdentifier, 16, this.ArticleId),
                GetSqlParameterWithoutDirection("@CustomerId", SqlDbType.UniqueIdentifier, 16, this.CustomerId),
                GetSqlParameterWithoutDirection("@DefaultRec", SqlDbType.Bit, 1, this.DefaultRec),
                GetSqlParameterWithoutDirection("@CustRef", SqlDbType.NVarChar, 32, this.CustRef),
                GetSqlParameterWithoutDirection("@CurrencyId", SqlDbType.UniqueIdentifier, 16, this.CurrencyId),
                GetSqlParameterWithoutDirection("@FCLPrice", SqlDbType.Decimal, 9, this.FCLPrice),
                GetSqlParameterWithoutDirection("@LCLPrice", SqlDbType.Decimal, 9, this.LCLPrice),
                GetSqlParameterWithoutDirection("@UnitPrice", SqlDbType.Decimal, 9, this.UnitPrice),
                GetSqlParameterWithoutDirection("@DateRevised", SqlDbType.DateTime, 8, this.DateRevised),
                GetSqlParameterWithoutDirection("@Notes", SqlDbType.NVarChar, 255, this.Notes),
                GetSqlParameterWithoutDirection("@CreatedOn", SqlDbType.DateTime, 8, this.CreatedOn),
                GetSqlParameterWithoutDirection("@CreatedBy", SqlDbType.UniqueIdentifier, 16, this.CreatedBy),
                GetSqlParameterWithoutDirection("@ModifiedOn", SqlDbType.DateTime, 8, this.ModifiedOn),
                GetSqlParameterWithoutDirection("@ModifiedBy", SqlDbType.UniqueIdentifier, 16, this.ModifiedBy),
                GetSqlParameterWithoutDirection("@Retired", SqlDbType.Bit, 1, this.Retired),
                GetSqlParameterWithoutDirection("@RetiredOn", SqlDbType.DateTime, 8, this.RetiredOn),
                GetSqlParameterWithoutDirection("@RetiredBy", SqlDbType.UniqueIdentifier, 16, this.RetiredBy)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("articleCustomerId: " + articleCustomerId.ToString()).Append("\r\n");
            builder.Append("articleId: " + articleId.ToString()).Append("\r\n");
            builder.Append("customerId: " + customerId.ToString()).Append("\r\n");
            builder.Append("defaultRec: " + defaultRec.ToString()).Append("\r\n");
            builder.Append("custRef: " + custRef.ToString()).Append("\r\n");
            builder.Append("currencyId: " + currencyId.ToString()).Append("\r\n");
            builder.Append("fCLPrice: " + fCLPrice.ToString()).Append("\r\n");
            builder.Append("lCLPrice: " + lCLPrice.ToString()).Append("\r\n");
            builder.Append("unitPrice: " + unitPrice.ToString()).Append("\r\n");
            builder.Append("dateRevised: " + dateRevised.ToString()).Append("\r\n");
            builder.Append("notes: " + notes.ToString()).Append("\r\n");
            builder.Append("createdOn: " + createdOn.ToString()).Append("\r\n");
            builder.Append("createdBy: " + createdBy.ToString()).Append("\r\n");
            builder.Append("modifiedOn: " + modifiedOn.ToString()).Append("\r\n");
            builder.Append("modifiedBy: " + modifiedBy.ToString()).Append("\r\n");
            builder.Append("retired: " + retired.ToString()).Append("\r\n");
            builder.Append("retiredOn: " + retiredOn.ToString()).Append("\r\n");
            builder.Append("retiredBy: " + retiredBy.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }

        #region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            string[] textField = { TextField };
            LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            if (SwitchLocale)
            {
                TextField = GetSwitchLocale(TextField);
            }
            ddList.Items.Clear();

            ArticleCustomerCollection source;

            if (OrderBy == null || OrderBy.Length == 0)
            {
                OrderBy = TextField;
            }
            // Filter the retired records
            if (WhereClause.Length > 0)
            {
                WhereClause += " AND Retired = 0";
            }
            else
            {
                WhereClause = "Retired = 0";
            }

            if (WhereClause.Length > 0)
            {
                source = ArticleCustomer.LoadCollection(WhereClause, OrderBy, true);
            }
            else
            {
                source = ArticleCustomer.LoadCollection(OrderBy, true);
            }

            Common.ComboList sourceList = new Common.ComboList();

            if (BlankLine)
            {
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
            }

            foreach (ArticleCustomer item in source)
            {
                bool filter = false;
                if (ParentFilter.Trim() != String.Empty)
                {
                    filter = true;
                    if (item.ArticleId != Guid.Empty)
                    {
                        filter = IgnorThis(item, ParentFilter);
                    }
                }
                if (!(filter))
                {
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.ArticleCustomerId));
                }
            }

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";

            if (ddList.Items.Count > 0)
            {
                ddList.SelectedIndex = 0;
            }
        }

        #endregion


        private static bool IgnorThis(ArticleCustomer target, string parentFilter)
        {
            bool result = true;
            parentFilter = parentFilter.Replace(" ", "");       // remove spaces
            parentFilter = parentFilter.Replace("'", "");       // remove '
            string[] parsed = parentFilter.Split('=');          // parse

            if (target.ArticleId == Guid.Empty)
            {
                PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
                string filterField = (string)pi.GetValue(target, null);
                if (filterField.ToLower() == parsed[1].ToLower())
                {
                    result = false;
                }
            }
            else
            {
                ArticleCustomer parentTemplate = ArticleCustomer.Load(target.ArticleId);
                result = IgnorThis(parentTemplate, parentFilter);
            }
            return result;
        }

        private static string GetFormatedText(ArticleCustomer target, string[] textField, string textFormatString)
        {
            for (int i = 0; i < textField.Length; i++)
            {
                PropertyInfo pi = target.GetType().GetProperty(textField[i]);
                textFormatString = textFormatString.Replace("{" + i.ToString() + "}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
            }
            return textFormatString;
        }

        private static string[] GetSwitchLocale(string[] source)
        {
            switch (Common.Config.CurrentLanguageId)
            {
                case 2:
                    source[source.Length - 1] += "_Chs";
                    break;
                case 3:
                    source[source.Length - 1] += "_Cht";
                    break;
            }
            return source;
        }
    }


    /// <summary>
    /// Represents a collection of <see cref="ArticleCustomer">ArticleCustomer</see> objects.
    /// </summary>
    public class ArticleCustomerCollection : BindingList<ArticleCustomer>
    {
    }
}
