using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace xPort5.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.ArticlePackage.
    /// Date Created:   2020-03-02 02:13:28
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class ArticlePackage
    {
        private Guid key = Guid.Empty;
        private Guid articlePackageId = Guid.Empty;
        private Guid articleId = Guid.Empty;
        private Guid packageId = Guid.Empty;
        private bool defaultRec;
        private Guid uomId = Guid.Empty;
        private decimal innerBox;
        private decimal outerBox;
        private decimal cUFT;
        private decimal sizeLength_in;
        private decimal sizeWidth_in;
        private decimal sizeHeight_in;
        private decimal sizeLength_cm;
        private decimal sizeWidth_cm;
        private decimal sizeHeight_cm;
        private decimal weightGross_lb;
        private decimal weightNet_lb;
        private decimal weightGross_kg;
        private decimal weightNet_kg;
        private decimal containerQty;
        private string containerSize = String.Empty;
        private DateTime createdOn = DateTime.Parse("1900-1-1");
        private Guid createdBy = Guid.Empty;
        private DateTime modifiedOn = DateTime.Parse("1900-1-1");
        private Guid modifiedBy = Guid.Empty;
        private bool retired;
        private DateTime retiredOn = DateTime.Parse("1900-1-1");
        private Guid retiredBy = Guid.Empty;

        /// <summary>
        /// Initialize an new empty ArticlePackage object.
        /// </summary>
        public ArticlePackage()
        {
        }

        /// <summary>
        /// Initialize a new ArticlePackage object with the given parameters.
        /// </summary>
        public ArticlePackage(Guid articlePackageId, Guid articleId, Guid packageId, bool defaultRec, Guid uomId, decimal innerBox, decimal outerBox, decimal cUFT, decimal sizeLength_in, decimal sizeWidth_in, decimal sizeHeight_in, decimal sizeLength_cm, decimal sizeWidth_cm, decimal sizeHeight_cm, decimal weightGross_lb, decimal weightNet_lb, decimal weightGross_kg, decimal weightNet_kg, decimal containerQty, string containerSize, DateTime createdOn, Guid createdBy, DateTime modifiedOn, Guid modifiedBy, bool retired, DateTime retiredOn, Guid retiredBy)
        {
            this.articlePackageId = articlePackageId;
            this.articleId = articleId;
            this.packageId = packageId;
            this.defaultRec = defaultRec;
            this.uomId = uomId;
            this.innerBox = innerBox;
            this.outerBox = outerBox;
            this.cUFT = cUFT;
            this.sizeLength_in = sizeLength_in;
            this.sizeWidth_in = sizeWidth_in;
            this.sizeHeight_in = sizeHeight_in;
            this.sizeLength_cm = sizeLength_cm;
            this.sizeWidth_cm = sizeWidth_cm;
            this.sizeHeight_cm = sizeHeight_cm;
            this.weightGross_lb = weightGross_lb;
            this.weightNet_lb = weightNet_lb;
            this.weightGross_kg = weightGross_kg;
            this.weightNet_kg = weightNet_kg;
            this.containerQty = containerQty;
            this.containerSize = containerSize;
            this.createdOn = createdOn;
            this.createdBy = createdBy;
            this.modifiedOn = modifiedOn;
            this.modifiedBy = modifiedBy;
            this.retired = retired;
            this.retiredOn = retiredOn;
            this.retiredBy = retiredBy;
        }

        /// <summary>
        /// Loads a ArticlePackage object from the database using the given ArticlePackageId
        /// </summary>
        /// <param name="articlePackageId">The primary key value</param>
        /// <returns>A ArticlePackage object</returns>
        public static ArticlePackage Load(Guid articlePackageId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@ArticlePackageId", articlePackageId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spArticlePackage_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    ArticlePackage result = new ArticlePackage();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a ArticlePackage object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A ArticlePackage object</returns>
        public static ArticlePackage LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spArticlePackage_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    ArticlePackage result = new ArticlePackage();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a collection of ArticlePackage objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the ArticlePackage objects in the database.</returns>
        public static ArticlePackageCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] { };
            return LoadCollection("spArticlePackage_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of ArticlePackage objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the ArticlePackage objects in the database ordered by the columns specified.</returns>
        public static ArticlePackageCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spArticlePackage_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of ArticlePackage objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the ArticlePackage objects in the database.</returns>
        public static ArticlePackageCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spArticlePackage_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of ArticlePackage objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the ArticlePackage objects in the database ordered by the columns specified.</returns>
        public static ArticlePackageCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spArticlePackage_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of ArticlePackage objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the ArticlePackage objects in the database.</returns>
        public static ArticlePackageCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            ArticlePackageCollection result = new ArticlePackageCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    ArticlePackage tmp = new ArticlePackage();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a ArticlePackage object from the database.
        /// </summary>
        /// <param name="articlePackageId">The primary key value</param>
        public static void Delete(Guid articlePackageId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@ArticlePackageId", articlePackageId) };
            SqlHelper.Default.ExecuteNonQuery("spArticlePackage_DelRec", parameterValues);
        }


        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) articlePackageId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) articleId = reader.GetGuid(1);
                if (!reader.IsDBNull(2)) packageId = reader.GetGuid(2);
                if (!reader.IsDBNull(3)) defaultRec = reader.GetBoolean(3);
                if (!reader.IsDBNull(4)) uomId = reader.GetGuid(4);
                if (!reader.IsDBNull(5)) innerBox = reader.GetDecimal(5);
                if (!reader.IsDBNull(6)) outerBox = reader.GetDecimal(6);
                if (!reader.IsDBNull(7)) cUFT = reader.GetDecimal(7);
                if (!reader.IsDBNull(8)) sizeLength_in = reader.GetDecimal(8);
                if (!reader.IsDBNull(9)) sizeWidth_in = reader.GetDecimal(9);
                if (!reader.IsDBNull(10)) sizeHeight_in = reader.GetDecimal(10);
                if (!reader.IsDBNull(11)) sizeLength_cm = reader.GetDecimal(11);
                if (!reader.IsDBNull(12)) sizeWidth_cm = reader.GetDecimal(12);
                if (!reader.IsDBNull(13)) sizeHeight_cm = reader.GetDecimal(13);
                if (!reader.IsDBNull(14)) weightGross_lb = reader.GetDecimal(14);
                if (!reader.IsDBNull(15)) weightNet_lb = reader.GetDecimal(15);
                if (!reader.IsDBNull(16)) weightGross_kg = reader.GetDecimal(16);
                if (!reader.IsDBNull(17)) weightNet_kg = reader.GetDecimal(17);
                if (!reader.IsDBNull(18)) containerQty = reader.GetDecimal(18);
                if (!reader.IsDBNull(19)) containerSize = reader.GetString(19);
                if (!reader.IsDBNull(20)) createdOn = reader.GetDateTime(20);
                if (!reader.IsDBNull(21)) createdBy = reader.GetGuid(21);
                if (!reader.IsDBNull(22)) modifiedOn = reader.GetDateTime(22);
                if (!reader.IsDBNull(23)) modifiedBy = reader.GetGuid(23);
                if (!reader.IsDBNull(24)) retired = reader.GetBoolean(24);
                if (!reader.IsDBNull(25)) retiredOn = reader.GetDateTime(25);
                if (!reader.IsDBNull(26)) retiredBy = reader.GetGuid(26);
            }
        }

        public void Delete()
        {
            Delete(this.ArticlePackageId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != ArticlePackageId)
                    this.Delete();
                Update();
            }
        }

        public Guid ArticlePackageId
        {
            get { return articlePackageId; }
            set { articlePackageId = value; }
        }

        public Guid ArticleId
        {
            get { return articleId; }
            set { articleId = value; }
        }

        public Guid PackageId
        {
            get { return packageId; }
            set { packageId = value; }
        }

        public bool DefaultRec
        {
            get { return defaultRec; }
            set { defaultRec = value; }
        }

        public Guid UomId
        {
            get { return uomId; }
            set { uomId = value; }
        }

        public decimal InnerBox
        {
            get { return innerBox; }
            set { innerBox = value; }
        }

        public decimal OuterBox
        {
            get { return outerBox; }
            set { outerBox = value; }
        }

        public decimal CUFT
        {
            get { return cUFT; }
            set { cUFT = value; }
        }

        public decimal SizeLength_in
        {
            get { return sizeLength_in; }
            set { sizeLength_in = value; }
        }

        public decimal SizeWidth_in
        {
            get { return sizeWidth_in; }
            set { sizeWidth_in = value; }
        }

        public decimal SizeHeight_in
        {
            get { return sizeHeight_in; }
            set { sizeHeight_in = value; }
        }

        public decimal SizeLength_cm
        {
            get { return sizeLength_cm; }
            set { sizeLength_cm = value; }
        }

        public decimal SizeWidth_cm
        {
            get { return sizeWidth_cm; }
            set { sizeWidth_cm = value; }
        }

        public decimal SizeHeight_cm
        {
            get { return sizeHeight_cm; }
            set { sizeHeight_cm = value; }
        }

        public decimal WeightGross_lb
        {
            get { return weightGross_lb; }
            set { weightGross_lb = value; }
        }

        public decimal WeightNet_lb
        {
            get { return weightNet_lb; }
            set { weightNet_lb = value; }
        }

        public decimal WeightGross_kg
        {
            get { return weightGross_kg; }
            set { weightGross_kg = value; }
        }

        public decimal WeightNet_kg
        {
            get { return weightNet_kg; }
            set { weightNet_kg = value; }
        }

        public decimal ContainerQty
        {
            get { return containerQty; }
            set { containerQty = value; }
        }

        public string ContainerSize
        {
            get { return containerSize; }
            set { containerSize = value; }
        }

        public DateTime CreatedOn
        {
            get { return createdOn; }
            set { createdOn = value; }
        }

        public Guid CreatedBy
        {
            get { return createdBy; }
            set { createdBy = value; }
        }

        public DateTime ModifiedOn
        {
            get { return modifiedOn; }
            set { modifiedOn = value; }
        }

        public Guid ModifiedBy
        {
            get { return modifiedBy; }
            set { modifiedBy = value; }
        }

        public bool Retired
        {
            get { return retired; }
            set { retired = value; }
        }

        public DateTime RetiredOn
        {
            get { return retiredOn; }
            set { retiredOn = value; }
        }

        public Guid RetiredBy
        {
            get { return retiredBy; }
            set { retiredBy = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;

            SqlHelper.Default.ExecuteNonQuery("spArticlePackage_InsRec", "@ArticlePackageId", out returnedValue, parameterValues);

            articlePackageId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();

            SqlHelper.Default.ExecuteNonQuery("spArticlePackage_UpdRec", parameterValues);
        }

        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[27];
            prams[0] = GetSqlParameter("@ArticlePackageId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.ArticlePackageId);
            prams[1] = GetSqlParameter("@ArticleId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.ArticleId);
            prams[2] = GetSqlParameter("@PackageId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.PackageId);
            prams[3] = GetSqlParameter("@DefaultRec", ParameterDirection.Input, SqlDbType.Bit, 1, this.DefaultRec);
            prams[4] = GetSqlParameter("@UomId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.UomId);
            prams[5] = GetSqlParameter("@InnerBox", ParameterDirection.Input, SqlDbType.Decimal, 9, this.InnerBox);
            prams[6] = GetSqlParameter("@OuterBox", ParameterDirection.Input, SqlDbType.Decimal, 9, this.OuterBox);
            prams[7] = GetSqlParameter("@CUFT", ParameterDirection.Input, SqlDbType.Decimal, 9, this.CUFT);
            prams[8] = GetSqlParameter("@SizeLength_in", ParameterDirection.Input, SqlDbType.Decimal, 9, this.SizeLength_in);
            prams[9] = GetSqlParameter("@SizeWidth_in", ParameterDirection.Input, SqlDbType.Decimal, 9, this.SizeWidth_in);
            prams[10] = GetSqlParameter("@SizeHeight_in", ParameterDirection.Input, SqlDbType.Decimal, 9, this.SizeHeight_in);
            prams[11] = GetSqlParameter("@SizeLength_cm", ParameterDirection.Input, SqlDbType.Decimal, 9, this.SizeLength_cm);
            prams[12] = GetSqlParameter("@SizeWidth_cm", ParameterDirection.Input, SqlDbType.Decimal, 9, this.SizeWidth_cm);
            prams[13] = GetSqlParameter("@SizeHeight_cm", ParameterDirection.Input, SqlDbType.Decimal, 9, this.SizeHeight_cm);
            prams[14] = GetSqlParameter("@WeightGross_lb", ParameterDirection.Input, SqlDbType.Decimal, 9, this.WeightGross_lb);
            prams[15] = GetSqlParameter("@WeightNet_lb", ParameterDirection.Input, SqlDbType.Decimal, 9, this.WeightNet_lb);
            prams[16] = GetSqlParameter("@WeightGross_kg", ParameterDirection.Input, SqlDbType.Decimal, 9, this.WeightGross_kg);
            prams[17] = GetSqlParameter("@WeightNet_kg", ParameterDirection.Input, SqlDbType.Decimal, 9, this.WeightNet_kg);
            prams[18] = GetSqlParameter("@ContainerQty", ParameterDirection.Input, SqlDbType.Decimal, 9, this.ContainerQty);
            prams[19] = GetSqlParameter("@ContainerSize", ParameterDirection.Input, SqlDbType.VarChar, 4, this.ContainerSize);
            prams[20] = GetSqlParameter("@CreatedOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.CreatedOn);
            prams[21] = GetSqlParameter("@CreatedBy", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.CreatedBy);
            prams[22] = GetSqlParameter("@ModifiedOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.ModifiedOn);
            prams[23] = GetSqlParameter("@ModifiedBy", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.ModifiedBy);
            prams[24] = GetSqlParameter("@Retired", ParameterDirection.Input, SqlDbType.Bit, 1, this.Retired);
            prams[25] = GetSqlParameter("@RetiredOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.RetiredOn);
            prams[26] = GetSqlParameter("@RetiredBy", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.RetiredBy);
            return prams;
        }

        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }

        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[]
            {
                GetSqlParameterWithoutDirection("@ArticlePackageId", SqlDbType.UniqueIdentifier, 16, this.ArticlePackageId),
                GetSqlParameterWithoutDirection("@ArticleId", SqlDbType.UniqueIdentifier, 16, this.ArticleId),
                GetSqlParameterWithoutDirection("@PackageId", SqlDbType.UniqueIdentifier, 16, this.PackageId),
                GetSqlParameterWithoutDirection("@DefaultRec", SqlDbType.Bit, 1, this.DefaultRec),
                GetSqlParameterWithoutDirection("@UomId", SqlDbType.UniqueIdentifier, 16, this.UomId),
                GetSqlParameterWithoutDirection("@InnerBox", SqlDbType.Decimal, 9, this.InnerBox),
                GetSqlParameterWithoutDirection("@OuterBox", SqlDbType.Decimal, 9, this.OuterBox),
                GetSqlParameterWithoutDirection("@CUFT", SqlDbType.Decimal, 9, this.CUFT),
                GetSqlParameterWithoutDirection("@SizeLength_in", SqlDbType.Decimal, 9, this.SizeLength_in),
                GetSqlParameterWithoutDirection("@SizeWidth_in", SqlDbType.Decimal, 9, this.SizeWidth_in),
                GetSqlParameterWithoutDirection("@SizeHeight_in", SqlDbType.Decimal, 9, this.SizeHeight_in),
                GetSqlParameterWithoutDirection("@SizeLength_cm", SqlDbType.Decimal, 9, this.SizeLength_cm),
                GetSqlParameterWithoutDirection("@SizeWidth_cm", SqlDbType.Decimal, 9, this.SizeWidth_cm),
                GetSqlParameterWithoutDirection("@SizeHeight_cm", SqlDbType.Decimal, 9, this.SizeHeight_cm),
                GetSqlParameterWithoutDirection("@WeightGross_lb", SqlDbType.Decimal, 9, this.WeightGross_lb),
                GetSqlParameterWithoutDirection("@WeightNet_lb", SqlDbType.Decimal, 9, this.WeightNet_lb),
                GetSqlParameterWithoutDirection("@WeightGross_kg", SqlDbType.Decimal, 9, this.WeightGross_kg),
                GetSqlParameterWithoutDirection("@WeightNet_kg", SqlDbType.Decimal, 9, this.WeightNet_kg),
                GetSqlParameterWithoutDirection("@ContainerQty", SqlDbType.Decimal, 9, this.ContainerQty),
                GetSqlParameterWithoutDirection("@ContainerSize", SqlDbType.VarChar, 4, this.ContainerSize),
                GetSqlParameterWithoutDirection("@CreatedOn", SqlDbType.DateTime, 8, this.CreatedOn),
                GetSqlParameterWithoutDirection("@CreatedBy", SqlDbType.UniqueIdentifier, 16, this.CreatedBy),
                GetSqlParameterWithoutDirection("@ModifiedOn", SqlDbType.DateTime, 8, this.ModifiedOn),
                GetSqlParameterWithoutDirection("@ModifiedBy", SqlDbType.UniqueIdentifier, 16, this.ModifiedBy),
                GetSqlParameterWithoutDirection("@Retired", SqlDbType.Bit, 1, this.Retired),
                GetSqlParameterWithoutDirection("@RetiredOn", SqlDbType.DateTime, 8, this.RetiredOn),
                GetSqlParameterWithoutDirection("@RetiredBy", SqlDbType.UniqueIdentifier, 16, this.RetiredBy)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("articlePackageId: " + articlePackageId.ToString()).Append("\r\n");
            builder.Append("articleId: " + articleId.ToString()).Append("\r\n");
            builder.Append("packageId: " + packageId.ToString()).Append("\r\n");
            builder.Append("defaultRec: " + defaultRec.ToString()).Append("\r\n");
            builder.Append("uomId: " + uomId.ToString()).Append("\r\n");
            builder.Append("innerBox: " + innerBox.ToString()).Append("\r\n");
            builder.Append("outerBox: " + outerBox.ToString()).Append("\r\n");
            builder.Append("cUFT: " + cUFT.ToString()).Append("\r\n");
            builder.Append("sizeLength_in: " + sizeLength_in.ToString()).Append("\r\n");
            builder.Append("sizeWidth_in: " + sizeWidth_in.ToString()).Append("\r\n");
            builder.Append("sizeHeight_in: " + sizeHeight_in.ToString()).Append("\r\n");
            builder.Append("sizeLength_cm: " + sizeLength_cm.ToString()).Append("\r\n");
            builder.Append("sizeWidth_cm: " + sizeWidth_cm.ToString()).Append("\r\n");
            builder.Append("sizeHeight_cm: " + sizeHeight_cm.ToString()).Append("\r\n");
            builder.Append("weightGross_lb: " + weightGross_lb.ToString()).Append("\r\n");
            builder.Append("weightNet_lb: " + weightNet_lb.ToString()).Append("\r\n");
            builder.Append("weightGross_kg: " + weightGross_kg.ToString()).Append("\r\n");
            builder.Append("weightNet_kg: " + weightNet_kg.ToString()).Append("\r\n");
            builder.Append("containerQty: " + containerQty.ToString()).Append("\r\n");
            builder.Append("containerSize: " + containerSize.ToString()).Append("\r\n");
            builder.Append("createdOn: " + createdOn.ToString()).Append("\r\n");
            builder.Append("createdBy: " + createdBy.ToString()).Append("\r\n");
            builder.Append("modifiedOn: " + modifiedOn.ToString()).Append("\r\n");
            builder.Append("modifiedBy: " + modifiedBy.ToString()).Append("\r\n");
            builder.Append("retired: " + retired.ToString()).Append("\r\n");
            builder.Append("retiredOn: " + retiredOn.ToString()).Append("\r\n");
            builder.Append("retiredBy: " + retiredBy.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }

        #region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            string[] textField = { TextField };
            LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            if (SwitchLocale)
            {
                TextField = GetSwitchLocale(TextField);
            }
            ddList.Items.Clear();

            ArticlePackageCollection source;

            if (OrderBy == null || OrderBy.Length == 0)
            {
                OrderBy = TextField;
            }
            // Filter the retired records
            if (WhereClause.Length > 0)
            {
                WhereClause += " AND Retired = 0";
            }
            else
            {
                WhereClause = "Retired = 0";
            }

            if (WhereClause.Length > 0)
            {
                source = ArticlePackage.LoadCollection(WhereClause, OrderBy, true);
            }
            else
            {
                source = ArticlePackage.LoadCollection(OrderBy, true);
            }

            Common.ComboList sourceList = new Common.ComboList();

            if (BlankLine)
            {
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
            }

            foreach (ArticlePackage item in source)
            {
                bool filter = false;
                if (ParentFilter.Trim() != String.Empty)
                {
                    filter = true;
                    if (item.ArticleId != Guid.Empty)
                    {
                        filter = IgnorThis(item, ParentFilter);
                    }
                }
                if (!(filter))
                {
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.ArticlePackageId));
                }
            }

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";

            if (ddList.Items.Count > 0)
            {
                ddList.SelectedIndex = 0;
            }
        }

        #endregion


        private static bool IgnorThis(ArticlePackage target, string parentFilter)
        {
            bool result = true;
            parentFilter = parentFilter.Replace(" ", "");       // remove spaces
            parentFilter = parentFilter.Replace("'", "");       // remove '
            string[] parsed = parentFilter.Split('=');          // parse

            if (target.ArticleId == Guid.Empty)
            {
                PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
                string filterField = (string)pi.GetValue(target, null);
                if (filterField.ToLower() == parsed[1].ToLower())
                {
                    result = false;
                }
            }
            else
            {
                ArticlePackage parentTemplate = ArticlePackage.Load(target.ArticleId);
                result = IgnorThis(parentTemplate, parentFilter);
            }
            return result;
        }

        private static string GetFormatedText(ArticlePackage target, string[] textField, string textFormatString)
        {
            for (int i = 0; i < textField.Length; i++)
            {
                PropertyInfo pi = target.GetType().GetProperty(textField[i]);
                textFormatString = textFormatString.Replace("{" + i.ToString() + "}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
            }
            return textFormatString;
        }

        private static string[] GetSwitchLocale(string[] source)
        {
            switch (Common.Config.CurrentLanguageId)
            {
                case 2:
                    source[source.Length - 1] += "_Chs";
                    break;
                case 3:
                    source[source.Length - 1] += "_Cht";
                    break;
            }
            return source;
        }
    }


    /// <summary>
    /// Represents a collection of <see cref="ArticlePackage">ArticlePackage</see> objects.
    /// </summary>
    public class ArticlePackageCollection : BindingList<ArticlePackage>
    {
    }
}
