using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace xPort5.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.CustomerContact.
    /// Date Created:   2020-03-02 02:15:37
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class CustomerContact
    {
        private Guid key = Guid.Empty;
        private Guid customerContactId = Guid.Empty;
        private Guid customerId = Guid.Empty;
        private bool defaultRec;
        private Guid salutationId = Guid.Empty;
        private string fullName = String.Empty;
        private string firstName = String.Empty;
        private string lastName = String.Empty;
        private Guid jobTitleId = Guid.Empty;
        private Guid phone1_Label = Guid.Empty;
        private string phone1_Text = String.Empty;
        private Guid phone2_Label = Guid.Empty;
        private string phone2_Text = String.Empty;
        private Guid phone3_Label = Guid.Empty;
        private string phone3_Text = String.Empty;
        private Guid phone4_Label = Guid.Empty;
        private string phone4_Text = String.Empty;
        private Guid phone5_Label = Guid.Empty;
        private string phone5_Text = String.Empty;
        private string notes = String.Empty;
        private DateTime createdOn = DateTime.Parse("1900-1-1");
        private Guid createdBy = Guid.Empty;
        private DateTime modifiedOn = DateTime.Parse("1900-1-1");
        private Guid modifiedBy = Guid.Empty;
        private bool retired;
        private DateTime retiredOn = DateTime.Parse("1900-1-1");
        private Guid retiredBy = Guid.Empty;

        /// <summary>
        /// Initialize an new empty CustomerContact object.
        /// </summary>
        public CustomerContact()
        {
        }

        /// <summary>
        /// Initialize a new CustomerContact object with the given parameters.
        /// </summary>
        public CustomerContact(Guid customerContactId, Guid customerId, bool defaultRec, Guid salutationId, string fullName, string firstName, string lastName, Guid jobTitleId, Guid phone1_Label, string phone1_Text, Guid phone2_Label, string phone2_Text, Guid phone3_Label, string phone3_Text, Guid phone4_Label, string phone4_Text, Guid phone5_Label, string phone5_Text, string notes, DateTime createdOn, Guid createdBy, DateTime modifiedOn, Guid modifiedBy, bool retired, DateTime retiredOn, Guid retiredBy)
        {
            this.customerContactId = customerContactId;
            this.customerId = customerId;
            this.defaultRec = defaultRec;
            this.salutationId = salutationId;
            this.fullName = fullName;
            this.firstName = firstName;
            this.lastName = lastName;
            this.jobTitleId = jobTitleId;
            this.phone1_Label = phone1_Label;
            this.phone1_Text = phone1_Text;
            this.phone2_Label = phone2_Label;
            this.phone2_Text = phone2_Text;
            this.phone3_Label = phone3_Label;
            this.phone3_Text = phone3_Text;
            this.phone4_Label = phone4_Label;
            this.phone4_Text = phone4_Text;
            this.phone5_Label = phone5_Label;
            this.phone5_Text = phone5_Text;
            this.notes = notes;
            this.createdOn = createdOn;
            this.createdBy = createdBy;
            this.modifiedOn = modifiedOn;
            this.modifiedBy = modifiedBy;
            this.retired = retired;
            this.retiredOn = retiredOn;
            this.retiredBy = retiredBy;
        }

        /// <summary>
        /// Loads a CustomerContact object from the database using the given CustomerContactId
        /// </summary>
        /// <param name="customerContactId">The primary key value</param>
        /// <returns>A CustomerContact object</returns>
        public static CustomerContact Load(Guid customerContactId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@CustomerContactId", customerContactId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spCustomerContact_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    CustomerContact result = new CustomerContact();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a CustomerContact object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A CustomerContact object</returns>
        public static CustomerContact LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spCustomerContact_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    CustomerContact result = new CustomerContact();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a collection of CustomerContact objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the CustomerContact objects in the database.</returns>
        public static CustomerContactCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] { };
            return LoadCollection("spCustomerContact_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of CustomerContact objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the CustomerContact objects in the database ordered by the columns specified.</returns>
        public static CustomerContactCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spCustomerContact_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of CustomerContact objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the CustomerContact objects in the database.</returns>
        public static CustomerContactCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spCustomerContact_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of CustomerContact objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the CustomerContact objects in the database ordered by the columns specified.</returns>
        public static CustomerContactCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spCustomerContact_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of CustomerContact objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the CustomerContact objects in the database.</returns>
        public static CustomerContactCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            CustomerContactCollection result = new CustomerContactCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    CustomerContact tmp = new CustomerContact();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a CustomerContact object from the database.
        /// </summary>
        /// <param name="customerContactId">The primary key value</param>
        public static void Delete(Guid customerContactId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@CustomerContactId", customerContactId) };
            SqlHelper.Default.ExecuteNonQuery("spCustomerContact_DelRec", parameterValues);
        }


        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) customerContactId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) customerId = reader.GetGuid(1);
                if (!reader.IsDBNull(2)) defaultRec = reader.GetBoolean(2);
                if (!reader.IsDBNull(3)) salutationId = reader.GetGuid(3);
                if (!reader.IsDBNull(4)) fullName = reader.GetString(4);
                if (!reader.IsDBNull(5)) firstName = reader.GetString(5);
                if (!reader.IsDBNull(6)) lastName = reader.GetString(6);
                if (!reader.IsDBNull(7)) jobTitleId = reader.GetGuid(7);
                if (!reader.IsDBNull(8)) phone1_Label = reader.GetGuid(8);
                if (!reader.IsDBNull(9)) phone1_Text = reader.GetString(9);
                if (!reader.IsDBNull(10)) phone2_Label = reader.GetGuid(10);
                if (!reader.IsDBNull(11)) phone2_Text = reader.GetString(11);
                if (!reader.IsDBNull(12)) phone3_Label = reader.GetGuid(12);
                if (!reader.IsDBNull(13)) phone3_Text = reader.GetString(13);
                if (!reader.IsDBNull(14)) phone4_Label = reader.GetGuid(14);
                if (!reader.IsDBNull(15)) phone4_Text = reader.GetString(15);
                if (!reader.IsDBNull(16)) phone5_Label = reader.GetGuid(16);
                if (!reader.IsDBNull(17)) phone5_Text = reader.GetString(17);
                if (!reader.IsDBNull(18)) notes = reader.GetString(18);
                if (!reader.IsDBNull(19)) createdOn = reader.GetDateTime(19);
                if (!reader.IsDBNull(20)) createdBy = reader.GetGuid(20);
                if (!reader.IsDBNull(21)) modifiedOn = reader.GetDateTime(21);
                if (!reader.IsDBNull(22)) modifiedBy = reader.GetGuid(22);
                if (!reader.IsDBNull(23)) retired = reader.GetBoolean(23);
                if (!reader.IsDBNull(24)) retiredOn = reader.GetDateTime(24);
                if (!reader.IsDBNull(25)) retiredBy = reader.GetGuid(25);
            }
        }

        public void Delete()
        {
            Delete(this.CustomerContactId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != CustomerContactId)
                    this.Delete();
                Update();
            }
        }

        public Guid CustomerContactId
        {
            get { return customerContactId; }
            set { customerContactId = value; }
        }

        public Guid CustomerId
        {
            get { return customerId; }
            set { customerId = value; }
        }

        public bool DefaultRec
        {
            get { return defaultRec; }
            set { defaultRec = value; }
        }

        public Guid SalutationId
        {
            get { return salutationId; }
            set { salutationId = value; }
        }

        public string FullName
        {
            get { return fullName; }
            set { fullName = value; }
        }

        public string FirstName
        {
            get { return firstName; }
            set { firstName = value; }
        }

        public string LastName
        {
            get { return lastName; }
            set { lastName = value; }
        }

        public Guid JobTitleId
        {
            get { return jobTitleId; }
            set { jobTitleId = value; }
        }

        public Guid Phone1_Label
        {
            get { return phone1_Label; }
            set { phone1_Label = value; }
        }

        public string Phone1_Text
        {
            get { return phone1_Text; }
            set { phone1_Text = value; }
        }

        public Guid Phone2_Label
        {
            get { return phone2_Label; }
            set { phone2_Label = value; }
        }

        public string Phone2_Text
        {
            get { return phone2_Text; }
            set { phone2_Text = value; }
        }

        public Guid Phone3_Label
        {
            get { return phone3_Label; }
            set { phone3_Label = value; }
        }

        public string Phone3_Text
        {
            get { return phone3_Text; }
            set { phone3_Text = value; }
        }

        public Guid Phone4_Label
        {
            get { return phone4_Label; }
            set { phone4_Label = value; }
        }

        public string Phone4_Text
        {
            get { return phone4_Text; }
            set { phone4_Text = value; }
        }

        public Guid Phone5_Label
        {
            get { return phone5_Label; }
            set { phone5_Label = value; }
        }

        public string Phone5_Text
        {
            get { return phone5_Text; }
            set { phone5_Text = value; }
        }

        public string Notes
        {
            get { return notes; }
            set { notes = value; }
        }

        public DateTime CreatedOn
        {
            get { return createdOn; }
            set { createdOn = value; }
        }

        public Guid CreatedBy
        {
            get { return createdBy; }
            set { createdBy = value; }
        }

        public DateTime ModifiedOn
        {
            get { return modifiedOn; }
            set { modifiedOn = value; }
        }

        public Guid ModifiedBy
        {
            get { return modifiedBy; }
            set { modifiedBy = value; }
        }

        public bool Retired
        {
            get { return retired; }
            set { retired = value; }
        }

        public DateTime RetiredOn
        {
            get { return retiredOn; }
            set { retiredOn = value; }
        }

        public Guid RetiredBy
        {
            get { return retiredBy; }
            set { retiredBy = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;

            SqlHelper.Default.ExecuteNonQuery("spCustomerContact_InsRec", "@CustomerContactId", out returnedValue, parameterValues);

            customerContactId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();

            SqlHelper.Default.ExecuteNonQuery("spCustomerContact_UpdRec", parameterValues);
        }

        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[26];
            prams[0] = GetSqlParameter("@CustomerContactId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.CustomerContactId);
            prams[1] = GetSqlParameter("@CustomerId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.CustomerId);
            prams[2] = GetSqlParameter("@DefaultRec", ParameterDirection.Input, SqlDbType.Bit, 1, this.DefaultRec);
            prams[3] = GetSqlParameter("@SalutationId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.SalutationId);
            prams[4] = GetSqlParameter("@FullName", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.FullName);
            prams[5] = GetSqlParameter("@FirstName", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.FirstName);
            prams[6] = GetSqlParameter("@LastName", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.LastName);
            prams[7] = GetSqlParameter("@JobTitleId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.JobTitleId);
            prams[8] = GetSqlParameter("@Phone1_Label", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.Phone1_Label);
            prams[9] = GetSqlParameter("@Phone1_Text", ParameterDirection.Input, SqlDbType.NVarChar, 32, this.Phone1_Text);
            prams[10] = GetSqlParameter("@Phone2_Label", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.Phone2_Label);
            prams[11] = GetSqlParameter("@Phone2_Text", ParameterDirection.Input, SqlDbType.NVarChar, 32, this.Phone2_Text);
            prams[12] = GetSqlParameter("@Phone3_Label", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.Phone3_Label);
            prams[13] = GetSqlParameter("@Phone3_Text", ParameterDirection.Input, SqlDbType.NVarChar, 32, this.Phone3_Text);
            prams[14] = GetSqlParameter("@Phone4_Label", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.Phone4_Label);
            prams[15] = GetSqlParameter("@Phone4_Text", ParameterDirection.Input, SqlDbType.NVarChar, 32, this.Phone4_Text);
            prams[16] = GetSqlParameter("@Phone5_Label", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.Phone5_Label);
            prams[17] = GetSqlParameter("@Phone5_Text", ParameterDirection.Input, SqlDbType.NVarChar, 32, this.Phone5_Text);
            prams[18] = GetSqlParameter("@Notes", ParameterDirection.Input, SqlDbType.NVarChar, 255, this.Notes);
            prams[19] = GetSqlParameter("@CreatedOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.CreatedOn);
            prams[20] = GetSqlParameter("@CreatedBy", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.CreatedBy);
            prams[21] = GetSqlParameter("@ModifiedOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.ModifiedOn);
            prams[22] = GetSqlParameter("@ModifiedBy", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.ModifiedBy);
            prams[23] = GetSqlParameter("@Retired", ParameterDirection.Input, SqlDbType.Bit, 1, this.Retired);
            prams[24] = GetSqlParameter("@RetiredOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.RetiredOn);
            prams[25] = GetSqlParameter("@RetiredBy", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.RetiredBy);
            return prams;
        }

        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }

        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[]
            {
                GetSqlParameterWithoutDirection("@CustomerContactId", SqlDbType.UniqueIdentifier, 16, this.CustomerContactId),
                GetSqlParameterWithoutDirection("@CustomerId", SqlDbType.UniqueIdentifier, 16, this.CustomerId),
                GetSqlParameterWithoutDirection("@DefaultRec", SqlDbType.Bit, 1, this.DefaultRec),
                GetSqlParameterWithoutDirection("@SalutationId", SqlDbType.UniqueIdentifier, 16, this.SalutationId),
                GetSqlParameterWithoutDirection("@FullName", SqlDbType.NVarChar, 64, this.FullName),
                GetSqlParameterWithoutDirection("@FirstName", SqlDbType.NVarChar, 64, this.FirstName),
                GetSqlParameterWithoutDirection("@LastName", SqlDbType.NVarChar, 64, this.LastName),
                GetSqlParameterWithoutDirection("@JobTitleId", SqlDbType.UniqueIdentifier, 16, this.JobTitleId),
                GetSqlParameterWithoutDirection("@Phone1_Label", SqlDbType.UniqueIdentifier, 16, this.Phone1_Label),
                GetSqlParameterWithoutDirection("@Phone1_Text", SqlDbType.NVarChar, 32, this.Phone1_Text),
                GetSqlParameterWithoutDirection("@Phone2_Label", SqlDbType.UniqueIdentifier, 16, this.Phone2_Label),
                GetSqlParameterWithoutDirection("@Phone2_Text", SqlDbType.NVarChar, 32, this.Phone2_Text),
                GetSqlParameterWithoutDirection("@Phone3_Label", SqlDbType.UniqueIdentifier, 16, this.Phone3_Label),
                GetSqlParameterWithoutDirection("@Phone3_Text", SqlDbType.NVarChar, 32, this.Phone3_Text),
                GetSqlParameterWithoutDirection("@Phone4_Label", SqlDbType.UniqueIdentifier, 16, this.Phone4_Label),
                GetSqlParameterWithoutDirection("@Phone4_Text", SqlDbType.NVarChar, 32, this.Phone4_Text),
                GetSqlParameterWithoutDirection("@Phone5_Label", SqlDbType.UniqueIdentifier, 16, this.Phone5_Label),
                GetSqlParameterWithoutDirection("@Phone5_Text", SqlDbType.NVarChar, 32, this.Phone5_Text),
                GetSqlParameterWithoutDirection("@Notes", SqlDbType.NVarChar, 255, this.Notes),
                GetSqlParameterWithoutDirection("@CreatedOn", SqlDbType.DateTime, 8, this.CreatedOn),
                GetSqlParameterWithoutDirection("@CreatedBy", SqlDbType.UniqueIdentifier, 16, this.CreatedBy),
                GetSqlParameterWithoutDirection("@ModifiedOn", SqlDbType.DateTime, 8, this.ModifiedOn),
                GetSqlParameterWithoutDirection("@ModifiedBy", SqlDbType.UniqueIdentifier, 16, this.ModifiedBy),
                GetSqlParameterWithoutDirection("@Retired", SqlDbType.Bit, 1, this.Retired),
                GetSqlParameterWithoutDirection("@RetiredOn", SqlDbType.DateTime, 8, this.RetiredOn),
                GetSqlParameterWithoutDirection("@RetiredBy", SqlDbType.UniqueIdentifier, 16, this.RetiredBy)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("customerContactId: " + customerContactId.ToString()).Append("\r\n");
            builder.Append("customerId: " + customerId.ToString()).Append("\r\n");
            builder.Append("defaultRec: " + defaultRec.ToString()).Append("\r\n");
            builder.Append("salutationId: " + salutationId.ToString()).Append("\r\n");
            builder.Append("fullName: " + fullName.ToString()).Append("\r\n");
            builder.Append("firstName: " + firstName.ToString()).Append("\r\n");
            builder.Append("lastName: " + lastName.ToString()).Append("\r\n");
            builder.Append("jobTitleId: " + jobTitleId.ToString()).Append("\r\n");
            builder.Append("phone1_Label: " + phone1_Label.ToString()).Append("\r\n");
            builder.Append("phone1_Text: " + phone1_Text.ToString()).Append("\r\n");
            builder.Append("phone2_Label: " + phone2_Label.ToString()).Append("\r\n");
            builder.Append("phone2_Text: " + phone2_Text.ToString()).Append("\r\n");
            builder.Append("phone3_Label: " + phone3_Label.ToString()).Append("\r\n");
            builder.Append("phone3_Text: " + phone3_Text.ToString()).Append("\r\n");
            builder.Append("phone4_Label: " + phone4_Label.ToString()).Append("\r\n");
            builder.Append("phone4_Text: " + phone4_Text.ToString()).Append("\r\n");
            builder.Append("phone5_Label: " + phone5_Label.ToString()).Append("\r\n");
            builder.Append("phone5_Text: " + phone5_Text.ToString()).Append("\r\n");
            builder.Append("notes: " + notes.ToString()).Append("\r\n");
            builder.Append("createdOn: " + createdOn.ToString()).Append("\r\n");
            builder.Append("createdBy: " + createdBy.ToString()).Append("\r\n");
            builder.Append("modifiedOn: " + modifiedOn.ToString()).Append("\r\n");
            builder.Append("modifiedBy: " + modifiedBy.ToString()).Append("\r\n");
            builder.Append("retired: " + retired.ToString()).Append("\r\n");
            builder.Append("retiredOn: " + retiredOn.ToString()).Append("\r\n");
            builder.Append("retiredBy: " + retiredBy.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }

        #region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            string[] textField = { TextField };
            LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            if (SwitchLocale)
            {
                TextField = GetSwitchLocale(TextField);
            }
            ddList.Items.Clear();

            CustomerContactCollection source;

            if (OrderBy == null || OrderBy.Length == 0)
            {
                OrderBy = TextField;
            }
            // Filter the retired records
            if (WhereClause.Length > 0)
            {
                WhereClause += " AND Retired = 0";
            }
            else
            {
                WhereClause = "Retired = 0";
            }

            if (WhereClause.Length > 0)
            {
                source = CustomerContact.LoadCollection(WhereClause, OrderBy, true);
            }
            else
            {
                source = CustomerContact.LoadCollection(OrderBy, true);
            }

            Common.ComboList sourceList = new Common.ComboList();

            if (BlankLine)
            {
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
            }

            foreach (CustomerContact item in source)
            {
                bool filter = false;
                if (ParentFilter.Trim() != String.Empty)
                {
                    filter = true;
                    if (item.CustomerId != Guid.Empty)
                    {
                        filter = IgnorThis(item, ParentFilter);
                    }
                }
                if (!(filter))
                {
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.CustomerContactId));
                }
            }

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";

            if (ddList.Items.Count > 0)
            {
                ddList.SelectedIndex = 0;
            }
        }

        #endregion


        private static bool IgnorThis(CustomerContact target, string parentFilter)
        {
            bool result = true;
            parentFilter = parentFilter.Replace(" ", "");       // remove spaces
            parentFilter = parentFilter.Replace("'", "");       // remove '
            string[] parsed = parentFilter.Split('=');          // parse

            if (target.CustomerId == Guid.Empty)
            {
                PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
                string filterField = (string)pi.GetValue(target, null);
                if (filterField.ToLower() == parsed[1].ToLower())
                {
                    result = false;
                }
            }
            else
            {
                CustomerContact parentTemplate = CustomerContact.Load(target.CustomerId);
                result = IgnorThis(parentTemplate, parentFilter);
            }
            return result;
        }

        private static string GetFormatedText(CustomerContact target, string[] textField, string textFormatString)
        {
            for (int i = 0; i < textField.Length; i++)
            {
                PropertyInfo pi = target.GetType().GetProperty(textField[i]);
                textFormatString = textFormatString.Replace("{" + i.ToString() + "}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
            }
            return textFormatString;
        }

        private static string[] GetSwitchLocale(string[] source)
        {
            switch (Common.Config.CurrentLanguageId)
            {
                case 2:
                    source[source.Length - 1] += "_Chs";
                    break;
                case 3:
                    source[source.Length - 1] += "_Cht";
                    break;
            }
            return source;
        }
    }


    /// <summary>
    /// Represents a collection of <see cref="CustomerContact">CustomerContact</see> objects.
    /// </summary>
    public class CustomerContactCollection : BindingList<CustomerContact>
    {
    }
}
