using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace xPort5.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.OrderPL.
    /// Date Created:   2020-03-02 02:19:18
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class OrderPL
    {
        private Guid key = Guid.Empty;
        private Guid orderPLId = Guid.Empty;
        private string pLNumber = String.Empty;
        private DateTime pLDate = DateTime.Parse("1900-1-1");
        private Guid customerId = Guid.Empty;
        private Guid staffId = Guid.Empty;
        private string sendFrom = String.Empty;
        private string sendTo = String.Empty;
        private decimal totalQty;
        private decimal totalQtyIN;
        private decimal totalQtyOUT;
        private decimal totalAmount;
        private string remarks = String.Empty;
        private int revision = 0;
        private bool inUse;
        private int status = 0;
        private DateTime createdOn = DateTime.Parse("1900-1-1");
        private Guid createdBy = Guid.Empty;
        private DateTime modifiedOn = DateTime.Parse("1900-1-1");
        private Guid modifiedBy = Guid.Empty;
        private DateTime accessedOn = DateTime.Parse("1900-1-1");
        private Guid accessedBy = Guid.Empty;
        private bool retired;
        private DateTime retiredOn = DateTime.Parse("1900-1-1");
        private Guid retiredBy = Guid.Empty;

        /// <summary>
        /// Initialize an new empty OrderPL object.
        /// </summary>
        public OrderPL()
        {
        }

        /// <summary>
        /// Initialize a new OrderPL object with the given parameters.
        /// </summary>
        public OrderPL(Guid orderPLId, string pLNumber, DateTime pLDate, Guid customerId, Guid staffId, string sendFrom, string sendTo, decimal totalQty, decimal totalQtyIN, decimal totalQtyOUT, decimal totalAmount, string remarks, int revision, bool inUse, int status, DateTime createdOn, Guid createdBy, DateTime modifiedOn, Guid modifiedBy, DateTime accessedOn, Guid accessedBy, bool retired, DateTime retiredOn, Guid retiredBy)
        {
            this.orderPLId = orderPLId;
            this.pLNumber = pLNumber;
            this.pLDate = pLDate;
            this.customerId = customerId;
            this.staffId = staffId;
            this.sendFrom = sendFrom;
            this.sendTo = sendTo;
            this.totalQty = totalQty;
            this.totalQtyIN = totalQtyIN;
            this.totalQtyOUT = totalQtyOUT;
            this.totalAmount = totalAmount;
            this.remarks = remarks;
            this.revision = revision;
            this.inUse = inUse;
            this.status = status;
            this.createdOn = createdOn;
            this.createdBy = createdBy;
            this.modifiedOn = modifiedOn;
            this.modifiedBy = modifiedBy;
            this.accessedOn = accessedOn;
            this.accessedBy = accessedBy;
            this.retired = retired;
            this.retiredOn = retiredOn;
            this.retiredBy = retiredBy;
        }

        /// <summary>
        /// Loads a OrderPL object from the database using the given OrderPLId
        /// </summary>
        /// <param name="orderPLId">The primary key value</param>
        /// <returns>A OrderPL object</returns>
        public static OrderPL Load(Guid orderPLId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@OrderPLId", orderPLId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spOrderPL_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    OrderPL result = new OrderPL();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a OrderPL object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A OrderPL object</returns>
        public static OrderPL LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spOrderPL_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    OrderPL result = new OrderPL();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a collection of OrderPL objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the OrderPL objects in the database.</returns>
        public static OrderPLCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] { };
            return LoadCollection("spOrderPL_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderPL objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the OrderPL objects in the database ordered by the columns specified.</returns>
        public static OrderPLCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spOrderPL_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderPL objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the OrderPL objects in the database.</returns>
        public static OrderPLCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spOrderPL_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderPL objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the OrderPL objects in the database ordered by the columns specified.</returns>
        public static OrderPLCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spOrderPL_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderPL objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the OrderPL objects in the database.</returns>
        public static OrderPLCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            OrderPLCollection result = new OrderPLCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    OrderPL tmp = new OrderPL();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a OrderPL object from the database.
        /// </summary>
        /// <param name="orderPLId">The primary key value</param>
        public static void Delete(Guid orderPLId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@OrderPLId", orderPLId) };
            SqlHelper.Default.ExecuteNonQuery("spOrderPL_DelRec", parameterValues);
        }


        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) orderPLId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) pLNumber = reader.GetString(1);
                if (!reader.IsDBNull(2)) pLDate = reader.GetDateTime(2);
                if (!reader.IsDBNull(3)) customerId = reader.GetGuid(3);
                if (!reader.IsDBNull(4)) staffId = reader.GetGuid(4);
                if (!reader.IsDBNull(5)) sendFrom = reader.GetString(5);
                if (!reader.IsDBNull(6)) sendTo = reader.GetString(6);
                if (!reader.IsDBNull(7)) totalQty = reader.GetDecimal(7);
                if (!reader.IsDBNull(8)) totalQtyIN = reader.GetDecimal(8);
                if (!reader.IsDBNull(9)) totalQtyOUT = reader.GetDecimal(9);
                if (!reader.IsDBNull(10)) totalAmount = reader.GetDecimal(10);
                if (!reader.IsDBNull(11)) remarks = reader.GetString(11);
                if (!reader.IsDBNull(12)) revision = reader.GetInt32(12);
                if (!reader.IsDBNull(13)) inUse = reader.GetBoolean(13);
                if (!reader.IsDBNull(14)) status = reader.GetInt32(14);
                if (!reader.IsDBNull(15)) createdOn = reader.GetDateTime(15);
                if (!reader.IsDBNull(16)) createdBy = reader.GetGuid(16);
                if (!reader.IsDBNull(17)) modifiedOn = reader.GetDateTime(17);
                if (!reader.IsDBNull(18)) modifiedBy = reader.GetGuid(18);
                if (!reader.IsDBNull(19)) accessedOn = reader.GetDateTime(19);
                if (!reader.IsDBNull(20)) accessedBy = reader.GetGuid(20);
                if (!reader.IsDBNull(21)) retired = reader.GetBoolean(21);
                if (!reader.IsDBNull(22)) retiredOn = reader.GetDateTime(22);
                if (!reader.IsDBNull(23)) retiredBy = reader.GetGuid(23);
            }
        }

        public void Delete()
        {
            Delete(this.OrderPLId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != OrderPLId)
                    this.Delete();
                Update();
            }
        }

        public Guid OrderPLId
        {
            get { return orderPLId; }
            set { orderPLId = value; }
        }

        public string PLNumber
        {
            get { return pLNumber; }
            set { pLNumber = value; }
        }

        public DateTime PLDate
        {
            get { return pLDate; }
            set { pLDate = value; }
        }

        public Guid CustomerId
        {
            get { return customerId; }
            set { customerId = value; }
        }

        public Guid StaffId
        {
            get { return staffId; }
            set { staffId = value; }
        }

        public string SendFrom
        {
            get { return sendFrom; }
            set { sendFrom = value; }
        }

        public string SendTo
        {
            get { return sendTo; }
            set { sendTo = value; }
        }

        public decimal TotalQty
        {
            get { return totalQty; }
            set { totalQty = value; }
        }

        public decimal TotalQtyIN
        {
            get { return totalQtyIN; }
            set { totalQtyIN = value; }
        }

        public decimal TotalQtyOUT
        {
            get { return totalQtyOUT; }
            set { totalQtyOUT = value; }
        }

        public decimal TotalAmount
        {
            get { return totalAmount; }
            set { totalAmount = value; }
        }

        public string Remarks
        {
            get { return remarks; }
            set { remarks = value; }
        }

        public int Revision
        {
            get { return revision; }
            set { revision = value; }
        }

        public bool InUse
        {
            get { return inUse; }
            set { inUse = value; }
        }

        public int Status
        {
            get { return status; }
            set { status = value; }
        }

        public DateTime CreatedOn
        {
            get { return createdOn; }
            set { createdOn = value; }
        }

        public Guid CreatedBy
        {
            get { return createdBy; }
            set { createdBy = value; }
        }

        public DateTime ModifiedOn
        {
            get { return modifiedOn; }
            set { modifiedOn = value; }
        }

        public Guid ModifiedBy
        {
            get { return modifiedBy; }
            set { modifiedBy = value; }
        }

        public DateTime AccessedOn
        {
            get { return accessedOn; }
            set { accessedOn = value; }
        }

        public Guid AccessedBy
        {
            get { return accessedBy; }
            set { accessedBy = value; }
        }

        public bool Retired
        {
            get { return retired; }
            set { retired = value; }
        }

        public DateTime RetiredOn
        {
            get { return retiredOn; }
            set { retiredOn = value; }
        }

        public Guid RetiredBy
        {
            get { return retiredBy; }
            set { retiredBy = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;

            SqlHelper.Default.ExecuteNonQuery("spOrderPL_InsRec", "@OrderPLId", out returnedValue, parameterValues);

            orderPLId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();

            SqlHelper.Default.ExecuteNonQuery("spOrderPL_UpdRec", parameterValues);
        }

        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[24];
            prams[0] = GetSqlParameter("@OrderPLId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.OrderPLId);
            prams[1] = GetSqlParameter("@PLNumber", ParameterDirection.Input, SqlDbType.VarChar, 10, this.PLNumber);
            prams[2] = GetSqlParameter("@PLDate", ParameterDirection.Input, SqlDbType.DateTime, 8, this.PLDate);
            prams[3] = GetSqlParameter("@CustomerId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.CustomerId);
            prams[4] = GetSqlParameter("@StaffId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.StaffId);
            prams[5] = GetSqlParameter("@SendFrom", ParameterDirection.Input, SqlDbType.NVarChar, 16, this.SendFrom);
            prams[6] = GetSqlParameter("@SendTo", ParameterDirection.Input, SqlDbType.NVarChar, 16, this.SendTo);
            prams[7] = GetSqlParameter("@TotalQty", ParameterDirection.Input, SqlDbType.Decimal, 9, this.TotalQty);
            prams[8] = GetSqlParameter("@TotalQtyIN", ParameterDirection.Input, SqlDbType.Decimal, 9, this.TotalQtyIN);
            prams[9] = GetSqlParameter("@TotalQtyOUT", ParameterDirection.Input, SqlDbType.Decimal, 9, this.TotalQtyOUT);
            prams[10] = GetSqlParameter("@TotalAmount", ParameterDirection.Input, SqlDbType.Money, 8, this.TotalAmount);
            prams[11] = GetSqlParameter("@Remarks", ParameterDirection.Input, SqlDbType.NVarChar, 255, this.Remarks);
            prams[12] = GetSqlParameter("@Revision", ParameterDirection.Input, SqlDbType.Int, 4, this.Revision);
            prams[13] = GetSqlParameter("@InUse", ParameterDirection.Input, SqlDbType.Bit, 1, this.InUse);
            prams[14] = GetSqlParameter("@Status", ParameterDirection.Input, SqlDbType.Int, 4, this.Status);
            prams[15] = GetSqlParameter("@CreatedOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.CreatedOn);
            prams[16] = GetSqlParameter("@CreatedBy", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.CreatedBy);
            prams[17] = GetSqlParameter("@ModifiedOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.ModifiedOn);
            prams[18] = GetSqlParameter("@ModifiedBy", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.ModifiedBy);
            prams[19] = GetSqlParameter("@AccessedOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.AccessedOn);
            prams[20] = GetSqlParameter("@AccessedBy", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.AccessedBy);
            prams[21] = GetSqlParameter("@Retired", ParameterDirection.Input, SqlDbType.Bit, 1, this.Retired);
            prams[22] = GetSqlParameter("@RetiredOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.RetiredOn);
            prams[23] = GetSqlParameter("@RetiredBy", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.RetiredBy);
            return prams;
        }

        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }

        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[]
            {
                GetSqlParameterWithoutDirection("@OrderPLId", SqlDbType.UniqueIdentifier, 16, this.OrderPLId),
                GetSqlParameterWithoutDirection("@PLNumber", SqlDbType.VarChar, 10, this.PLNumber),
                GetSqlParameterWithoutDirection("@PLDate", SqlDbType.DateTime, 8, this.PLDate),
                GetSqlParameterWithoutDirection("@CustomerId", SqlDbType.UniqueIdentifier, 16, this.CustomerId),
                GetSqlParameterWithoutDirection("@StaffId", SqlDbType.UniqueIdentifier, 16, this.StaffId),
                GetSqlParameterWithoutDirection("@SendFrom", SqlDbType.NVarChar, 16, this.SendFrom),
                GetSqlParameterWithoutDirection("@SendTo", SqlDbType.NVarChar, 16, this.SendTo),
                GetSqlParameterWithoutDirection("@TotalQty", SqlDbType.Decimal, 9, this.TotalQty),
                GetSqlParameterWithoutDirection("@TotalQtyIN", SqlDbType.Decimal, 9, this.TotalQtyIN),
                GetSqlParameterWithoutDirection("@TotalQtyOUT", SqlDbType.Decimal, 9, this.TotalQtyOUT),
                GetSqlParameterWithoutDirection("@TotalAmount", SqlDbType.Money, 8, this.TotalAmount),
                GetSqlParameterWithoutDirection("@Remarks", SqlDbType.NVarChar, 255, this.Remarks),
                GetSqlParameterWithoutDirection("@Revision", SqlDbType.Int, 4, this.Revision),
                GetSqlParameterWithoutDirection("@InUse", SqlDbType.Bit, 1, this.InUse),
                GetSqlParameterWithoutDirection("@Status", SqlDbType.Int, 4, this.Status),
                GetSqlParameterWithoutDirection("@CreatedOn", SqlDbType.DateTime, 8, this.CreatedOn),
                GetSqlParameterWithoutDirection("@CreatedBy", SqlDbType.UniqueIdentifier, 16, this.CreatedBy),
                GetSqlParameterWithoutDirection("@ModifiedOn", SqlDbType.DateTime, 8, this.ModifiedOn),
                GetSqlParameterWithoutDirection("@ModifiedBy", SqlDbType.UniqueIdentifier, 16, this.ModifiedBy),
                GetSqlParameterWithoutDirection("@AccessedOn", SqlDbType.DateTime, 8, this.AccessedOn),
                GetSqlParameterWithoutDirection("@AccessedBy", SqlDbType.UniqueIdentifier, 16, this.AccessedBy),
                GetSqlParameterWithoutDirection("@Retired", SqlDbType.Bit, 1, this.Retired),
                GetSqlParameterWithoutDirection("@RetiredOn", SqlDbType.DateTime, 8, this.RetiredOn),
                GetSqlParameterWithoutDirection("@RetiredBy", SqlDbType.UniqueIdentifier, 16, this.RetiredBy)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("orderPLId: " + orderPLId.ToString()).Append("\r\n");
            builder.Append("pLNumber: " + pLNumber.ToString()).Append("\r\n");
            builder.Append("pLDate: " + pLDate.ToString()).Append("\r\n");
            builder.Append("customerId: " + customerId.ToString()).Append("\r\n");
            builder.Append("staffId: " + staffId.ToString()).Append("\r\n");
            builder.Append("sendFrom: " + sendFrom.ToString()).Append("\r\n");
            builder.Append("sendTo: " + sendTo.ToString()).Append("\r\n");
            builder.Append("totalQty: " + totalQty.ToString()).Append("\r\n");
            builder.Append("totalQtyIN: " + totalQtyIN.ToString()).Append("\r\n");
            builder.Append("totalQtyOUT: " + totalQtyOUT.ToString()).Append("\r\n");
            builder.Append("totalAmount: " + totalAmount.ToString()).Append("\r\n");
            builder.Append("remarks: " + remarks.ToString()).Append("\r\n");
            builder.Append("revision: " + revision.ToString()).Append("\r\n");
            builder.Append("inUse: " + inUse.ToString()).Append("\r\n");
            builder.Append("status: " + status.ToString()).Append("\r\n");
            builder.Append("createdOn: " + createdOn.ToString()).Append("\r\n");
            builder.Append("createdBy: " + createdBy.ToString()).Append("\r\n");
            builder.Append("modifiedOn: " + modifiedOn.ToString()).Append("\r\n");
            builder.Append("modifiedBy: " + modifiedBy.ToString()).Append("\r\n");
            builder.Append("accessedOn: " + accessedOn.ToString()).Append("\r\n");
            builder.Append("accessedBy: " + accessedBy.ToString()).Append("\r\n");
            builder.Append("retired: " + retired.ToString()).Append("\r\n");
            builder.Append("retiredOn: " + retiredOn.ToString()).Append("\r\n");
            builder.Append("retiredBy: " + retiredBy.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }

        #region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            string[] textField = { TextField };
            LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            if (SwitchLocale)
            {
                TextField = GetSwitchLocale(TextField);
            }
            ddList.Items.Clear();

            OrderPLCollection source;

            if (OrderBy == null || OrderBy.Length == 0)
            {
                OrderBy = TextField;
            }
            // Filter the retired records
            if (WhereClause.Length > 0)
            {
                WhereClause += " AND Retired = 0";
            }
            else
            {
                WhereClause = "Retired = 0";
            }

            if (WhereClause.Length > 0)
            {
                source = OrderPL.LoadCollection(WhereClause, OrderBy, true);
            }
            else
            {
                source = OrderPL.LoadCollection(OrderBy, true);
            }

            Common.ComboList sourceList = new Common.ComboList();

            if (BlankLine)
            {
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
            }

            foreach (OrderPL item in source)
            {
                bool filter = false;
                if (ParentFilter.Trim() != String.Empty)
                {
                    filter = true;
                    if (item.CustomerId != Guid.Empty)
                    {
                        filter = IgnorThis(item, ParentFilter);
                    }
                }
                if (!(filter))
                {
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.OrderPLId));
                }
            }

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";

            if (ddList.Items.Count > 0)
            {
                ddList.SelectedIndex = 0;
            }
        }

        #endregion


        private static bool IgnorThis(OrderPL target, string parentFilter)
        {
            bool result = true;
            parentFilter = parentFilter.Replace(" ", "");       // remove spaces
            parentFilter = parentFilter.Replace("'", "");       // remove '
            string[] parsed = parentFilter.Split('=');          // parse

            if (target.CustomerId == Guid.Empty)
            {
                PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
                string filterField = (string)pi.GetValue(target, null);
                if (filterField.ToLower() == parsed[1].ToLower())
                {
                    result = false;
                }
            }
            else
            {
                OrderPL parentTemplate = OrderPL.Load(target.CustomerId);
                result = IgnorThis(parentTemplate, parentFilter);
            }
            return result;
        }

        private static string GetFormatedText(OrderPL target, string[] textField, string textFormatString)
        {
            for (int i = 0; i < textField.Length; i++)
            {
                PropertyInfo pi = target.GetType().GetProperty(textField[i]);
                textFormatString = textFormatString.Replace("{" + i.ToString() + "}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
            }
            return textFormatString;
        }

        private static string[] GetSwitchLocale(string[] source)
        {
            switch (Common.Config.CurrentLanguageId)
            {
                case 2:
                    source[source.Length - 1] += "_Chs";
                    break;
                case 3:
                    source[source.Length - 1] += "_Cht";
                    break;
            }
            return source;
        }
    }


    /// <summary>
    /// Represents a collection of <see cref="OrderPL">OrderPL</see> objects.
    /// </summary>
    public class OrderPLCollection : BindingList<OrderPL>
    {
    }
}
