using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace xPort5.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.OrderQTItems.
    /// Date Created:   2020-03-02 02:20:53
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class OrderQTItems
    {
        private Guid key = Guid.Empty;
        private Guid orderQTItemId = Guid.Empty;
        private Guid orderQTId = Guid.Empty;
        private int lineNumber = 0;
        private Guid articleId = Guid.Empty;
        private Guid packageId = Guid.Empty;
        private Guid supplierId = Guid.Empty;
        private string particular = String.Empty;
        private string custRef = String.Empty;
        private int priceType = 0;
        private decimal factoryCost;
        private decimal margin;
        private decimal fCL;
        private decimal lCL;
        private decimal sampleQty;
        private decimal qty;
        private string unit = String.Empty;
        private decimal amount;
        private int carton = 0;
        private string gLAccount = String.Empty;
        private string refDocNo = String.Empty;
        private string shippingMark = String.Empty;
        private decimal qtyIN;
        private decimal qtyOUT;

        /// <summary>
        /// Initialize an new empty OrderQTItems object.
        /// </summary>
        public OrderQTItems()
        {
        }

        /// <summary>
        /// Initialize a new OrderQTItems object with the given parameters.
        /// </summary>
        public OrderQTItems(Guid orderQTItemId, Guid orderQTId, int lineNumber, Guid articleId, Guid packageId, Guid supplierId, string particular, string custRef, int priceType, decimal factoryCost, decimal margin, decimal fCL, decimal lCL, decimal sampleQty, decimal qty, string unit, decimal amount, int carton, string gLAccount, string refDocNo, string shippingMark, decimal qtyIN, decimal qtyOUT)
        {
            this.orderQTItemId = orderQTItemId;
            this.orderQTId = orderQTId;
            this.lineNumber = lineNumber;
            this.articleId = articleId;
            this.packageId = packageId;
            this.supplierId = supplierId;
            this.particular = particular;
            this.custRef = custRef;
            this.priceType = priceType;
            this.factoryCost = factoryCost;
            this.margin = margin;
            this.fCL = fCL;
            this.lCL = lCL;
            this.sampleQty = sampleQty;
            this.qty = qty;
            this.unit = unit;
            this.amount = amount;
            this.carton = carton;
            this.gLAccount = gLAccount;
            this.refDocNo = refDocNo;
            this.shippingMark = shippingMark;
            this.qtyIN = qtyIN;
            this.qtyOUT = qtyOUT;
        }

        /// <summary>
        /// Loads a OrderQTItems object from the database using the given OrderQTItemId
        /// </summary>
        /// <param name="orderQTItemId">The primary key value</param>
        /// <returns>A OrderQTItems object</returns>
        public static OrderQTItems Load(Guid orderQTItemId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@OrderQTItemId", orderQTItemId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spOrderQTItems_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    OrderQTItems result = new OrderQTItems();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a OrderQTItems object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A OrderQTItems object</returns>
        public static OrderQTItems LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spOrderQTItems_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    OrderQTItems result = new OrderQTItems();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a collection of OrderQTItems objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the OrderQTItems objects in the database.</returns>
        public static OrderQTItemsCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] { };
            return LoadCollection("spOrderQTItems_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderQTItems objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the OrderQTItems objects in the database ordered by the columns specified.</returns>
        public static OrderQTItemsCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spOrderQTItems_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderQTItems objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the OrderQTItems objects in the database.</returns>
        public static OrderQTItemsCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spOrderQTItems_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderQTItems objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the OrderQTItems objects in the database ordered by the columns specified.</returns>
        public static OrderQTItemsCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spOrderQTItems_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderQTItems objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the OrderQTItems objects in the database.</returns>
        public static OrderQTItemsCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            OrderQTItemsCollection result = new OrderQTItemsCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    OrderQTItems tmp = new OrderQTItems();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a OrderQTItems object from the database.
        /// </summary>
        /// <param name="orderQTItemId">The primary key value</param>
        public static void Delete(Guid orderQTItemId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@OrderQTItemId", orderQTItemId) };
            SqlHelper.Default.ExecuteNonQuery("spOrderQTItems_DelRec", parameterValues);
        }


        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) orderQTItemId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) orderQTId = reader.GetGuid(1);
                if (!reader.IsDBNull(2)) lineNumber = reader.GetInt32(2);
                if (!reader.IsDBNull(3)) articleId = reader.GetGuid(3);
                if (!reader.IsDBNull(4)) packageId = reader.GetGuid(4);
                if (!reader.IsDBNull(5)) supplierId = reader.GetGuid(5);
                if (!reader.IsDBNull(6)) particular = reader.GetString(6);
                if (!reader.IsDBNull(7)) custRef = reader.GetString(7);
                if (!reader.IsDBNull(8)) priceType = reader.GetInt32(8);
                if (!reader.IsDBNull(9)) factoryCost = reader.GetDecimal(9);
                if (!reader.IsDBNull(10)) margin = reader.GetDecimal(10);
                if (!reader.IsDBNull(11)) fCL = reader.GetDecimal(11);
                if (!reader.IsDBNull(12)) lCL = reader.GetDecimal(12);
                if (!reader.IsDBNull(13)) sampleQty = reader.GetDecimal(13);
                if (!reader.IsDBNull(14)) qty = reader.GetDecimal(14);
                if (!reader.IsDBNull(15)) unit = reader.GetString(15);
                if (!reader.IsDBNull(16)) amount = reader.GetDecimal(16);
                if (!reader.IsDBNull(17)) carton = reader.GetInt32(17);
                if (!reader.IsDBNull(18)) gLAccount = reader.GetString(18);
                if (!reader.IsDBNull(19)) refDocNo = reader.GetString(19);
                if (!reader.IsDBNull(20)) shippingMark = reader.GetString(20);
                if (!reader.IsDBNull(21)) qtyIN = reader.GetDecimal(21);
                if (!reader.IsDBNull(22)) qtyOUT = reader.GetDecimal(22);
            }
        }

        public void Delete()
        {
            Delete(this.OrderQTItemId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != OrderQTItemId)
                    this.Delete();
                Update();
            }
        }

        public Guid OrderQTItemId
        {
            get { return orderQTItemId; }
            set { orderQTItemId = value; }
        }

        public Guid OrderQTId
        {
            get { return orderQTId; }
            set { orderQTId = value; }
        }

        public int LineNumber
        {
            get { return lineNumber; }
            set { lineNumber = value; }
        }

        public Guid ArticleId
        {
            get { return articleId; }
            set { articleId = value; }
        }

        public Guid PackageId
        {
            get { return packageId; }
            set { packageId = value; }
        }

        public Guid SupplierId
        {
            get { return supplierId; }
            set { supplierId = value; }
        }

        public string Particular
        {
            get { return particular; }
            set { particular = value; }
        }

        public string CustRef
        {
            get { return custRef; }
            set { custRef = value; }
        }

        public int PriceType
        {
            get { return priceType; }
            set { priceType = value; }
        }

        public decimal FactoryCost
        {
            get { return factoryCost; }
            set { factoryCost = value; }
        }

        public decimal Margin
        {
            get { return margin; }
            set { margin = value; }
        }

        public decimal FCL
        {
            get { return fCL; }
            set { fCL = value; }
        }

        public decimal LCL
        {
            get { return lCL; }
            set { lCL = value; }
        }

        public decimal SampleQty
        {
            get { return sampleQty; }
            set { sampleQty = value; }
        }

        public decimal Qty
        {
            get { return qty; }
            set { qty = value; }
        }

        public string Unit
        {
            get { return unit; }
            set { unit = value; }
        }

        public decimal Amount
        {
            get { return amount; }
            set { amount = value; }
        }

        public int Carton
        {
            get { return carton; }
            set { carton = value; }
        }

        public string GLAccount
        {
            get { return gLAccount; }
            set { gLAccount = value; }
        }

        public string RefDocNo
        {
            get { return refDocNo; }
            set { refDocNo = value; }
        }

        public string ShippingMark
        {
            get { return shippingMark; }
            set { shippingMark = value; }
        }

        public decimal QtyIN
        {
            get { return qtyIN; }
            set { qtyIN = value; }
        }

        public decimal QtyOUT
        {
            get { return qtyOUT; }
            set { qtyOUT = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;

            SqlHelper.Default.ExecuteNonQuery("spOrderQTItems_InsRec", "@OrderQTItemId", out returnedValue, parameterValues);

            orderQTItemId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();

            SqlHelper.Default.ExecuteNonQuery("spOrderQTItems_UpdRec", parameterValues);
        }

        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[23];
            prams[0] = GetSqlParameter("@OrderQTItemId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.OrderQTItemId);
            prams[1] = GetSqlParameter("@OrderQTId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.OrderQTId);
            prams[2] = GetSqlParameter("@LineNumber", ParameterDirection.Input, SqlDbType.Int, 4, this.LineNumber);
            prams[3] = GetSqlParameter("@ArticleId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.ArticleId);
            prams[4] = GetSqlParameter("@PackageId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.PackageId);
            prams[5] = GetSqlParameter("@SupplierId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.SupplierId);
            prams[6] = GetSqlParameter("@Particular", ParameterDirection.Input, SqlDbType.NVarChar, 128, this.Particular);
            prams[7] = GetSqlParameter("@CustRef", ParameterDirection.Input, SqlDbType.NVarChar, 16, this.CustRef);
            prams[8] = GetSqlParameter("@PriceType", ParameterDirection.Input, SqlDbType.Int, 4, this.PriceType);
            prams[9] = GetSqlParameter("@FactoryCost", ParameterDirection.Input, SqlDbType.Decimal, 9, this.FactoryCost);
            prams[10] = GetSqlParameter("@Margin", ParameterDirection.Input, SqlDbType.Decimal, 9, this.Margin);
            prams[11] = GetSqlParameter("@FCL", ParameterDirection.Input, SqlDbType.Decimal, 9, this.FCL);
            prams[12] = GetSqlParameter("@LCL", ParameterDirection.Input, SqlDbType.Decimal, 9, this.LCL);
            prams[13] = GetSqlParameter("@SampleQty", ParameterDirection.Input, SqlDbType.Decimal, 9, this.SampleQty);
            prams[14] = GetSqlParameter("@Qty", ParameterDirection.Input, SqlDbType.Decimal, 9, this.Qty);
            prams[15] = GetSqlParameter("@Unit", ParameterDirection.Input, SqlDbType.VarChar, 6, this.Unit);
            prams[16] = GetSqlParameter("@Amount", ParameterDirection.Input, SqlDbType.Money, 8, this.Amount);
            prams[17] = GetSqlParameter("@Carton", ParameterDirection.Input, SqlDbType.Int, 4, this.Carton);
            prams[18] = GetSqlParameter("@GLAccount", ParameterDirection.Input, SqlDbType.NVarChar, 16, this.GLAccount);
            prams[19] = GetSqlParameter("@RefDocNo", ParameterDirection.Input, SqlDbType.NVarChar, 10, this.RefDocNo);
            prams[20] = GetSqlParameter("@ShippingMark", ParameterDirection.Input, SqlDbType.NVarChar, 255, this.ShippingMark);
            prams[21] = GetSqlParameter("@QtyIN", ParameterDirection.Input, SqlDbType.Decimal, 9, this.QtyIN);
            prams[22] = GetSqlParameter("@QtyOUT", ParameterDirection.Input, SqlDbType.Decimal, 9, this.QtyOUT);
            return prams;
        }

        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }

        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[]
            {
                GetSqlParameterWithoutDirection("@OrderQTItemId", SqlDbType.UniqueIdentifier, 16, this.OrderQTItemId),
                GetSqlParameterWithoutDirection("@OrderQTId", SqlDbType.UniqueIdentifier, 16, this.OrderQTId),
                GetSqlParameterWithoutDirection("@LineNumber", SqlDbType.Int, 4, this.LineNumber),
                GetSqlParameterWithoutDirection("@ArticleId", SqlDbType.UniqueIdentifier, 16, this.ArticleId),
                GetSqlParameterWithoutDirection("@PackageId", SqlDbType.UniqueIdentifier, 16, this.PackageId),
                GetSqlParameterWithoutDirection("@SupplierId", SqlDbType.UniqueIdentifier, 16, this.SupplierId),
                GetSqlParameterWithoutDirection("@Particular", SqlDbType.NVarChar, 128, this.Particular),
                GetSqlParameterWithoutDirection("@CustRef", SqlDbType.NVarChar, 16, this.CustRef),
                GetSqlParameterWithoutDirection("@PriceType", SqlDbType.Int, 4, this.PriceType),
                GetSqlParameterWithoutDirection("@FactoryCost", SqlDbType.Decimal, 9, this.FactoryCost),
                GetSqlParameterWithoutDirection("@Margin", SqlDbType.Decimal, 9, this.Margin),
                GetSqlParameterWithoutDirection("@FCL", SqlDbType.Decimal, 9, this.FCL),
                GetSqlParameterWithoutDirection("@LCL", SqlDbType.Decimal, 9, this.LCL),
                GetSqlParameterWithoutDirection("@SampleQty", SqlDbType.Decimal, 9, this.SampleQty),
                GetSqlParameterWithoutDirection("@Qty", SqlDbType.Decimal, 9, this.Qty),
                GetSqlParameterWithoutDirection("@Unit", SqlDbType.VarChar, 6, this.Unit),
                GetSqlParameterWithoutDirection("@Amount", SqlDbType.Money, 8, this.Amount),
                GetSqlParameterWithoutDirection("@Carton", SqlDbType.Int, 4, this.Carton),
                GetSqlParameterWithoutDirection("@GLAccount", SqlDbType.NVarChar, 16, this.GLAccount),
                GetSqlParameterWithoutDirection("@RefDocNo", SqlDbType.NVarChar, 10, this.RefDocNo),
                GetSqlParameterWithoutDirection("@ShippingMark", SqlDbType.NVarChar, 255, this.ShippingMark),
                GetSqlParameterWithoutDirection("@QtyIN", SqlDbType.Decimal, 9, this.QtyIN),
                GetSqlParameterWithoutDirection("@QtyOUT", SqlDbType.Decimal, 9, this.QtyOUT)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("orderQTItemId: " + orderQTItemId.ToString()).Append("\r\n");
            builder.Append("orderQTId: " + orderQTId.ToString()).Append("\r\n");
            builder.Append("lineNumber: " + lineNumber.ToString()).Append("\r\n");
            builder.Append("articleId: " + articleId.ToString()).Append("\r\n");
            builder.Append("packageId: " + packageId.ToString()).Append("\r\n");
            builder.Append("supplierId: " + supplierId.ToString()).Append("\r\n");
            builder.Append("particular: " + particular.ToString()).Append("\r\n");
            builder.Append("custRef: " + custRef.ToString()).Append("\r\n");
            builder.Append("priceType: " + priceType.ToString()).Append("\r\n");
            builder.Append("factoryCost: " + factoryCost.ToString()).Append("\r\n");
            builder.Append("margin: " + margin.ToString()).Append("\r\n");
            builder.Append("fCL: " + fCL.ToString()).Append("\r\n");
            builder.Append("lCL: " + lCL.ToString()).Append("\r\n");
            builder.Append("sampleQty: " + sampleQty.ToString()).Append("\r\n");
            builder.Append("qty: " + qty.ToString()).Append("\r\n");
            builder.Append("unit: " + unit.ToString()).Append("\r\n");
            builder.Append("amount: " + amount.ToString()).Append("\r\n");
            builder.Append("carton: " + carton.ToString()).Append("\r\n");
            builder.Append("gLAccount: " + gLAccount.ToString()).Append("\r\n");
            builder.Append("refDocNo: " + refDocNo.ToString()).Append("\r\n");
            builder.Append("shippingMark: " + shippingMark.ToString()).Append("\r\n");
            builder.Append("qtyIN: " + qtyIN.ToString()).Append("\r\n");
            builder.Append("qtyOUT: " + qtyOUT.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }

        #region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            string[] textField = { TextField };
            LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            if (SwitchLocale)
            {
                TextField = GetSwitchLocale(TextField);
            }
            ddList.Items.Clear();

            OrderQTItemsCollection source;

            if (OrderBy == null || OrderBy.Length == 0)
            {
                OrderBy = TextField;
            }

            if (WhereClause.Length > 0)
            {
                source = OrderQTItems.LoadCollection(WhereClause, OrderBy, true);
            }
            else
            {
                source = OrderQTItems.LoadCollection(OrderBy, true);
            }

            Common.ComboList sourceList = new Common.ComboList();

            if (BlankLine)
            {
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
            }

            foreach (OrderQTItems item in source)
            {
                bool filter = false;
                if (ParentFilter.Trim() != String.Empty)
                {
                    filter = true;
                    if (item.OrderQTId != Guid.Empty)
                    {
                        filter = IgnorThis(item, ParentFilter);
                    }
                }
                if (!(filter))
                {
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.OrderQTItemId));
                }
            }

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";

            if (ddList.Items.Count > 0)
            {
                ddList.SelectedIndex = 0;
            }
        }

        #endregion


        private static bool IgnorThis(OrderQTItems target, string parentFilter)
        {
            bool result = true;
            parentFilter = parentFilter.Replace(" ", "");       // remove spaces
            parentFilter = parentFilter.Replace("'", "");       // remove '
            string[] parsed = parentFilter.Split('=');          // parse

            if (target.OrderQTId == Guid.Empty)
            {
                PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
                string filterField = (string)pi.GetValue(target, null);
                if (filterField.ToLower() == parsed[1].ToLower())
                {
                    result = false;
                }
            }
            else
            {
                OrderQTItems parentTemplate = OrderQTItems.Load(target.OrderQTId);
                result = IgnorThis(parentTemplate, parentFilter);
            }
            return result;
        }

        private static string GetFormatedText(OrderQTItems target, string[] textField, string textFormatString)
        {
            for (int i = 0; i < textField.Length; i++)
            {
                PropertyInfo pi = target.GetType().GetProperty(textField[i]);
                textFormatString = textFormatString.Replace("{" + i.ToString() + "}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
            }
            return textFormatString;
        }

        private static string[] GetSwitchLocale(string[] source)
        {
            switch (Common.Config.CurrentLanguageId)
            {
                case 2:
                    source[source.Length - 1] += "_Chs";
                    break;
                case 3:
                    source[source.Length - 1] += "_Cht";
                    break;
            }
            return source;
        }
    }


    /// <summary>
    /// Represents a collection of <see cref="OrderQTItems">OrderQTItems</see> objects.
    /// </summary>
    public class OrderQTItemsCollection : BindingList<OrderQTItems>
    {
    }
}
