using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace xPort5.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.OrderIN.
    /// Date Created:   2020-03-02 02:16:02
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class OrderIN
    {
        private Guid key = Guid.Empty;
        private Guid orderINId = Guid.Empty;
        private string iNNumber = String.Empty;
        private DateTime iNDate = DateTime.Parse("1900-1-1");
        private Guid customerId = Guid.Empty;
        private Guid staffId = Guid.Empty;
        private string yourOrderNo = String.Empty;
        private string yourRef = String.Empty;
        private string carrier = String.Empty;
        private Guid paymentTerms = Guid.Empty;
        private Guid pricingTerms = Guid.Empty;
        private Guid loadingPort = Guid.Empty;
        private Guid dischargePort = Guid.Empty;
        private Guid destination = Guid.Empty;
        private Guid originId = Guid.Empty;
        private string sendFrom = String.Empty;
        private string sendTo = String.Empty;
        private int revision = 0;
        private DateTime shipmentDate = DateTime.Parse("1900-1-1");
        private string remarks = String.Empty;
        private string remarks2 = String.Empty;
        private string remarks3 = String.Empty;
        private bool inUse;
        private int status = 0;
        private DateTime createdOn = DateTime.Parse("1900-1-1");
        private Guid createdBy = Guid.Empty;
        private DateTime modifiedOn = DateTime.Parse("1900-1-1");
        private Guid modifiedBy = Guid.Empty;
        private DateTime accessedOn = DateTime.Parse("1900-1-1");
        private Guid accessedBy = Guid.Empty;
        private bool retired;
        private DateTime retiredOn = DateTime.Parse("1900-1-1");
        private Guid retiredBy = Guid.Empty;

        /// <summary>
        /// Initialize an new empty OrderIN object.
        /// </summary>
        public OrderIN()
        {
        }

        /// <summary>
        /// Initialize a new OrderIN object with the given parameters.
        /// </summary>
        public OrderIN(Guid orderINId, string iNNumber, DateTime iNDate, Guid customerId, Guid staffId, string yourOrderNo, string yourRef, string carrier, Guid paymentTerms, Guid pricingTerms, Guid loadingPort, Guid dischargePort, Guid destination, Guid originId, string sendFrom, string sendTo, int revision, DateTime shipmentDate, string remarks, string remarks2, string remarks3, bool inUse, int status, DateTime createdOn, Guid createdBy, DateTime modifiedOn, Guid modifiedBy, DateTime accessedOn, Guid accessedBy, bool retired, DateTime retiredOn, Guid retiredBy)
        {
            this.orderINId = orderINId;
            this.iNNumber = iNNumber;
            this.iNDate = iNDate;
            this.customerId = customerId;
            this.staffId = staffId;
            this.yourOrderNo = yourOrderNo;
            this.yourRef = yourRef;
            this.carrier = carrier;
            this.paymentTerms = paymentTerms;
            this.pricingTerms = pricingTerms;
            this.loadingPort = loadingPort;
            this.dischargePort = dischargePort;
            this.destination = destination;
            this.originId = originId;
            this.sendFrom = sendFrom;
            this.sendTo = sendTo;
            this.revision = revision;
            this.shipmentDate = shipmentDate;
            this.remarks = remarks;
            this.remarks2 = remarks2;
            this.remarks3 = remarks3;
            this.inUse = inUse;
            this.status = status;
            this.createdOn = createdOn;
            this.createdBy = createdBy;
            this.modifiedOn = modifiedOn;
            this.modifiedBy = modifiedBy;
            this.accessedOn = accessedOn;
            this.accessedBy = accessedBy;
            this.retired = retired;
            this.retiredOn = retiredOn;
            this.retiredBy = retiredBy;
        }

        /// <summary>
        /// Loads a OrderIN object from the database using the given OrderINId
        /// </summary>
        /// <param name="orderINId">The primary key value</param>
        /// <returns>A OrderIN object</returns>
        public static OrderIN Load(Guid orderINId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@OrderINId", orderINId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spOrderIN_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    OrderIN result = new OrderIN();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a OrderIN object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A OrderIN object</returns>
        public static OrderIN LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spOrderIN_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    OrderIN result = new OrderIN();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a collection of OrderIN objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the OrderIN objects in the database.</returns>
        public static OrderINCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] { };
            return LoadCollection("spOrderIN_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderIN objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the OrderIN objects in the database ordered by the columns specified.</returns>
        public static OrderINCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spOrderIN_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderIN objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the OrderIN objects in the database.</returns>
        public static OrderINCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spOrderIN_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderIN objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the OrderIN objects in the database ordered by the columns specified.</returns>
        public static OrderINCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spOrderIN_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderIN objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the OrderIN objects in the database.</returns>
        public static OrderINCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            OrderINCollection result = new OrderINCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    OrderIN tmp = new OrderIN();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a OrderIN object from the database.
        /// </summary>
        /// <param name="orderINId">The primary key value</param>
        public static void Delete(Guid orderINId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@OrderINId", orderINId) };
            SqlHelper.Default.ExecuteNonQuery("spOrderIN_DelRec", parameterValues);
        }


        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) orderINId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) iNNumber = reader.GetString(1);
                if (!reader.IsDBNull(2)) iNDate = reader.GetDateTime(2);
                if (!reader.IsDBNull(3)) customerId = reader.GetGuid(3);
                if (!reader.IsDBNull(4)) staffId = reader.GetGuid(4);
                if (!reader.IsDBNull(5)) yourOrderNo = reader.GetString(5);
                if (!reader.IsDBNull(6)) yourRef = reader.GetString(6);
                if (!reader.IsDBNull(7)) carrier = reader.GetString(7);
                if (!reader.IsDBNull(8)) paymentTerms = reader.GetGuid(8);
                if (!reader.IsDBNull(9)) pricingTerms = reader.GetGuid(9);
                if (!reader.IsDBNull(10)) loadingPort = reader.GetGuid(10);
                if (!reader.IsDBNull(11)) dischargePort = reader.GetGuid(11);
                if (!reader.IsDBNull(12)) destination = reader.GetGuid(12);
                if (!reader.IsDBNull(13)) originId = reader.GetGuid(13);
                if (!reader.IsDBNull(14)) sendFrom = reader.GetString(14);
                if (!reader.IsDBNull(15)) sendTo = reader.GetString(15);
                if (!reader.IsDBNull(16)) revision = reader.GetInt32(16);
                if (!reader.IsDBNull(17)) shipmentDate = reader.GetDateTime(17);
                if (!reader.IsDBNull(18)) remarks = reader.GetString(18);
                if (!reader.IsDBNull(19)) remarks2 = reader.GetString(19);
                if (!reader.IsDBNull(20)) remarks3 = reader.GetString(20);
                if (!reader.IsDBNull(21)) inUse = reader.GetBoolean(21);
                if (!reader.IsDBNull(22)) status = reader.GetInt32(22);
                if (!reader.IsDBNull(23)) createdOn = reader.GetDateTime(23);
                if (!reader.IsDBNull(24)) createdBy = reader.GetGuid(24);
                if (!reader.IsDBNull(25)) modifiedOn = reader.GetDateTime(25);
                if (!reader.IsDBNull(26)) modifiedBy = reader.GetGuid(26);
                if (!reader.IsDBNull(27)) accessedOn = reader.GetDateTime(27);
                if (!reader.IsDBNull(28)) accessedBy = reader.GetGuid(28);
                if (!reader.IsDBNull(29)) retired = reader.GetBoolean(29);
                if (!reader.IsDBNull(30)) retiredOn = reader.GetDateTime(30);
                if (!reader.IsDBNull(31)) retiredBy = reader.GetGuid(31);
            }
        }

        public void Delete()
        {
            Delete(this.OrderINId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != OrderINId)
                    this.Delete();
                Update();
            }
        }

        public Guid OrderINId
        {
            get { return orderINId; }
            set { orderINId = value; }
        }

        public string INNumber
        {
            get { return iNNumber; }
            set { iNNumber = value; }
        }

        public DateTime INDate
        {
            get { return iNDate; }
            set { iNDate = value; }
        }

        public Guid CustomerId
        {
            get { return customerId; }
            set { customerId = value; }
        }

        public Guid StaffId
        {
            get { return staffId; }
            set { staffId = value; }
        }

        public string YourOrderNo
        {
            get { return yourOrderNo; }
            set { yourOrderNo = value; }
        }

        public string YourRef
        {
            get { return yourRef; }
            set { yourRef = value; }
        }

        public string Carrier
        {
            get { return carrier; }
            set { carrier = value; }
        }

        public Guid PaymentTerms
        {
            get { return paymentTerms; }
            set { paymentTerms = value; }
        }

        public Guid PricingTerms
        {
            get { return pricingTerms; }
            set { pricingTerms = value; }
        }

        public Guid LoadingPort
        {
            get { return loadingPort; }
            set { loadingPort = value; }
        }

        public Guid DischargePort
        {
            get { return dischargePort; }
            set { dischargePort = value; }
        }

        public Guid Destination
        {
            get { return destination; }
            set { destination = value; }
        }

        public Guid OriginId
        {
            get { return originId; }
            set { originId = value; }
        }

        public string SendFrom
        {
            get { return sendFrom; }
            set { sendFrom = value; }
        }

        public string SendTo
        {
            get { return sendTo; }
            set { sendTo = value; }
        }

        public int Revision
        {
            get { return revision; }
            set { revision = value; }
        }

        public DateTime ShipmentDate
        {
            get { return shipmentDate; }
            set { shipmentDate = value; }
        }

        public string Remarks
        {
            get { return remarks; }
            set { remarks = value; }
        }

        public string Remarks2
        {
            get { return remarks2; }
            set { remarks2 = value; }
        }

        public string Remarks3
        {
            get { return remarks3; }
            set { remarks3 = value; }
        }

        public bool InUse
        {
            get { return inUse; }
            set { inUse = value; }
        }

        public int Status
        {
            get { return status; }
            set { status = value; }
        }

        public DateTime CreatedOn
        {
            get { return createdOn; }
            set { createdOn = value; }
        }

        public Guid CreatedBy
        {
            get { return createdBy; }
            set { createdBy = value; }
        }

        public DateTime ModifiedOn
        {
            get { return modifiedOn; }
            set { modifiedOn = value; }
        }

        public Guid ModifiedBy
        {
            get { return modifiedBy; }
            set { modifiedBy = value; }
        }

        public DateTime AccessedOn
        {
            get { return accessedOn; }
            set { accessedOn = value; }
        }

        public Guid AccessedBy
        {
            get { return accessedBy; }
            set { accessedBy = value; }
        }

        public bool Retired
        {
            get { return retired; }
            set { retired = value; }
        }

        public DateTime RetiredOn
        {
            get { return retiredOn; }
            set { retiredOn = value; }
        }

        public Guid RetiredBy
        {
            get { return retiredBy; }
            set { retiredBy = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;

            SqlHelper.Default.ExecuteNonQuery("spOrderIN_InsRec", "@OrderINId", out returnedValue, parameterValues);

            orderINId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();

            SqlHelper.Default.ExecuteNonQuery("spOrderIN_UpdRec", parameterValues);
        }

        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[32];
            prams[0] = GetSqlParameter("@OrderINId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.OrderINId);
            prams[1] = GetSqlParameter("@INNumber", ParameterDirection.Input, SqlDbType.VarChar, 10, this.INNumber);
            prams[2] = GetSqlParameter("@INDate", ParameterDirection.Input, SqlDbType.DateTime, 8, this.INDate);
            prams[3] = GetSqlParameter("@CustomerId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.CustomerId);
            prams[4] = GetSqlParameter("@StaffId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.StaffId);
            prams[5] = GetSqlParameter("@YourOrderNo", ParameterDirection.Input, SqlDbType.NVarChar, 32, this.YourOrderNo);
            prams[6] = GetSqlParameter("@YourRef", ParameterDirection.Input, SqlDbType.NVarChar, 32, this.YourRef);
            prams[7] = GetSqlParameter("@Carrier", ParameterDirection.Input, SqlDbType.NVarChar, 32, this.Carrier);
            prams[8] = GetSqlParameter("@PaymentTerms", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.PaymentTerms);
            prams[9] = GetSqlParameter("@PricingTerms", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.PricingTerms);
            prams[10] = GetSqlParameter("@LoadingPort", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.LoadingPort);
            prams[11] = GetSqlParameter("@DischargePort", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.DischargePort);
            prams[12] = GetSqlParameter("@Destination", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.Destination);
            prams[13] = GetSqlParameter("@OriginId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.OriginId);
            prams[14] = GetSqlParameter("@SendFrom", ParameterDirection.Input, SqlDbType.VarChar, 16, this.SendFrom);
            prams[15] = GetSqlParameter("@SendTo", ParameterDirection.Input, SqlDbType.VarChar, 16, this.SendTo);
            prams[16] = GetSqlParameter("@Revision", ParameterDirection.Input, SqlDbType.Int, 4, this.Revision);
            prams[17] = GetSqlParameter("@ShipmentDate", ParameterDirection.Input, SqlDbType.DateTime, 8, this.ShipmentDate);
            prams[18] = GetSqlParameter("@Remarks", ParameterDirection.Input, SqlDbType.NVarChar, 255, this.Remarks);
            prams[19] = GetSqlParameter("@Remarks2", ParameterDirection.Input, SqlDbType.NVarChar, 255, this.Remarks2);
            prams[20] = GetSqlParameter("@Remarks3", ParameterDirection.Input, SqlDbType.NVarChar, 255, this.Remarks3);
            prams[21] = GetSqlParameter("@InUse", ParameterDirection.Input, SqlDbType.Bit, 1, this.InUse);
            prams[22] = GetSqlParameter("@Status", ParameterDirection.Input, SqlDbType.Int, 4, this.Status);
            prams[23] = GetSqlParameter("@CreatedOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.CreatedOn);
            prams[24] = GetSqlParameter("@CreatedBy", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.CreatedBy);
            prams[25] = GetSqlParameter("@ModifiedOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.ModifiedOn);
            prams[26] = GetSqlParameter("@ModifiedBy", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.ModifiedBy);
            prams[27] = GetSqlParameter("@AccessedOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.AccessedOn);
            prams[28] = GetSqlParameter("@AccessedBy", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.AccessedBy);
            prams[29] = GetSqlParameter("@Retired", ParameterDirection.Input, SqlDbType.Bit, 1, this.Retired);
            prams[30] = GetSqlParameter("@RetiredOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.RetiredOn);
            prams[31] = GetSqlParameter("@RetiredBy", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.RetiredBy);
            return prams;
        }

        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }

        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[]
            {
                GetSqlParameterWithoutDirection("@OrderINId", SqlDbType.UniqueIdentifier, 16, this.OrderINId),
                GetSqlParameterWithoutDirection("@INNumber", SqlDbType.VarChar, 10, this.INNumber),
                GetSqlParameterWithoutDirection("@INDate", SqlDbType.DateTime, 8, this.INDate),
                GetSqlParameterWithoutDirection("@CustomerId", SqlDbType.UniqueIdentifier, 16, this.CustomerId),
                GetSqlParameterWithoutDirection("@StaffId", SqlDbType.UniqueIdentifier, 16, this.StaffId),
                GetSqlParameterWithoutDirection("@YourOrderNo", SqlDbType.NVarChar, 32, this.YourOrderNo),
                GetSqlParameterWithoutDirection("@YourRef", SqlDbType.NVarChar, 32, this.YourRef),
                GetSqlParameterWithoutDirection("@Carrier", SqlDbType.NVarChar, 32, this.Carrier),
                GetSqlParameterWithoutDirection("@PaymentTerms", SqlDbType.UniqueIdentifier, 16, this.PaymentTerms),
                GetSqlParameterWithoutDirection("@PricingTerms", SqlDbType.UniqueIdentifier, 16, this.PricingTerms),
                GetSqlParameterWithoutDirection("@LoadingPort", SqlDbType.UniqueIdentifier, 16, this.LoadingPort),
                GetSqlParameterWithoutDirection("@DischargePort", SqlDbType.UniqueIdentifier, 16, this.DischargePort),
                GetSqlParameterWithoutDirection("@Destination", SqlDbType.UniqueIdentifier, 16, this.Destination),
                GetSqlParameterWithoutDirection("@OriginId", SqlDbType.UniqueIdentifier, 16, this.OriginId),
                GetSqlParameterWithoutDirection("@SendFrom", SqlDbType.VarChar, 16, this.SendFrom),
                GetSqlParameterWithoutDirection("@SendTo", SqlDbType.VarChar, 16, this.SendTo),
                GetSqlParameterWithoutDirection("@Revision", SqlDbType.Int, 4, this.Revision),
                GetSqlParameterWithoutDirection("@ShipmentDate", SqlDbType.DateTime, 8, this.ShipmentDate),
                GetSqlParameterWithoutDirection("@Remarks", SqlDbType.NVarChar, 255, this.Remarks),
                GetSqlParameterWithoutDirection("@Remarks2", SqlDbType.NVarChar, 255, this.Remarks2),
                GetSqlParameterWithoutDirection("@Remarks3", SqlDbType.NVarChar, 255, this.Remarks3),
                GetSqlParameterWithoutDirection("@InUse", SqlDbType.Bit, 1, this.InUse),
                GetSqlParameterWithoutDirection("@Status", SqlDbType.Int, 4, this.Status),
                GetSqlParameterWithoutDirection("@CreatedOn", SqlDbType.DateTime, 8, this.CreatedOn),
                GetSqlParameterWithoutDirection("@CreatedBy", SqlDbType.UniqueIdentifier, 16, this.CreatedBy),
                GetSqlParameterWithoutDirection("@ModifiedOn", SqlDbType.DateTime, 8, this.ModifiedOn),
                GetSqlParameterWithoutDirection("@ModifiedBy", SqlDbType.UniqueIdentifier, 16, this.ModifiedBy),
                GetSqlParameterWithoutDirection("@AccessedOn", SqlDbType.DateTime, 8, this.AccessedOn),
                GetSqlParameterWithoutDirection("@AccessedBy", SqlDbType.UniqueIdentifier, 16, this.AccessedBy),
                GetSqlParameterWithoutDirection("@Retired", SqlDbType.Bit, 1, this.Retired),
                GetSqlParameterWithoutDirection("@RetiredOn", SqlDbType.DateTime, 8, this.RetiredOn),
                GetSqlParameterWithoutDirection("@RetiredBy", SqlDbType.UniqueIdentifier, 16, this.RetiredBy)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("orderINId: " + orderINId.ToString()).Append("\r\n");
            builder.Append("iNNumber: " + iNNumber.ToString()).Append("\r\n");
            builder.Append("iNDate: " + iNDate.ToString()).Append("\r\n");
            builder.Append("customerId: " + customerId.ToString()).Append("\r\n");
            builder.Append("staffId: " + staffId.ToString()).Append("\r\n");
            builder.Append("yourOrderNo: " + yourOrderNo.ToString()).Append("\r\n");
            builder.Append("yourRef: " + yourRef.ToString()).Append("\r\n");
            builder.Append("carrier: " + carrier.ToString()).Append("\r\n");
            builder.Append("paymentTerms: " + paymentTerms.ToString()).Append("\r\n");
            builder.Append("pricingTerms: " + pricingTerms.ToString()).Append("\r\n");
            builder.Append("loadingPort: " + loadingPort.ToString()).Append("\r\n");
            builder.Append("dischargePort: " + dischargePort.ToString()).Append("\r\n");
            builder.Append("destination: " + destination.ToString()).Append("\r\n");
            builder.Append("originId: " + originId.ToString()).Append("\r\n");
            builder.Append("sendFrom: " + sendFrom.ToString()).Append("\r\n");
            builder.Append("sendTo: " + sendTo.ToString()).Append("\r\n");
            builder.Append("revision: " + revision.ToString()).Append("\r\n");
            builder.Append("shipmentDate: " + shipmentDate.ToString()).Append("\r\n");
            builder.Append("remarks: " + remarks.ToString()).Append("\r\n");
            builder.Append("remarks2: " + remarks2.ToString()).Append("\r\n");
            builder.Append("remarks3: " + remarks3.ToString()).Append("\r\n");
            builder.Append("inUse: " + inUse.ToString()).Append("\r\n");
            builder.Append("status: " + status.ToString()).Append("\r\n");
            builder.Append("createdOn: " + createdOn.ToString()).Append("\r\n");
            builder.Append("createdBy: " + createdBy.ToString()).Append("\r\n");
            builder.Append("modifiedOn: " + modifiedOn.ToString()).Append("\r\n");
            builder.Append("modifiedBy: " + modifiedBy.ToString()).Append("\r\n");
            builder.Append("accessedOn: " + accessedOn.ToString()).Append("\r\n");
            builder.Append("accessedBy: " + accessedBy.ToString()).Append("\r\n");
            builder.Append("retired: " + retired.ToString()).Append("\r\n");
            builder.Append("retiredOn: " + retiredOn.ToString()).Append("\r\n");
            builder.Append("retiredBy: " + retiredBy.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }

        #region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            string[] textField = { TextField };
            LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            if (SwitchLocale)
            {
                TextField = GetSwitchLocale(TextField);
            }
            ddList.Items.Clear();

            OrderINCollection source;

            if (OrderBy == null || OrderBy.Length == 0)
            {
                OrderBy = TextField;
            }
            // Filter the retired records
            if (WhereClause.Length > 0)
            {
                WhereClause += " AND Retired = 0";
            }
            else
            {
                WhereClause = "Retired = 0";
            }

            if (WhereClause.Length > 0)
            {
                source = OrderIN.LoadCollection(WhereClause, OrderBy, true);
            }
            else
            {
                source = OrderIN.LoadCollection(OrderBy, true);
            }

            Common.ComboList sourceList = new Common.ComboList();

            if (BlankLine)
            {
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
            }

            foreach (OrderIN item in source)
            {
                bool filter = false;
                if (ParentFilter.Trim() != String.Empty)
                {
                    filter = true;
                    if (item.CustomerId != Guid.Empty)
                    {
                        filter = IgnorThis(item, ParentFilter);
                    }
                }
                if (!(filter))
                {
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.OrderINId));
                }
            }

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";

            if (ddList.Items.Count > 0)
            {
                ddList.SelectedIndex = 0;
            }
        }

        #endregion


        private static bool IgnorThis(OrderIN target, string parentFilter)
        {
            bool result = true;
            parentFilter = parentFilter.Replace(" ", "");       // remove spaces
            parentFilter = parentFilter.Replace("'", "");       // remove '
            string[] parsed = parentFilter.Split('=');          // parse

            if (target.CustomerId == Guid.Empty)
            {
                PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
                string filterField = (string)pi.GetValue(target, null);
                if (filterField.ToLower() == parsed[1].ToLower())
                {
                    result = false;
                }
            }
            else
            {
                OrderIN parentTemplate = OrderIN.Load(target.CustomerId);
                result = IgnorThis(parentTemplate, parentFilter);
            }
            return result;
        }

        private static string GetFormatedText(OrderIN target, string[] textField, string textFormatString)
        {
            for (int i = 0; i < textField.Length; i++)
            {
                PropertyInfo pi = target.GetType().GetProperty(textField[i]);
                textFormatString = textFormatString.Replace("{" + i.ToString() + "}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
            }
            return textFormatString;
        }

        private static string[] GetSwitchLocale(string[] source)
        {
            switch (Common.Config.CurrentLanguageId)
            {
                case 2:
                    source[source.Length - 1] += "_Chs";
                    break;
                case 3:
                    source[source.Length - 1] += "_Cht";
                    break;
            }
            return source;
        }
    }


    /// <summary>
    /// Represents a collection of <see cref="OrderIN">OrderIN</see> objects.
    /// </summary>
    public class OrderINCollection : BindingList<OrderIN>
    {
    }
}
