using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace xPort5.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.OrderPK.
    /// Date Created:   2020-03-02 02:18:22
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class OrderPK
    {
        private Guid key = Guid.Empty;
        private Guid orderPKId = Guid.Empty;
        private string pKNumber = String.Empty;
        private Guid customerId = Guid.Empty;
        private Guid staffId = Guid.Empty;
        private decimal fCLFactor;
        private decimal lCLFactor;
        private string unit = String.Empty;
        private string measurement = String.Empty;
        private int inputMask = 0;
        private string remarks = String.Empty;
        private Guid currencyId = Guid.Empty;
        private decimal exchangeRate;
        private string paymentTerms = String.Empty;
        private decimal repayment;
        private bool inUse;
        private int status = 0;
        private DateTime createdDate = DateTime.Parse("1900-1-1");
        private string createdUser = String.Empty;
        private DateTime accessedDate = DateTime.Parse("1900-1-1");
        private string accessedUser = String.Empty;
        private DateTime modifiedDate = DateTime.Parse("1900-1-1");
        private string modifiedUser = String.Empty;
        private string sendFrom = String.Empty;
        private string sendTo = String.Empty;
        private int revision = 0;
        private DateTime shipmentDate = DateTime.Parse("1900-1-1");

        /// <summary>
        /// Initialize an new empty OrderPK object.
        /// </summary>
        public OrderPK()
        {
        }

        /// <summary>
        /// Initialize a new OrderPK object with the given parameters.
        /// </summary>
        public OrderPK(Guid orderPKId, string pKNumber, Guid customerId, Guid staffId, decimal fCLFactor, decimal lCLFactor, string unit, string measurement, int inputMask, string remarks, Guid currencyId, decimal exchangeRate, string paymentTerms, decimal repayment, bool inUse, int status, DateTime createdDate, string createdUser, DateTime accessedDate, string accessedUser, DateTime modifiedDate, string modifiedUser, string sendFrom, string sendTo, int revision, DateTime shipmentDate)
        {
            this.orderPKId = orderPKId;
            this.pKNumber = pKNumber;
            this.customerId = customerId;
            this.staffId = staffId;
            this.fCLFactor = fCLFactor;
            this.lCLFactor = lCLFactor;
            this.unit = unit;
            this.measurement = measurement;
            this.inputMask = inputMask;
            this.remarks = remarks;
            this.currencyId = currencyId;
            this.exchangeRate = exchangeRate;
            this.paymentTerms = paymentTerms;
            this.repayment = repayment;
            this.inUse = inUse;
            this.status = status;
            this.createdDate = createdDate;
            this.createdUser = createdUser;
            this.accessedDate = accessedDate;
            this.accessedUser = accessedUser;
            this.modifiedDate = modifiedDate;
            this.modifiedUser = modifiedUser;
            this.sendFrom = sendFrom;
            this.sendTo = sendTo;
            this.revision = revision;
            this.shipmentDate = shipmentDate;
        }

        /// <summary>
        /// Loads a OrderPK object from the database using the given OrderPKId
        /// </summary>
        /// <param name="orderPKId">The primary key value</param>
        /// <returns>A OrderPK object</returns>
        public static OrderPK Load(Guid orderPKId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@OrderPKId", orderPKId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spOrderPK_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    OrderPK result = new OrderPK();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a OrderPK object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A OrderPK object</returns>
        public static OrderPK LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spOrderPK_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    OrderPK result = new OrderPK();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a collection of OrderPK objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the OrderPK objects in the database.</returns>
        public static OrderPKCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] { };
            return LoadCollection("spOrderPK_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderPK objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the OrderPK objects in the database ordered by the columns specified.</returns>
        public static OrderPKCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spOrderPK_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderPK objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the OrderPK objects in the database.</returns>
        public static OrderPKCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spOrderPK_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderPK objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the OrderPK objects in the database ordered by the columns specified.</returns>
        public static OrderPKCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spOrderPK_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderPK objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the OrderPK objects in the database.</returns>
        public static OrderPKCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            OrderPKCollection result = new OrderPKCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    OrderPK tmp = new OrderPK();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a OrderPK object from the database.
        /// </summary>
        /// <param name="orderPKId">The primary key value</param>
        public static void Delete(Guid orderPKId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@OrderPKId", orderPKId) };
            SqlHelper.Default.ExecuteNonQuery("spOrderPK_DelRec", parameterValues);
        }


        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) orderPKId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) pKNumber = reader.GetString(1);
                if (!reader.IsDBNull(2)) customerId = reader.GetGuid(2);
                if (!reader.IsDBNull(3)) staffId = reader.GetGuid(3);
                if (!reader.IsDBNull(4)) fCLFactor = reader.GetDecimal(4);
                if (!reader.IsDBNull(5)) lCLFactor = reader.GetDecimal(5);
                if (!reader.IsDBNull(6)) unit = reader.GetString(6);
                if (!reader.IsDBNull(7)) measurement = reader.GetString(7);
                if (!reader.IsDBNull(8)) inputMask = reader.GetInt32(8);
                if (!reader.IsDBNull(9)) remarks = reader.GetString(9);
                if (!reader.IsDBNull(10)) currencyId = reader.GetGuid(10);
                if (!reader.IsDBNull(11)) exchangeRate = reader.GetDecimal(11);
                if (!reader.IsDBNull(12)) paymentTerms = reader.GetString(12);
                if (!reader.IsDBNull(13)) repayment = reader.GetDecimal(13);
                if (!reader.IsDBNull(14)) inUse = reader.GetBoolean(14);
                if (!reader.IsDBNull(15)) status = reader.GetInt32(15);
                if (!reader.IsDBNull(16)) createdDate = reader.GetDateTime(16);
                if (!reader.IsDBNull(17)) createdUser = reader.GetString(17);
                if (!reader.IsDBNull(18)) accessedDate = reader.GetDateTime(18);
                if (!reader.IsDBNull(19)) accessedUser = reader.GetString(19);
                if (!reader.IsDBNull(20)) modifiedDate = reader.GetDateTime(20);
                if (!reader.IsDBNull(21)) modifiedUser = reader.GetString(21);
                if (!reader.IsDBNull(22)) sendFrom = reader.GetString(22);
                if (!reader.IsDBNull(23)) sendTo = reader.GetString(23);
                if (!reader.IsDBNull(24)) revision = reader.GetInt32(24);
                if (!reader.IsDBNull(25)) shipmentDate = reader.GetDateTime(25);
            }
        }

        public void Delete()
        {
            Delete(this.OrderPKId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != OrderPKId)
                    this.Delete();
                Update();
            }
        }

        public Guid OrderPKId
        {
            get { return orderPKId; }
            set { orderPKId = value; }
        }

        public string PKNumber
        {
            get { return pKNumber; }
            set { pKNumber = value; }
        }

        public Guid CustomerId
        {
            get { return customerId; }
            set { customerId = value; }
        }

        public Guid StaffId
        {
            get { return staffId; }
            set { staffId = value; }
        }

        public decimal FCLFactor
        {
            get { return fCLFactor; }
            set { fCLFactor = value; }
        }

        public decimal LCLFactor
        {
            get { return lCLFactor; }
            set { lCLFactor = value; }
        }

        public string Unit
        {
            get { return unit; }
            set { unit = value; }
        }

        public string Measurement
        {
            get { return measurement; }
            set { measurement = value; }
        }

        public int InputMask
        {
            get { return inputMask; }
            set { inputMask = value; }
        }

        public string Remarks
        {
            get { return remarks; }
            set { remarks = value; }
        }

        public Guid CurrencyId
        {
            get { return currencyId; }
            set { currencyId = value; }
        }

        public decimal ExchangeRate
        {
            get { return exchangeRate; }
            set { exchangeRate = value; }
        }

        public string PaymentTerms
        {
            get { return paymentTerms; }
            set { paymentTerms = value; }
        }

        public decimal Repayment
        {
            get { return repayment; }
            set { repayment = value; }
        }

        public bool InUse
        {
            get { return inUse; }
            set { inUse = value; }
        }

        public int Status
        {
            get { return status; }
            set { status = value; }
        }

        public DateTime CreatedDate
        {
            get { return createdDate; }
            set { createdDate = value; }
        }

        public string CreatedUser
        {
            get { return createdUser; }
            set { createdUser = value; }
        }

        public DateTime AccessedDate
        {
            get { return accessedDate; }
            set { accessedDate = value; }
        }

        public string AccessedUser
        {
            get { return accessedUser; }
            set { accessedUser = value; }
        }

        public DateTime ModifiedDate
        {
            get { return modifiedDate; }
            set { modifiedDate = value; }
        }

        public string ModifiedUser
        {
            get { return modifiedUser; }
            set { modifiedUser = value; }
        }

        public string SendFrom
        {
            get { return sendFrom; }
            set { sendFrom = value; }
        }

        public string SendTo
        {
            get { return sendTo; }
            set { sendTo = value; }
        }

        public int Revision
        {
            get { return revision; }
            set { revision = value; }
        }

        public DateTime ShipmentDate
        {
            get { return shipmentDate; }
            set { shipmentDate = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;

            SqlHelper.Default.ExecuteNonQuery("spOrderPK_InsRec", "@OrderPKId", out returnedValue, parameterValues);

            orderPKId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();

            SqlHelper.Default.ExecuteNonQuery("spOrderPK_UpdRec", parameterValues);
        }

        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[26];
            prams[0] = GetSqlParameter("@OrderPKId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.OrderPKId);
            prams[1] = GetSqlParameter("@PKNumber", ParameterDirection.Input, SqlDbType.VarChar, 10, this.PKNumber);
            prams[2] = GetSqlParameter("@CustomerId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.CustomerId);
            prams[3] = GetSqlParameter("@StaffId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.StaffId);
            prams[4] = GetSqlParameter("@FCLFactor", ParameterDirection.Input, SqlDbType.Decimal, 9, this.FCLFactor);
            prams[5] = GetSqlParameter("@LCLFactor", ParameterDirection.Input, SqlDbType.Decimal, 9, this.LCLFactor);
            prams[6] = GetSqlParameter("@Unit", ParameterDirection.Input, SqlDbType.VarChar, 6, this.Unit);
            prams[7] = GetSqlParameter("@Measurement", ParameterDirection.Input, SqlDbType.VarChar, 10, this.Measurement);
            prams[8] = GetSqlParameter("@InputMask", ParameterDirection.Input, SqlDbType.Int, 4, this.InputMask);
            prams[9] = GetSqlParameter("@Remarks", ParameterDirection.Input, SqlDbType.NVarChar, 255, this.Remarks);
            prams[10] = GetSqlParameter("@CurrencyId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.CurrencyId);
            prams[11] = GetSqlParameter("@ExchangeRate", ParameterDirection.Input, SqlDbType.Decimal, 9, this.ExchangeRate);
            prams[12] = GetSqlParameter("@PaymentTerms", ParameterDirection.Input, SqlDbType.VarChar, 6, this.PaymentTerms);
            prams[13] = GetSqlParameter("@Repayment", ParameterDirection.Input, SqlDbType.Decimal, 9, this.Repayment);
            prams[14] = GetSqlParameter("@InUse", ParameterDirection.Input, SqlDbType.Bit, 1, this.InUse);
            prams[15] = GetSqlParameter("@Status", ParameterDirection.Input, SqlDbType.Int, 4, this.Status);
            prams[16] = GetSqlParameter("@CreatedDate", ParameterDirection.Input, SqlDbType.DateTime, 8, this.CreatedDate);
            prams[17] = GetSqlParameter("@CreatedUser", ParameterDirection.Input, SqlDbType.VarChar, 16, this.CreatedUser);
            prams[18] = GetSqlParameter("@AccessedDate", ParameterDirection.Input, SqlDbType.DateTime, 8, this.AccessedDate);
            prams[19] = GetSqlParameter("@AccessedUser", ParameterDirection.Input, SqlDbType.VarChar, 16, this.AccessedUser);
            prams[20] = GetSqlParameter("@ModifiedDate", ParameterDirection.Input, SqlDbType.DateTime, 8, this.ModifiedDate);
            prams[21] = GetSqlParameter("@ModifiedUser", ParameterDirection.Input, SqlDbType.VarChar, 16, this.ModifiedUser);
            prams[22] = GetSqlParameter("@SendFrom", ParameterDirection.Input, SqlDbType.NVarChar, 16, this.SendFrom);
            prams[23] = GetSqlParameter("@SendTo", ParameterDirection.Input, SqlDbType.NVarChar, 16, this.SendTo);
            prams[24] = GetSqlParameter("@Revision", ParameterDirection.Input, SqlDbType.Int, 4, this.Revision);
            prams[25] = GetSqlParameter("@ShipmentDate", ParameterDirection.Input, SqlDbType.DateTime, 8, this.ShipmentDate);
            return prams;
        }

        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }

        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[]
            {
                GetSqlParameterWithoutDirection("@OrderPKId", SqlDbType.UniqueIdentifier, 16, this.OrderPKId),
                GetSqlParameterWithoutDirection("@PKNumber", SqlDbType.VarChar, 10, this.PKNumber),
                GetSqlParameterWithoutDirection("@CustomerId", SqlDbType.UniqueIdentifier, 16, this.CustomerId),
                GetSqlParameterWithoutDirection("@StaffId", SqlDbType.UniqueIdentifier, 16, this.StaffId),
                GetSqlParameterWithoutDirection("@FCLFactor", SqlDbType.Decimal, 9, this.FCLFactor),
                GetSqlParameterWithoutDirection("@LCLFactor", SqlDbType.Decimal, 9, this.LCLFactor),
                GetSqlParameterWithoutDirection("@Unit", SqlDbType.VarChar, 6, this.Unit),
                GetSqlParameterWithoutDirection("@Measurement", SqlDbType.VarChar, 10, this.Measurement),
                GetSqlParameterWithoutDirection("@InputMask", SqlDbType.Int, 4, this.InputMask),
                GetSqlParameterWithoutDirection("@Remarks", SqlDbType.NVarChar, 255, this.Remarks),
                GetSqlParameterWithoutDirection("@CurrencyId", SqlDbType.UniqueIdentifier, 16, this.CurrencyId),
                GetSqlParameterWithoutDirection("@ExchangeRate", SqlDbType.Decimal, 9, this.ExchangeRate),
                GetSqlParameterWithoutDirection("@PaymentTerms", SqlDbType.VarChar, 6, this.PaymentTerms),
                GetSqlParameterWithoutDirection("@Repayment", SqlDbType.Decimal, 9, this.Repayment),
                GetSqlParameterWithoutDirection("@InUse", SqlDbType.Bit, 1, this.InUse),
                GetSqlParameterWithoutDirection("@Status", SqlDbType.Int, 4, this.Status),
                GetSqlParameterWithoutDirection("@CreatedDate", SqlDbType.DateTime, 8, this.CreatedDate),
                GetSqlParameterWithoutDirection("@CreatedUser", SqlDbType.VarChar, 16, this.CreatedUser),
                GetSqlParameterWithoutDirection("@AccessedDate", SqlDbType.DateTime, 8, this.AccessedDate),
                GetSqlParameterWithoutDirection("@AccessedUser", SqlDbType.VarChar, 16, this.AccessedUser),
                GetSqlParameterWithoutDirection("@ModifiedDate", SqlDbType.DateTime, 8, this.ModifiedDate),
                GetSqlParameterWithoutDirection("@ModifiedUser", SqlDbType.VarChar, 16, this.ModifiedUser),
                GetSqlParameterWithoutDirection("@SendFrom", SqlDbType.NVarChar, 16, this.SendFrom),
                GetSqlParameterWithoutDirection("@SendTo", SqlDbType.NVarChar, 16, this.SendTo),
                GetSqlParameterWithoutDirection("@Revision", SqlDbType.Int, 4, this.Revision),
                GetSqlParameterWithoutDirection("@ShipmentDate", SqlDbType.DateTime, 8, this.ShipmentDate)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("orderPKId: " + orderPKId.ToString()).Append("\r\n");
            builder.Append("pKNumber: " + pKNumber.ToString()).Append("\r\n");
            builder.Append("customerId: " + customerId.ToString()).Append("\r\n");
            builder.Append("staffId: " + staffId.ToString()).Append("\r\n");
            builder.Append("fCLFactor: " + fCLFactor.ToString()).Append("\r\n");
            builder.Append("lCLFactor: " + lCLFactor.ToString()).Append("\r\n");
            builder.Append("unit: " + unit.ToString()).Append("\r\n");
            builder.Append("measurement: " + measurement.ToString()).Append("\r\n");
            builder.Append("inputMask: " + inputMask.ToString()).Append("\r\n");
            builder.Append("remarks: " + remarks.ToString()).Append("\r\n");
            builder.Append("currencyId: " + currencyId.ToString()).Append("\r\n");
            builder.Append("exchangeRate: " + exchangeRate.ToString()).Append("\r\n");
            builder.Append("paymentTerms: " + paymentTerms.ToString()).Append("\r\n");
            builder.Append("repayment: " + repayment.ToString()).Append("\r\n");
            builder.Append("inUse: " + inUse.ToString()).Append("\r\n");
            builder.Append("status: " + status.ToString()).Append("\r\n");
            builder.Append("createdDate: " + createdDate.ToString()).Append("\r\n");
            builder.Append("createdUser: " + createdUser.ToString()).Append("\r\n");
            builder.Append("accessedDate: " + accessedDate.ToString()).Append("\r\n");
            builder.Append("accessedUser: " + accessedUser.ToString()).Append("\r\n");
            builder.Append("modifiedDate: " + modifiedDate.ToString()).Append("\r\n");
            builder.Append("modifiedUser: " + modifiedUser.ToString()).Append("\r\n");
            builder.Append("sendFrom: " + sendFrom.ToString()).Append("\r\n");
            builder.Append("sendTo: " + sendTo.ToString()).Append("\r\n");
            builder.Append("revision: " + revision.ToString()).Append("\r\n");
            builder.Append("shipmentDate: " + shipmentDate.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }

        #region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            string[] textField = { TextField };
            LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            if (SwitchLocale)
            {
                TextField = GetSwitchLocale(TextField);
            }
            ddList.Items.Clear();

            OrderPKCollection source;

            if (OrderBy == null || OrderBy.Length == 0)
            {
                OrderBy = TextField;
            }

            if (WhereClause.Length > 0)
            {
                source = OrderPK.LoadCollection(WhereClause, OrderBy, true);
            }
            else
            {
                source = OrderPK.LoadCollection(OrderBy, true);
            }

            Common.ComboList sourceList = new Common.ComboList();

            if (BlankLine)
            {
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
            }

            foreach (OrderPK item in source)
            {
                bool filter = false;
                if (ParentFilter.Trim() != String.Empty)
                {
                    filter = true;
                    if (item.CustomerId != Guid.Empty)
                    {
                        filter = IgnorThis(item, ParentFilter);
                    }
                }
                if (!(filter))
                {
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.OrderPKId));
                }
            }

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";

            if (ddList.Items.Count > 0)
            {
                ddList.SelectedIndex = 0;
            }
        }

        #endregion


        private static bool IgnorThis(OrderPK target, string parentFilter)
        {
            bool result = true;
            parentFilter = parentFilter.Replace(" ", "");       // remove spaces
            parentFilter = parentFilter.Replace("'", "");       // remove '
            string[] parsed = parentFilter.Split('=');          // parse

            if (target.CustomerId == Guid.Empty)
            {
                PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
                string filterField = (string)pi.GetValue(target, null);
                if (filterField.ToLower() == parsed[1].ToLower())
                {
                    result = false;
                }
            }
            else
            {
                OrderPK parentTemplate = OrderPK.Load(target.CustomerId);
                result = IgnorThis(parentTemplate, parentFilter);
            }
            return result;
        }

        private static string GetFormatedText(OrderPK target, string[] textField, string textFormatString)
        {
            for (int i = 0; i < textField.Length; i++)
            {
                PropertyInfo pi = target.GetType().GetProperty(textField[i]);
                textFormatString = textFormatString.Replace("{" + i.ToString() + "}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
            }
            return textFormatString;
        }

        private static string[] GetSwitchLocale(string[] source)
        {
            switch (Common.Config.CurrentLanguageId)
            {
                case 2:
                    source[source.Length - 1] += "_Chs";
                    break;
                case 3:
                    source[source.Length - 1] += "_Cht";
                    break;
            }
            return source;
        }
    }


    /// <summary>
    /// Represents a collection of <see cref="OrderPK">OrderPK</see> objects.
    /// </summary>
    public class OrderPKCollection : BindingList<OrderPK>
    {
    }
}
