using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace xPort5.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.OrderQT.
    /// Date Created:   2020-03-02 02:20:04
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class OrderQT
    {
        private Guid key = Guid.Empty;
        private Guid orderQTId = Guid.Empty;
        private string qTNumber = String.Empty;
        private DateTime qTDate = DateTime.Parse("1900-1-1");
        private Guid customerId = Guid.Empty;
        private Guid staffId = Guid.Empty;
        private int priceMethod = 0;
        private decimal fCLFactor;
        private decimal lCLFactor;
        private string unit = String.Empty;
        private string measurement = String.Empty;
        private decimal sampleQty;
        private int inputMask = 0;
        private Guid currencyId = Guid.Empty;
        private decimal exchangeRate;
        private Guid termsId = Guid.Empty;
        private decimal repayment;
        private string sendFrom = String.Empty;
        private string sendTo = String.Empty;
        private decimal totalQty;
        private decimal totalQtyIN;
        private decimal totalQtyOUT;
        private decimal totalAmount;
        private string remarks = String.Empty;
        private string remarks2 = String.Empty;
        private string remarks3 = String.Empty;
        private int revision = 0;
        private bool inUse;
        private int status = 0;
        private DateTime createdOn = DateTime.Parse("1900-1-1");
        private Guid createdBy = Guid.Empty;
        private DateTime modifiedOn = DateTime.Parse("1900-1-1");
        private Guid modifiedBy = Guid.Empty;
        private DateTime accessedOn = DateTime.Parse("1900-1-1");
        private Guid accessedBy = Guid.Empty;
        private bool retired;
        private DateTime retiredOn = DateTime.Parse("1900-1-1");
        private Guid retiredBy = Guid.Empty;

        /// <summary>
        /// Initialize an new empty OrderQT object.
        /// </summary>
        public OrderQT()
        {
        }

        /// <summary>
        /// Initialize a new OrderQT object with the given parameters.
        /// </summary>
        public OrderQT(Guid orderQTId, string qTNumber, DateTime qTDate, Guid customerId, Guid staffId, int priceMethod, decimal fCLFactor, decimal lCLFactor, string unit, string measurement, decimal sampleQty, int inputMask, Guid currencyId, decimal exchangeRate, Guid termsId, decimal repayment, string sendFrom, string sendTo, decimal totalQty, decimal totalQtyIN, decimal totalQtyOUT, decimal totalAmount, string remarks, string remarks2, string remarks3, int revision, bool inUse, int status, DateTime createdOn, Guid createdBy, DateTime modifiedOn, Guid modifiedBy, DateTime accessedOn, Guid accessedBy, bool retired, DateTime retiredOn, Guid retiredBy)
        {
            this.orderQTId = orderQTId;
            this.qTNumber = qTNumber;
            this.qTDate = qTDate;
            this.customerId = customerId;
            this.staffId = staffId;
            this.priceMethod = priceMethod;
            this.fCLFactor = fCLFactor;
            this.lCLFactor = lCLFactor;
            this.unit = unit;
            this.measurement = measurement;
            this.sampleQty = sampleQty;
            this.inputMask = inputMask;
            this.currencyId = currencyId;
            this.exchangeRate = exchangeRate;
            this.termsId = termsId;
            this.repayment = repayment;
            this.sendFrom = sendFrom;
            this.sendTo = sendTo;
            this.totalQty = totalQty;
            this.totalQtyIN = totalQtyIN;
            this.totalQtyOUT = totalQtyOUT;
            this.totalAmount = totalAmount;
            this.remarks = remarks;
            this.remarks2 = remarks2;
            this.remarks3 = remarks3;
            this.revision = revision;
            this.inUse = inUse;
            this.status = status;
            this.createdOn = createdOn;
            this.createdBy = createdBy;
            this.modifiedOn = modifiedOn;
            this.modifiedBy = modifiedBy;
            this.accessedOn = accessedOn;
            this.accessedBy = accessedBy;
            this.retired = retired;
            this.retiredOn = retiredOn;
            this.retiredBy = retiredBy;
        }

        /// <summary>
        /// Loads a OrderQT object from the database using the given OrderQTId
        /// </summary>
        /// <param name="orderQTId">The primary key value</param>
        /// <returns>A OrderQT object</returns>
        public static OrderQT Load(Guid orderQTId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@OrderQTId", orderQTId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spOrderQT_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    OrderQT result = new OrderQT();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a OrderQT object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A OrderQT object</returns>
        public static OrderQT LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spOrderQT_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    OrderQT result = new OrderQT();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a collection of OrderQT objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the OrderQT objects in the database.</returns>
        public static OrderQTCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] { };
            return LoadCollection("spOrderQT_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderQT objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the OrderQT objects in the database ordered by the columns specified.</returns>
        public static OrderQTCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spOrderQT_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderQT objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the OrderQT objects in the database.</returns>
        public static OrderQTCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spOrderQT_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderQT objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the OrderQT objects in the database ordered by the columns specified.</returns>
        public static OrderQTCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spOrderQT_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderQT objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the OrderQT objects in the database.</returns>
        public static OrderQTCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            OrderQTCollection result = new OrderQTCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    OrderQT tmp = new OrderQT();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a OrderQT object from the database.
        /// </summary>
        /// <param name="orderQTId">The primary key value</param>
        public static void Delete(Guid orderQTId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@OrderQTId", orderQTId) };
            SqlHelper.Default.ExecuteNonQuery("spOrderQT_DelRec", parameterValues);
        }


        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) orderQTId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) qTNumber = reader.GetString(1);
                if (!reader.IsDBNull(2)) qTDate = reader.GetDateTime(2);
                if (!reader.IsDBNull(3)) customerId = reader.GetGuid(3);
                if (!reader.IsDBNull(4)) staffId = reader.GetGuid(4);
                if (!reader.IsDBNull(5)) priceMethod = reader.GetInt32(5);
                if (!reader.IsDBNull(6)) fCLFactor = reader.GetDecimal(6);
                if (!reader.IsDBNull(7)) lCLFactor = reader.GetDecimal(7);
                if (!reader.IsDBNull(8)) unit = reader.GetString(8);
                if (!reader.IsDBNull(9)) measurement = reader.GetString(9);
                if (!reader.IsDBNull(10)) sampleQty = reader.GetDecimal(10);
                if (!reader.IsDBNull(11)) inputMask = reader.GetInt32(11);
                if (!reader.IsDBNull(12)) currencyId = reader.GetGuid(12);
                if (!reader.IsDBNull(13)) exchangeRate = reader.GetDecimal(13);
                if (!reader.IsDBNull(14)) termsId = reader.GetGuid(14);
                if (!reader.IsDBNull(15)) repayment = reader.GetDecimal(15);
                if (!reader.IsDBNull(16)) sendFrom = reader.GetString(16);
                if (!reader.IsDBNull(17)) sendTo = reader.GetString(17);
                if (!reader.IsDBNull(18)) totalQty = reader.GetDecimal(18);
                if (!reader.IsDBNull(19)) totalQtyIN = reader.GetDecimal(19);
                if (!reader.IsDBNull(20)) totalQtyOUT = reader.GetDecimal(20);
                if (!reader.IsDBNull(21)) totalAmount = reader.GetDecimal(21);
                if (!reader.IsDBNull(22)) remarks = reader.GetString(22);
                if (!reader.IsDBNull(23)) remarks2 = reader.GetString(23);
                if (!reader.IsDBNull(24)) remarks3 = reader.GetString(24);
                if (!reader.IsDBNull(25)) revision = reader.GetInt32(25);
                if (!reader.IsDBNull(26)) inUse = reader.GetBoolean(26);
                if (!reader.IsDBNull(27)) status = reader.GetInt32(27);
                if (!reader.IsDBNull(28)) createdOn = reader.GetDateTime(28);
                if (!reader.IsDBNull(29)) createdBy = reader.GetGuid(29);
                if (!reader.IsDBNull(30)) modifiedOn = reader.GetDateTime(30);
                if (!reader.IsDBNull(31)) modifiedBy = reader.GetGuid(31);
                if (!reader.IsDBNull(32)) accessedOn = reader.GetDateTime(32);
                if (!reader.IsDBNull(33)) accessedBy = reader.GetGuid(33);
                if (!reader.IsDBNull(34)) retired = reader.GetBoolean(34);
                if (!reader.IsDBNull(35)) retiredOn = reader.GetDateTime(35);
                if (!reader.IsDBNull(36)) retiredBy = reader.GetGuid(36);
            }
        }

        public void Delete()
        {
            Delete(this.OrderQTId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != OrderQTId)
                    this.Delete();
                Update();
            }
        }

        public Guid OrderQTId
        {
            get { return orderQTId; }
            set { orderQTId = value; }
        }

        public string QTNumber
        {
            get { return qTNumber; }
            set { qTNumber = value; }
        }

        public DateTime QTDate
        {
            get { return qTDate; }
            set { qTDate = value; }
        }

        public Guid CustomerId
        {
            get { return customerId; }
            set { customerId = value; }
        }

        public Guid StaffId
        {
            get { return staffId; }
            set { staffId = value; }
        }

        public int PriceMethod
        {
            get { return priceMethod; }
            set { priceMethod = value; }
        }

        public decimal FCLFactor
        {
            get { return fCLFactor; }
            set { fCLFactor = value; }
        }

        public decimal LCLFactor
        {
            get { return lCLFactor; }
            set { lCLFactor = value; }
        }

        public string Unit
        {
            get { return unit; }
            set { unit = value; }
        }

        public string Measurement
        {
            get { return measurement; }
            set { measurement = value; }
        }

        public decimal SampleQty
        {
            get { return sampleQty; }
            set { sampleQty = value; }
        }

        public int InputMask
        {
            get { return inputMask; }
            set { inputMask = value; }
        }

        public Guid CurrencyId
        {
            get { return currencyId; }
            set { currencyId = value; }
        }

        public decimal ExchangeRate
        {
            get { return exchangeRate; }
            set { exchangeRate = value; }
        }

        public Guid TermsId
        {
            get { return termsId; }
            set { termsId = value; }
        }

        public decimal Repayment
        {
            get { return repayment; }
            set { repayment = value; }
        }

        public string SendFrom
        {
            get { return sendFrom; }
            set { sendFrom = value; }
        }

        public string SendTo
        {
            get { return sendTo; }
            set { sendTo = value; }
        }

        public decimal TotalQty
        {
            get { return totalQty; }
            set { totalQty = value; }
        }

        public decimal TotalQtyIN
        {
            get { return totalQtyIN; }
            set { totalQtyIN = value; }
        }

        public decimal TotalQtyOUT
        {
            get { return totalQtyOUT; }
            set { totalQtyOUT = value; }
        }

        public decimal TotalAmount
        {
            get { return totalAmount; }
            set { totalAmount = value; }
        }

        public string Remarks
        {
            get { return remarks; }
            set { remarks = value; }
        }

        public string Remarks2
        {
            get { return remarks2; }
            set { remarks2 = value; }
        }

        public string Remarks3
        {
            get { return remarks3; }
            set { remarks3 = value; }
        }

        public int Revision
        {
            get { return revision; }
            set { revision = value; }
        }

        public bool InUse
        {
            get { return inUse; }
            set { inUse = value; }
        }

        public int Status
        {
            get { return status; }
            set { status = value; }
        }

        public DateTime CreatedOn
        {
            get { return createdOn; }
            set { createdOn = value; }
        }

        public Guid CreatedBy
        {
            get { return createdBy; }
            set { createdBy = value; }
        }

        public DateTime ModifiedOn
        {
            get { return modifiedOn; }
            set { modifiedOn = value; }
        }

        public Guid ModifiedBy
        {
            get { return modifiedBy; }
            set { modifiedBy = value; }
        }

        public DateTime AccessedOn
        {
            get { return accessedOn; }
            set { accessedOn = value; }
        }

        public Guid AccessedBy
        {
            get { return accessedBy; }
            set { accessedBy = value; }
        }

        public bool Retired
        {
            get { return retired; }
            set { retired = value; }
        }

        public DateTime RetiredOn
        {
            get { return retiredOn; }
            set { retiredOn = value; }
        }

        public Guid RetiredBy
        {
            get { return retiredBy; }
            set { retiredBy = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;

            SqlHelper.Default.ExecuteNonQuery("spOrderQT_InsRec", "@OrderQTId", out returnedValue, parameterValues);

            orderQTId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();

            SqlHelper.Default.ExecuteNonQuery("spOrderQT_UpdRec", parameterValues);
        }

        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[37];
            prams[0] = GetSqlParameter("@OrderQTId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.OrderQTId);
            prams[1] = GetSqlParameter("@QTNumber", ParameterDirection.Input, SqlDbType.VarChar, 10, this.QTNumber);
            prams[2] = GetSqlParameter("@QTDate", ParameterDirection.Input, SqlDbType.DateTime, 8, this.QTDate);
            prams[3] = GetSqlParameter("@CustomerId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.CustomerId);
            prams[4] = GetSqlParameter("@StaffId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.StaffId);
            prams[5] = GetSqlParameter("@PriceMethod", ParameterDirection.Input, SqlDbType.Int, 4, this.PriceMethod);
            prams[6] = GetSqlParameter("@FCLFactor", ParameterDirection.Input, SqlDbType.Decimal, 9, this.FCLFactor);
            prams[7] = GetSqlParameter("@LCLFactor", ParameterDirection.Input, SqlDbType.Decimal, 9, this.LCLFactor);
            prams[8] = GetSqlParameter("@Unit", ParameterDirection.Input, SqlDbType.NVarChar, 6, this.Unit);
            prams[9] = GetSqlParameter("@Measurement", ParameterDirection.Input, SqlDbType.NVarChar, 10, this.Measurement);
            prams[10] = GetSqlParameter("@SampleQty", ParameterDirection.Input, SqlDbType.Decimal, 5, this.SampleQty);
            prams[11] = GetSqlParameter("@InputMask", ParameterDirection.Input, SqlDbType.Int, 4, this.InputMask);
            prams[12] = GetSqlParameter("@CurrencyId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.CurrencyId);
            prams[13] = GetSqlParameter("@ExchangeRate", ParameterDirection.Input, SqlDbType.Decimal, 9, this.ExchangeRate);
            prams[14] = GetSqlParameter("@TermsId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.TermsId);
            prams[15] = GetSqlParameter("@Repayment", ParameterDirection.Input, SqlDbType.Decimal, 9, this.Repayment);
            prams[16] = GetSqlParameter("@SendFrom", ParameterDirection.Input, SqlDbType.NVarChar, 16, this.SendFrom);
            prams[17] = GetSqlParameter("@SendTo", ParameterDirection.Input, SqlDbType.NVarChar, 16, this.SendTo);
            prams[18] = GetSqlParameter("@TotalQty", ParameterDirection.Input, SqlDbType.Decimal, 9, this.TotalQty);
            prams[19] = GetSqlParameter("@TotalQtyIN", ParameterDirection.Input, SqlDbType.Decimal, 9, this.TotalQtyIN);
            prams[20] = GetSqlParameter("@TotalQtyOUT", ParameterDirection.Input, SqlDbType.Decimal, 9, this.TotalQtyOUT);
            prams[21] = GetSqlParameter("@TotalAmount", ParameterDirection.Input, SqlDbType.Money, 8, this.TotalAmount);
            prams[22] = GetSqlParameter("@Remarks", ParameterDirection.Input, SqlDbType.NVarChar, 255, this.Remarks);
            prams[23] = GetSqlParameter("@Remarks2", ParameterDirection.Input, SqlDbType.NVarChar, 255, this.Remarks2);
            prams[24] = GetSqlParameter("@Remarks3", ParameterDirection.Input, SqlDbType.NVarChar, 255, this.Remarks3);
            prams[25] = GetSqlParameter("@Revision", ParameterDirection.Input, SqlDbType.Int, 4, this.Revision);
            prams[26] = GetSqlParameter("@InUse", ParameterDirection.Input, SqlDbType.Bit, 1, this.InUse);
            prams[27] = GetSqlParameter("@Status", ParameterDirection.Input, SqlDbType.Int, 4, this.Status);
            prams[28] = GetSqlParameter("@CreatedOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.CreatedOn);
            prams[29] = GetSqlParameter("@CreatedBy", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.CreatedBy);
            prams[30] = GetSqlParameter("@ModifiedOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.ModifiedOn);
            prams[31] = GetSqlParameter("@ModifiedBy", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.ModifiedBy);
            prams[32] = GetSqlParameter("@AccessedOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.AccessedOn);
            prams[33] = GetSqlParameter("@AccessedBy", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.AccessedBy);
            prams[34] = GetSqlParameter("@Retired", ParameterDirection.Input, SqlDbType.Bit, 1, this.Retired);
            prams[35] = GetSqlParameter("@RetiredOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.RetiredOn);
            prams[36] = GetSqlParameter("@RetiredBy", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.RetiredBy);
            return prams;
        }

        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }

        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[]
            {
                GetSqlParameterWithoutDirection("@OrderQTId", SqlDbType.UniqueIdentifier, 16, this.OrderQTId),
                GetSqlParameterWithoutDirection("@QTNumber", SqlDbType.VarChar, 10, this.QTNumber),
                GetSqlParameterWithoutDirection("@QTDate", SqlDbType.DateTime, 8, this.QTDate),
                GetSqlParameterWithoutDirection("@CustomerId", SqlDbType.UniqueIdentifier, 16, this.CustomerId),
                GetSqlParameterWithoutDirection("@StaffId", SqlDbType.UniqueIdentifier, 16, this.StaffId),
                GetSqlParameterWithoutDirection("@PriceMethod", SqlDbType.Int, 4, this.PriceMethod),
                GetSqlParameterWithoutDirection("@FCLFactor", SqlDbType.Decimal, 9, this.FCLFactor),
                GetSqlParameterWithoutDirection("@LCLFactor", SqlDbType.Decimal, 9, this.LCLFactor),
                GetSqlParameterWithoutDirection("@Unit", SqlDbType.NVarChar, 6, this.Unit),
                GetSqlParameterWithoutDirection("@Measurement", SqlDbType.NVarChar, 10, this.Measurement),
                GetSqlParameterWithoutDirection("@SampleQty", SqlDbType.Decimal, 5, this.SampleQty),
                GetSqlParameterWithoutDirection("@InputMask", SqlDbType.Int, 4, this.InputMask),
                GetSqlParameterWithoutDirection("@CurrencyId", SqlDbType.UniqueIdentifier, 16, this.CurrencyId),
                GetSqlParameterWithoutDirection("@ExchangeRate", SqlDbType.Decimal, 9, this.ExchangeRate),
                GetSqlParameterWithoutDirection("@TermsId", SqlDbType.UniqueIdentifier, 16, this.TermsId),
                GetSqlParameterWithoutDirection("@Repayment", SqlDbType.Decimal, 9, this.Repayment),
                GetSqlParameterWithoutDirection("@SendFrom", SqlDbType.NVarChar, 16, this.SendFrom),
                GetSqlParameterWithoutDirection("@SendTo", SqlDbType.NVarChar, 16, this.SendTo),
                GetSqlParameterWithoutDirection("@TotalQty", SqlDbType.Decimal, 9, this.TotalQty),
                GetSqlParameterWithoutDirection("@TotalQtyIN", SqlDbType.Decimal, 9, this.TotalQtyIN),
                GetSqlParameterWithoutDirection("@TotalQtyOUT", SqlDbType.Decimal, 9, this.TotalQtyOUT),
                GetSqlParameterWithoutDirection("@TotalAmount", SqlDbType.Money, 8, this.TotalAmount),
                GetSqlParameterWithoutDirection("@Remarks", SqlDbType.NVarChar, 255, this.Remarks),
                GetSqlParameterWithoutDirection("@Remarks2", SqlDbType.NVarChar, 255, this.Remarks2),
                GetSqlParameterWithoutDirection("@Remarks3", SqlDbType.NVarChar, 255, this.Remarks3),
                GetSqlParameterWithoutDirection("@Revision", SqlDbType.Int, 4, this.Revision),
                GetSqlParameterWithoutDirection("@InUse", SqlDbType.Bit, 1, this.InUse),
                GetSqlParameterWithoutDirection("@Status", SqlDbType.Int, 4, this.Status),
                GetSqlParameterWithoutDirection("@CreatedOn", SqlDbType.DateTime, 8, this.CreatedOn),
                GetSqlParameterWithoutDirection("@CreatedBy", SqlDbType.UniqueIdentifier, 16, this.CreatedBy),
                GetSqlParameterWithoutDirection("@ModifiedOn", SqlDbType.DateTime, 8, this.ModifiedOn),
                GetSqlParameterWithoutDirection("@ModifiedBy", SqlDbType.UniqueIdentifier, 16, this.ModifiedBy),
                GetSqlParameterWithoutDirection("@AccessedOn", SqlDbType.DateTime, 8, this.AccessedOn),
                GetSqlParameterWithoutDirection("@AccessedBy", SqlDbType.UniqueIdentifier, 16, this.AccessedBy),
                GetSqlParameterWithoutDirection("@Retired", SqlDbType.Bit, 1, this.Retired),
                GetSqlParameterWithoutDirection("@RetiredOn", SqlDbType.DateTime, 8, this.RetiredOn),
                GetSqlParameterWithoutDirection("@RetiredBy", SqlDbType.UniqueIdentifier, 16, this.RetiredBy)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("orderQTId: " + orderQTId.ToString()).Append("\r\n");
            builder.Append("qTNumber: " + qTNumber.ToString()).Append("\r\n");
            builder.Append("qTDate: " + qTDate.ToString()).Append("\r\n");
            builder.Append("customerId: " + customerId.ToString()).Append("\r\n");
            builder.Append("staffId: " + staffId.ToString()).Append("\r\n");
            builder.Append("priceMethod: " + priceMethod.ToString()).Append("\r\n");
            builder.Append("fCLFactor: " + fCLFactor.ToString()).Append("\r\n");
            builder.Append("lCLFactor: " + lCLFactor.ToString()).Append("\r\n");
            builder.Append("unit: " + unit.ToString()).Append("\r\n");
            builder.Append("measurement: " + measurement.ToString()).Append("\r\n");
            builder.Append("sampleQty: " + sampleQty.ToString()).Append("\r\n");
            builder.Append("inputMask: " + inputMask.ToString()).Append("\r\n");
            builder.Append("currencyId: " + currencyId.ToString()).Append("\r\n");
            builder.Append("exchangeRate: " + exchangeRate.ToString()).Append("\r\n");
            builder.Append("termsId: " + termsId.ToString()).Append("\r\n");
            builder.Append("repayment: " + repayment.ToString()).Append("\r\n");
            builder.Append("sendFrom: " + sendFrom.ToString()).Append("\r\n");
            builder.Append("sendTo: " + sendTo.ToString()).Append("\r\n");
            builder.Append("totalQty: " + totalQty.ToString()).Append("\r\n");
            builder.Append("totalQtyIN: " + totalQtyIN.ToString()).Append("\r\n");
            builder.Append("totalQtyOUT: " + totalQtyOUT.ToString()).Append("\r\n");
            builder.Append("totalAmount: " + totalAmount.ToString()).Append("\r\n");
            builder.Append("remarks: " + remarks.ToString()).Append("\r\n");
            builder.Append("remarks2: " + remarks2.ToString()).Append("\r\n");
            builder.Append("remarks3: " + remarks3.ToString()).Append("\r\n");
            builder.Append("revision: " + revision.ToString()).Append("\r\n");
            builder.Append("inUse: " + inUse.ToString()).Append("\r\n");
            builder.Append("status: " + status.ToString()).Append("\r\n");
            builder.Append("createdOn: " + createdOn.ToString()).Append("\r\n");
            builder.Append("createdBy: " + createdBy.ToString()).Append("\r\n");
            builder.Append("modifiedOn: " + modifiedOn.ToString()).Append("\r\n");
            builder.Append("modifiedBy: " + modifiedBy.ToString()).Append("\r\n");
            builder.Append("accessedOn: " + accessedOn.ToString()).Append("\r\n");
            builder.Append("accessedBy: " + accessedBy.ToString()).Append("\r\n");
            builder.Append("retired: " + retired.ToString()).Append("\r\n");
            builder.Append("retiredOn: " + retiredOn.ToString()).Append("\r\n");
            builder.Append("retiredBy: " + retiredBy.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }

        #region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            string[] textField = { TextField };
            LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            if (SwitchLocale)
            {
                TextField = GetSwitchLocale(TextField);
            }
            ddList.Items.Clear();

            OrderQTCollection source;

            if (OrderBy == null || OrderBy.Length == 0)
            {
                OrderBy = TextField;
            }
            // Filter the retired records
            if (WhereClause.Length > 0)
            {
                WhereClause += " AND Retired = 0";
            }
            else
            {
                WhereClause = "Retired = 0";
            }

            if (WhereClause.Length > 0)
            {
                source = OrderQT.LoadCollection(WhereClause, OrderBy, true);
            }
            else
            {
                source = OrderQT.LoadCollection(OrderBy, true);
            }

            Common.ComboList sourceList = new Common.ComboList();

            if (BlankLine)
            {
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
            }

            foreach (OrderQT item in source)
            {
                bool filter = false;
                if (ParentFilter.Trim() != String.Empty)
                {
                    filter = true;
                    if (item.CustomerId != Guid.Empty)
                    {
                        filter = IgnorThis(item, ParentFilter);
                    }
                }
                if (!(filter))
                {
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.OrderQTId));
                }
            }

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";

            if (ddList.Items.Count > 0)
            {
                ddList.SelectedIndex = 0;
            }
        }

        #endregion


        private static bool IgnorThis(OrderQT target, string parentFilter)
        {
            bool result = true;
            parentFilter = parentFilter.Replace(" ", "");       // remove spaces
            parentFilter = parentFilter.Replace("'", "");       // remove '
            string[] parsed = parentFilter.Split('=');          // parse

            if (target.CustomerId == Guid.Empty)
            {
                PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
                string filterField = (string)pi.GetValue(target, null);
                if (filterField.ToLower() == parsed[1].ToLower())
                {
                    result = false;
                }
            }
            else
            {
                OrderQT parentTemplate = OrderQT.Load(target.CustomerId);
                result = IgnorThis(parentTemplate, parentFilter);
            }
            return result;
        }

        private static string GetFormatedText(OrderQT target, string[] textField, string textFormatString)
        {
            for (int i = 0; i < textField.Length; i++)
            {
                PropertyInfo pi = target.GetType().GetProperty(textField[i]);
                textFormatString = textFormatString.Replace("{" + i.ToString() + "}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
            }
            return textFormatString;
        }

        private static string[] GetSwitchLocale(string[] source)
        {
            switch (Common.Config.CurrentLanguageId)
            {
                case 2:
                    source[source.Length - 1] += "_Chs";
                    break;
                case 3:
                    source[source.Length - 1] += "_Cht";
                    break;
            }
            return source;
        }
    }


    /// <summary>
    /// Represents a collection of <see cref="OrderQT">OrderQT</see> objects.
    /// </summary>
    public class OrderQTCollection : BindingList<OrderQT>
    {
    }
}
