using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace xPort5.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.OrderQTSupplier.
    /// Date Created:   2020-03-02 02:21:42
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class OrderQTSupplier
    {
        private Guid key = Guid.Empty;
        private Guid orderQtSupplierId = Guid.Empty;
        private Guid orderQTItemId = Guid.Empty;
        private string suppRef = String.Empty;
        private Guid currencyId = Guid.Empty;
        private decimal fCLCost;
        private decimal lCLCost;
        private decimal unitCost;

        /// <summary>
        /// Initialize an new empty OrderQTSupplier object.
        /// </summary>
        public OrderQTSupplier()
        {
        }

        /// <summary>
        /// Initialize a new OrderQTSupplier object with the given parameters.
        /// </summary>
        public OrderQTSupplier(Guid orderQtSupplierId, Guid orderQTItemId, string suppRef, Guid currencyId, decimal fCLCost, decimal lCLCost, decimal unitCost)
        {
            this.orderQtSupplierId = orderQtSupplierId;
            this.orderQTItemId = orderQTItemId;
            this.suppRef = suppRef;
            this.currencyId = currencyId;
            this.fCLCost = fCLCost;
            this.lCLCost = lCLCost;
            this.unitCost = unitCost;
        }

        /// <summary>
        /// Loads a OrderQTSupplier object from the database using the given OrderQtSupplierId
        /// </summary>
        /// <param name="orderQtSupplierId">The primary key value</param>
        /// <returns>A OrderQTSupplier object</returns>
        public static OrderQTSupplier Load(Guid orderQtSupplierId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@OrderQtSupplierId", orderQtSupplierId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spOrderQTSupplier_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    OrderQTSupplier result = new OrderQTSupplier();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a OrderQTSupplier object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A OrderQTSupplier object</returns>
        public static OrderQTSupplier LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spOrderQTSupplier_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    OrderQTSupplier result = new OrderQTSupplier();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a collection of OrderQTSupplier objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the OrderQTSupplier objects in the database.</returns>
        public static OrderQTSupplierCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] { };
            return LoadCollection("spOrderQTSupplier_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderQTSupplier objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the OrderQTSupplier objects in the database ordered by the columns specified.</returns>
        public static OrderQTSupplierCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spOrderQTSupplier_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderQTSupplier objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the OrderQTSupplier objects in the database.</returns>
        public static OrderQTSupplierCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spOrderQTSupplier_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderQTSupplier objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the OrderQTSupplier objects in the database ordered by the columns specified.</returns>
        public static OrderQTSupplierCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spOrderQTSupplier_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderQTSupplier objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the OrderQTSupplier objects in the database.</returns>
        public static OrderQTSupplierCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            OrderQTSupplierCollection result = new OrderQTSupplierCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    OrderQTSupplier tmp = new OrderQTSupplier();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a OrderQTSupplier object from the database.
        /// </summary>
        /// <param name="orderQtSupplierId">The primary key value</param>
        public static void Delete(Guid orderQtSupplierId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@OrderQtSupplierId", orderQtSupplierId) };
            SqlHelper.Default.ExecuteNonQuery("spOrderQTSupplier_DelRec", parameterValues);
        }


        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) orderQtSupplierId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) orderQTItemId = reader.GetGuid(1);
                if (!reader.IsDBNull(2)) suppRef = reader.GetString(2);
                if (!reader.IsDBNull(3)) currencyId = reader.GetGuid(3);
                if (!reader.IsDBNull(4)) fCLCost = reader.GetDecimal(4);
                if (!reader.IsDBNull(5)) lCLCost = reader.GetDecimal(5);
                if (!reader.IsDBNull(6)) unitCost = reader.GetDecimal(6);
            }
        }

        public void Delete()
        {
            Delete(this.OrderQtSupplierId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != OrderQtSupplierId)
                    this.Delete();
                Update();
            }
        }

        public Guid OrderQtSupplierId
        {
            get { return orderQtSupplierId; }
            set { orderQtSupplierId = value; }
        }

        public Guid OrderQTItemId
        {
            get { return orderQTItemId; }
            set { orderQTItemId = value; }
        }

        public string SuppRef
        {
            get { return suppRef; }
            set { suppRef = value; }
        }

        public Guid CurrencyId
        {
            get { return currencyId; }
            set { currencyId = value; }
        }

        public decimal FCLCost
        {
            get { return fCLCost; }
            set { fCLCost = value; }
        }

        public decimal LCLCost
        {
            get { return lCLCost; }
            set { lCLCost = value; }
        }

        public decimal UnitCost
        {
            get { return unitCost; }
            set { unitCost = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;

            SqlHelper.Default.ExecuteNonQuery("spOrderQTSupplier_InsRec", "@OrderQtSupplierId", out returnedValue, parameterValues);

            orderQtSupplierId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();

            SqlHelper.Default.ExecuteNonQuery("spOrderQTSupplier_UpdRec", parameterValues);
        }

        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[7];
            prams[0] = GetSqlParameter("@OrderQtSupplierId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.OrderQtSupplierId);
            prams[1] = GetSqlParameter("@OrderQTItemId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.OrderQTItemId);
            prams[2] = GetSqlParameter("@SuppRef", ParameterDirection.Input, SqlDbType.NVarChar, 32, this.SuppRef);
            prams[3] = GetSqlParameter("@CurrencyId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.CurrencyId);
            prams[4] = GetSqlParameter("@FCLCost", ParameterDirection.Input, SqlDbType.Decimal, 9, this.FCLCost);
            prams[5] = GetSqlParameter("@LCLCost", ParameterDirection.Input, SqlDbType.Decimal, 9, this.LCLCost);
            prams[6] = GetSqlParameter("@UnitCost", ParameterDirection.Input, SqlDbType.Decimal, 9, this.UnitCost);
            return prams;
        }

        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }

        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[]
            {
                GetSqlParameterWithoutDirection("@OrderQtSupplierId", SqlDbType.UniqueIdentifier, 16, this.OrderQtSupplierId),
                GetSqlParameterWithoutDirection("@OrderQTItemId", SqlDbType.UniqueIdentifier, 16, this.OrderQTItemId),
                GetSqlParameterWithoutDirection("@SuppRef", SqlDbType.NVarChar, 32, this.SuppRef),
                GetSqlParameterWithoutDirection("@CurrencyId", SqlDbType.UniqueIdentifier, 16, this.CurrencyId),
                GetSqlParameterWithoutDirection("@FCLCost", SqlDbType.Decimal, 9, this.FCLCost),
                GetSqlParameterWithoutDirection("@LCLCost", SqlDbType.Decimal, 9, this.LCLCost),
                GetSqlParameterWithoutDirection("@UnitCost", SqlDbType.Decimal, 9, this.UnitCost)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("orderQtSupplierId: " + orderQtSupplierId.ToString()).Append("\r\n");
            builder.Append("orderQTItemId: " + orderQTItemId.ToString()).Append("\r\n");
            builder.Append("suppRef: " + suppRef.ToString()).Append("\r\n");
            builder.Append("currencyId: " + currencyId.ToString()).Append("\r\n");
            builder.Append("fCLCost: " + fCLCost.ToString()).Append("\r\n");
            builder.Append("lCLCost: " + lCLCost.ToString()).Append("\r\n");
            builder.Append("unitCost: " + unitCost.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }

        #region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            string[] textField = { TextField };
            LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            if (SwitchLocale)
            {
                TextField = GetSwitchLocale(TextField);
            }
            ddList.Items.Clear();

            OrderQTSupplierCollection source;

            if (OrderBy == null || OrderBy.Length == 0)
            {
                OrderBy = TextField;
            }

            if (WhereClause.Length > 0)
            {
                source = OrderQTSupplier.LoadCollection(WhereClause, OrderBy, true);
            }
            else
            {
                source = OrderQTSupplier.LoadCollection(OrderBy, true);
            }

            Common.ComboList sourceList = new Common.ComboList();

            if (BlankLine)
            {
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
            }

            foreach (OrderQTSupplier item in source)
            {
                bool filter = false;
                if (ParentFilter.Trim() != String.Empty)
                {
                    filter = true;
                    if (item.OrderQTItemId != Guid.Empty)
                    {
                        filter = IgnorThis(item, ParentFilter);
                    }
                }
                if (!(filter))
                {
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.OrderQtSupplierId));
                }
            }

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";

            if (ddList.Items.Count > 0)
            {
                ddList.SelectedIndex = 0;
            }
        }

        #endregion


        private static bool IgnorThis(OrderQTSupplier target, string parentFilter)
        {
            bool result = true;
            parentFilter = parentFilter.Replace(" ", "");       // remove spaces
            parentFilter = parentFilter.Replace("'", "");       // remove '
            string[] parsed = parentFilter.Split('=');          // parse

            if (target.OrderQTItemId == Guid.Empty)
            {
                PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
                string filterField = (string)pi.GetValue(target, null);
                if (filterField.ToLower() == parsed[1].ToLower())
                {
                    result = false;
                }
            }
            else
            {
                OrderQTSupplier parentTemplate = OrderQTSupplier.Load(target.OrderQTItemId);
                result = IgnorThis(parentTemplate, parentFilter);
            }
            return result;
        }

        private static string GetFormatedText(OrderQTSupplier target, string[] textField, string textFormatString)
        {
            for (int i = 0; i < textField.Length; i++)
            {
                PropertyInfo pi = target.GetType().GetProperty(textField[i]);
                textFormatString = textFormatString.Replace("{" + i.ToString() + "}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
            }
            return textFormatString;
        }

        private static string[] GetSwitchLocale(string[] source)
        {
            switch (Common.Config.CurrentLanguageId)
            {
                case 2:
                    source[source.Length - 1] += "_Chs";
                    break;
                case 3:
                    source[source.Length - 1] += "_Cht";
                    break;
            }
            return source;
        }
    }


    /// <summary>
    /// Represents a collection of <see cref="OrderQTSupplier">OrderQTSupplier</see> objects.
    /// </summary>
    public class OrderQTSupplierCollection : BindingList<OrderQTSupplier>
    {
    }
}
