using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace xPort5.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.OrderQTCustShipping.
    /// Date Created:   2020-03-02 02:20:32
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class OrderQTCustShipping
    {
        private Guid key = Guid.Empty;
        private Guid orderQTCustShippingId = Guid.Empty;
        private Guid orderQTItemId = Guid.Empty;
        private DateTime shippedOn = DateTime.Parse("1900-1-1");
        private decimal qtyOrdered;
        private decimal qtyShipped;
        private int status = 0;

        /// <summary>
        /// Initialize an new empty OrderQTCustShipping object.
        /// </summary>
        public OrderQTCustShipping()
        {
        }

        /// <summary>
        /// Initialize a new OrderQTCustShipping object with the given parameters.
        /// </summary>
        public OrderQTCustShipping(Guid orderQTCustShippingId, Guid orderQTItemId, DateTime shippedOn, decimal qtyOrdered, decimal qtyShipped, int status)
        {
            this.orderQTCustShippingId = orderQTCustShippingId;
            this.orderQTItemId = orderQTItemId;
            this.shippedOn = shippedOn;
            this.qtyOrdered = qtyOrdered;
            this.qtyShipped = qtyShipped;
            this.status = status;
        }

        /// <summary>
        /// Loads a OrderQTCustShipping object from the database using the given OrderQTCustShippingId
        /// </summary>
        /// <param name="orderQTCustShippingId">The primary key value</param>
        /// <returns>A OrderQTCustShipping object</returns>
        public static OrderQTCustShipping Load(Guid orderQTCustShippingId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@OrderQTCustShippingId", orderQTCustShippingId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spOrderQTCustShipping_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    OrderQTCustShipping result = new OrderQTCustShipping();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a OrderQTCustShipping object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A OrderQTCustShipping object</returns>
        public static OrderQTCustShipping LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spOrderQTCustShipping_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    OrderQTCustShipping result = new OrderQTCustShipping();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a collection of OrderQTCustShipping objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the OrderQTCustShipping objects in the database.</returns>
        public static OrderQTCustShippingCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] { };
            return LoadCollection("spOrderQTCustShipping_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderQTCustShipping objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the OrderQTCustShipping objects in the database ordered by the columns specified.</returns>
        public static OrderQTCustShippingCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spOrderQTCustShipping_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderQTCustShipping objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the OrderQTCustShipping objects in the database.</returns>
        public static OrderQTCustShippingCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spOrderQTCustShipping_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderQTCustShipping objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the OrderQTCustShipping objects in the database ordered by the columns specified.</returns>
        public static OrderQTCustShippingCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spOrderQTCustShipping_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderQTCustShipping objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the OrderQTCustShipping objects in the database.</returns>
        public static OrderQTCustShippingCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            OrderQTCustShippingCollection result = new OrderQTCustShippingCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    OrderQTCustShipping tmp = new OrderQTCustShipping();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a OrderQTCustShipping object from the database.
        /// </summary>
        /// <param name="orderQTCustShippingId">The primary key value</param>
        public static void Delete(Guid orderQTCustShippingId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@OrderQTCustShippingId", orderQTCustShippingId) };
            SqlHelper.Default.ExecuteNonQuery("spOrderQTCustShipping_DelRec", parameterValues);
        }


        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) orderQTCustShippingId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) orderQTItemId = reader.GetGuid(1);
                if (!reader.IsDBNull(2)) shippedOn = reader.GetDateTime(2);
                if (!reader.IsDBNull(3)) qtyOrdered = reader.GetDecimal(3);
                if (!reader.IsDBNull(4)) qtyShipped = reader.GetDecimal(4);
                if (!reader.IsDBNull(5)) status = reader.GetInt32(5);
            }
        }

        public void Delete()
        {
            Delete(this.OrderQTCustShippingId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != OrderQTCustShippingId)
                    this.Delete();
                Update();
            }
        }

        public Guid OrderQTCustShippingId
        {
            get { return orderQTCustShippingId; }
            set { orderQTCustShippingId = value; }
        }

        public Guid OrderQTItemId
        {
            get { return orderQTItemId; }
            set { orderQTItemId = value; }
        }

        public DateTime ShippedOn
        {
            get { return shippedOn; }
            set { shippedOn = value; }
        }

        public decimal QtyOrdered
        {
            get { return qtyOrdered; }
            set { qtyOrdered = value; }
        }

        public decimal QtyShipped
        {
            get { return qtyShipped; }
            set { qtyShipped = value; }
        }

        public int Status
        {
            get { return status; }
            set { status = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;

            SqlHelper.Default.ExecuteNonQuery("spOrderQTCustShipping_InsRec", "@OrderQTCustShippingId", out returnedValue, parameterValues);

            orderQTCustShippingId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();

            SqlHelper.Default.ExecuteNonQuery("spOrderQTCustShipping_UpdRec", parameterValues);
        }

        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[6];
            prams[0] = GetSqlParameter("@OrderQTCustShippingId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.OrderQTCustShippingId);
            prams[1] = GetSqlParameter("@OrderQTItemId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.OrderQTItemId);
            prams[2] = GetSqlParameter("@ShippedOn", ParameterDirection.Input, SqlDbType.DateTime, 8, this.ShippedOn);
            prams[3] = GetSqlParameter("@QtyOrdered", ParameterDirection.Input, SqlDbType.Decimal, 9, this.QtyOrdered);
            prams[4] = GetSqlParameter("@QtyShipped", ParameterDirection.Input, SqlDbType.Decimal, 9, this.QtyShipped);
            prams[5] = GetSqlParameter("@Status", ParameterDirection.Input, SqlDbType.Int, 4, this.Status);
            return prams;
        }

        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }

        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[]
            {
                GetSqlParameterWithoutDirection("@OrderQTCustShippingId", SqlDbType.UniqueIdentifier, 16, this.OrderQTCustShippingId),
                GetSqlParameterWithoutDirection("@OrderQTItemId", SqlDbType.UniqueIdentifier, 16, this.OrderQTItemId),
                GetSqlParameterWithoutDirection("@ShippedOn", SqlDbType.DateTime, 8, this.ShippedOn),
                GetSqlParameterWithoutDirection("@QtyOrdered", SqlDbType.Decimal, 9, this.QtyOrdered),
                GetSqlParameterWithoutDirection("@QtyShipped", SqlDbType.Decimal, 9, this.QtyShipped),
                GetSqlParameterWithoutDirection("@Status", SqlDbType.Int, 4, this.Status)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("orderQTCustShippingId: " + orderQTCustShippingId.ToString()).Append("\r\n");
            builder.Append("orderQTItemId: " + orderQTItemId.ToString()).Append("\r\n");
            builder.Append("shippedOn: " + shippedOn.ToString()).Append("\r\n");
            builder.Append("qtyOrdered: " + qtyOrdered.ToString()).Append("\r\n");
            builder.Append("qtyShipped: " + qtyShipped.ToString()).Append("\r\n");
            builder.Append("status: " + status.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }

        #region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            string[] textField = { TextField };
            LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            if (SwitchLocale)
            {
                TextField = GetSwitchLocale(TextField);
            }
            ddList.Items.Clear();

            OrderQTCustShippingCollection source;

            if (OrderBy == null || OrderBy.Length == 0)
            {
                OrderBy = TextField;
            }

            if (WhereClause.Length > 0)
            {
                source = OrderQTCustShipping.LoadCollection(WhereClause, OrderBy, true);
            }
            else
            {
                source = OrderQTCustShipping.LoadCollection(OrderBy, true);
            }

            Common.ComboList sourceList = new Common.ComboList();

            if (BlankLine)
            {
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
            }

            foreach (OrderQTCustShipping item in source)
            {
                bool filter = false;
                if (ParentFilter.Trim() != String.Empty)
                {
                    filter = true;
                    if (item.OrderQTItemId != Guid.Empty)
                    {
                        filter = IgnorThis(item, ParentFilter);
                    }
                }
                if (!(filter))
                {
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.OrderQTCustShippingId));
                }
            }

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";

            if (ddList.Items.Count > 0)
            {
                ddList.SelectedIndex = 0;
            }
        }

        #endregion


        private static bool IgnorThis(OrderQTCustShipping target, string parentFilter)
        {
            bool result = true;
            parentFilter = parentFilter.Replace(" ", "");       // remove spaces
            parentFilter = parentFilter.Replace("'", "");       // remove '
            string[] parsed = parentFilter.Split('=');          // parse

            if (target.OrderQTItemId == Guid.Empty)
            {
                PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
                string filterField = (string)pi.GetValue(target, null);
                if (filterField.ToLower() == parsed[1].ToLower())
                {
                    result = false;
                }
            }
            else
            {
                OrderQTCustShipping parentTemplate = OrderQTCustShipping.Load(target.OrderQTItemId);
                result = IgnorThis(parentTemplate, parentFilter);
            }
            return result;
        }

        private static string GetFormatedText(OrderQTCustShipping target, string[] textField, string textFormatString)
        {
            for (int i = 0; i < textField.Length; i++)
            {
                PropertyInfo pi = target.GetType().GetProperty(textField[i]);
                textFormatString = textFormatString.Replace("{" + i.ToString() + "}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
            }
            return textFormatString;
        }

        private static string[] GetSwitchLocale(string[] source)
        {
            switch (Common.Config.CurrentLanguageId)
            {
                case 2:
                    source[source.Length - 1] += "_Chs";
                    break;
                case 3:
                    source[source.Length - 1] += "_Cht";
                    break;
            }
            return source;
        }
    }


    /// <summary>
    /// Represents a collection of <see cref="OrderQTCustShipping">OrderQTCustShipping</see> objects.
    /// </summary>
    public class OrderQTCustShippingCollection : BindingList<OrderQTCustShipping>
    {
    }
}
