using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace xPort5.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.T_BarCode.
    /// Date Created:   2020-03-02 02:42:43
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class T_BarCode
    {
        private Guid key = Guid.Empty;
        private Guid barcodeId = Guid.Empty;
        private string barcodeCode = String.Empty;
        private string barcodeName = String.Empty;
        private string barcodeName_Chs = String.Empty;
        private string barcodeName_Cht = String.Empty;
        private string barcodeType = String.Empty;

        /// <summary>
        /// Initialize an new empty T_BarCode object.
        /// </summary>
        public T_BarCode()
        {
        }

        /// <summary>
        /// Initialize a new T_BarCode object with the given parameters.
        /// </summary>
        public T_BarCode(Guid barcodeId, string barcodeCode, string barcodeName, string barcodeName_Chs, string barcodeName_Cht, string barcodeType)
        {
            this.barcodeId = barcodeId;
            this.barcodeCode = barcodeCode;
            this.barcodeName = barcodeName;
            this.barcodeName_Chs = barcodeName_Chs;
            this.barcodeName_Cht = barcodeName_Cht;
            this.barcodeType = barcodeType;
        }

        /// <summary>
        /// Loads a T_BarCode object from the database using the given BarcodeId
        /// </summary>
        /// <param name="barcodeId">The primary key value</param>
        /// <returns>A T_BarCode object</returns>
        public static T_BarCode Load(Guid barcodeId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@BarcodeId", barcodeId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spT_BarCode_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    T_BarCode result = new T_BarCode();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a T_BarCode object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A T_BarCode object</returns>
        public static T_BarCode LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spT_BarCode_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    T_BarCode result = new T_BarCode();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a collection of T_BarCode objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_BarCode objects in the database.</returns>
        public static T_BarCodeCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] { };
            return LoadCollection("spT_BarCode_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_BarCode objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the T_BarCode objects in the database ordered by the columns specified.</returns>
        public static T_BarCodeCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spT_BarCode_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_BarCode objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_BarCode objects in the database.</returns>
        public static T_BarCodeCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spT_BarCode_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_BarCode objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the T_BarCode objects in the database ordered by the columns specified.</returns>
        public static T_BarCodeCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spT_BarCode_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_BarCode objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_BarCode objects in the database.</returns>
        public static T_BarCodeCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            T_BarCodeCollection result = new T_BarCodeCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    T_BarCode tmp = new T_BarCode();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a T_BarCode object from the database.
        /// </summary>
        /// <param name="barcodeId">The primary key value</param>
        public static void Delete(Guid barcodeId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@BarcodeId", barcodeId) };
            SqlHelper.Default.ExecuteNonQuery("spT_BarCode_DelRec", parameterValues);
        }


        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) barcodeId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) barcodeCode = reader.GetString(1);
                if (!reader.IsDBNull(2)) barcodeName = reader.GetString(2);
                if (!reader.IsDBNull(3)) barcodeName_Chs = reader.GetString(3);
                if (!reader.IsDBNull(4)) barcodeName_Cht = reader.GetString(4);
                if (!reader.IsDBNull(5)) barcodeType = reader.GetString(5);
            }
        }

        public void Delete()
        {
            Delete(this.BarcodeId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != BarcodeId)
                    this.Delete();
                Update();
            }
        }

        public Guid BarcodeId
        {
            get { return barcodeId; }
            set { barcodeId = value; }
        }

        public string BarcodeCode
        {
            get { return barcodeCode; }
            set { barcodeCode = value; }
        }

        public string BarcodeName
        {
            get { return barcodeName; }
            set { barcodeName = value; }
        }

        public string BarcodeName_Chs
        {
            get { return barcodeName_Chs; }
            set { barcodeName_Chs = value; }
        }

        public string BarcodeName_Cht
        {
            get { return barcodeName_Cht; }
            set { barcodeName_Cht = value; }
        }

        public string BarcodeType
        {
            get { return barcodeType; }
            set { barcodeType = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;

            SqlHelper.Default.ExecuteNonQuery("spT_BarCode_InsRec", "@BarcodeId", out returnedValue, parameterValues);

            barcodeId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();

            SqlHelper.Default.ExecuteNonQuery("spT_BarCode_UpdRec", parameterValues);
        }

        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[6];
            prams[0] = GetSqlParameter("@BarcodeId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.BarcodeId);
            prams[1] = GetSqlParameter("@BarcodeCode", ParameterDirection.Input, SqlDbType.VarChar, 32, this.BarcodeCode);
            prams[2] = GetSqlParameter("@BarcodeName", ParameterDirection.Input, SqlDbType.NVarChar, 255, this.BarcodeName);
            prams[3] = GetSqlParameter("@BarcodeName_Chs", ParameterDirection.Input, SqlDbType.NVarChar, 255, this.BarcodeName_Chs);
            prams[4] = GetSqlParameter("@BarcodeName_Cht", ParameterDirection.Input, SqlDbType.NVarChar, 255, this.BarcodeName_Cht);
            prams[5] = GetSqlParameter("@BarcodeType", ParameterDirection.Input, SqlDbType.NVarChar, 32, this.BarcodeType);
            return prams;
        }

        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }

        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[]
            {
                GetSqlParameterWithoutDirection("@BarcodeId", SqlDbType.UniqueIdentifier, 16, this.BarcodeId),
                GetSqlParameterWithoutDirection("@BarcodeCode", SqlDbType.VarChar, 32, this.BarcodeCode),
                GetSqlParameterWithoutDirection("@BarcodeName", SqlDbType.NVarChar, 255, this.BarcodeName),
                GetSqlParameterWithoutDirection("@BarcodeName_Chs", SqlDbType.NVarChar, 255, this.BarcodeName_Chs),
                GetSqlParameterWithoutDirection("@BarcodeName_Cht", SqlDbType.NVarChar, 255, this.BarcodeName_Cht),
                GetSqlParameterWithoutDirection("@BarcodeType", SqlDbType.NVarChar, 32, this.BarcodeType)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("barcodeId: " + barcodeId.ToString()).Append("\r\n");
            builder.Append("barcodeCode: " + barcodeCode.ToString()).Append("\r\n");
            builder.Append("barcodeName: " + barcodeName.ToString()).Append("\r\n");
            builder.Append("barcodeName_Chs: " + barcodeName_Chs.ToString()).Append("\r\n");
            builder.Append("barcodeName_Cht: " + barcodeName_Cht.ToString()).Append("\r\n");
            builder.Append("barcodeType: " + barcodeType.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }

        #region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            string[] textField = { TextField };
            LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            if (SwitchLocale)
            {
                TextField = GetSwitchLocale(TextField);
            }
            ddList.Items.Clear();

            T_BarCodeCollection source;

            if (OrderBy == null || OrderBy.Length == 0)
            {
                OrderBy = TextField;
            }

            if (WhereClause.Length > 0)
            {
                source = T_BarCode.LoadCollection(WhereClause, OrderBy, true);
            }
            else
            {
                source = T_BarCode.LoadCollection(OrderBy, true);
            }

            Common.ComboList sourceList = new Common.ComboList();

            if (BlankLine)
            {
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
            }

            foreach (T_BarCode item in source)
            {
                bool filter = false;
                if (ParentFilter.Trim() != String.Empty)
                {
                    filter = IgnorThis(item, ParentFilter);
                }
                if (!(filter))
                {
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.BarcodeId));
                }
            }

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";

            if (ddList.Items.Count > 0)
            {
                ddList.SelectedIndex = 0;
            }
        }

        #endregion


        private static bool IgnorThis(T_BarCode target, string parentFilter)
        {
            bool result = true;
            parentFilter = parentFilter.Replace(" ", "");       // remove spaces
            parentFilter = parentFilter.Replace("'", "");       // remove '
            string[] parsed = parentFilter.Split('=');          // parse

            PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
            string filterField = (string)pi.GetValue(target, null);
            if (filterField.ToLower() == parsed[1].ToLower())
            {
                result = false;
            }
            return result;
        }

        private static string GetFormatedText(T_BarCode target, string[] textField, string textFormatString)
        {
            for (int i = 0; i < textField.Length; i++)
            {
                PropertyInfo pi = target.GetType().GetProperty(textField[i]);
                textFormatString = textFormatString.Replace("{" + i.ToString() + "}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
            }
            return textFormatString;
        }

        private static string[] GetSwitchLocale(string[] source)
        {
            switch (Common.Config.CurrentLanguageId)
            {
                case 2:
                    source[source.Length - 1] += "_Chs";
                    break;
                case 3:
                    source[source.Length - 1] += "_Cht";
                    break;
            }
            return source;
        }
    }


    /// <summary>
    /// Represents a collection of <see cref="T_BarCode">T_BarCode</see> objects.
    /// </summary>
    public class T_BarCodeCollection : BindingList<T_BarCode>
    {
    }
}
