using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace xPort5.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.T_Category.
    /// Date Created:   2020-03-02 02:42:22
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class T_Category
    {
        private Guid key = Guid.Empty;
        private Guid categoryId = Guid.Empty;
        private Guid deptId = Guid.Empty;
        private Guid classId = Guid.Empty;
        private string categoryCode = String.Empty;
        private string categoryName = String.Empty;
        private string categoryName_Chs = String.Empty;
        private string categoryName_Cht = String.Empty;
        private int costingMethod = 0;
        private int inventoryMethod = 0;
        private string taxMethod = String.Empty;

        /// <summary>
        /// Initialize an new empty T_Category object.
        /// </summary>
        public T_Category()
        {
        }

        /// <summary>
        /// Initialize a new T_Category object with the given parameters.
        /// </summary>
        public T_Category(Guid categoryId, Guid deptId, Guid classId, string categoryCode, string categoryName, string categoryName_Chs, string categoryName_Cht, int costingMethod, int inventoryMethod, string taxMethod)
        {
            this.categoryId = categoryId;
            this.deptId = deptId;
            this.classId = classId;
            this.categoryCode = categoryCode;
            this.categoryName = categoryName;
            this.categoryName_Chs = categoryName_Chs;
            this.categoryName_Cht = categoryName_Cht;
            this.costingMethod = costingMethod;
            this.inventoryMethod = inventoryMethod;
            this.taxMethod = taxMethod;
        }

        /// <summary>
        /// Loads a T_Category object from the database using the given CategoryId
        /// </summary>
        /// <param name="categoryId">The primary key value</param>
        /// <returns>A T_Category object</returns>
        public static T_Category Load(Guid categoryId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@CategoryId", categoryId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spT_Category_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    T_Category result = new T_Category();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a T_Category object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A T_Category object</returns>
        public static T_Category LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spT_Category_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    T_Category result = new T_Category();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a collection of T_Category objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_Category objects in the database.</returns>
        public static T_CategoryCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] { };
            return LoadCollection("spT_Category_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_Category objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the T_Category objects in the database ordered by the columns specified.</returns>
        public static T_CategoryCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spT_Category_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_Category objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_Category objects in the database.</returns>
        public static T_CategoryCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spT_Category_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_Category objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the T_Category objects in the database ordered by the columns specified.</returns>
        public static T_CategoryCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spT_Category_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_Category objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_Category objects in the database.</returns>
        public static T_CategoryCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            T_CategoryCollection result = new T_CategoryCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    T_Category tmp = new T_Category();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a T_Category object from the database.
        /// </summary>
        /// <param name="categoryId">The primary key value</param>
        public static void Delete(Guid categoryId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@CategoryId", categoryId) };
            SqlHelper.Default.ExecuteNonQuery("spT_Category_DelRec", parameterValues);
        }


        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) categoryId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) deptId = reader.GetGuid(1);
                if (!reader.IsDBNull(2)) classId = reader.GetGuid(2);
                if (!reader.IsDBNull(3)) categoryCode = reader.GetString(3);
                if (!reader.IsDBNull(4)) categoryName = reader.GetString(4);
                if (!reader.IsDBNull(5)) categoryName_Chs = reader.GetString(5);
                if (!reader.IsDBNull(6)) categoryName_Cht = reader.GetString(6);
                if (!reader.IsDBNull(7)) costingMethod = reader.GetInt32(7);
                if (!reader.IsDBNull(8)) inventoryMethod = reader.GetInt32(8);
                if (!reader.IsDBNull(9)) taxMethod = reader.GetString(9);
            }
        }

        public void Delete()
        {
            Delete(this.CategoryId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != CategoryId)
                    this.Delete();
                Update();
            }
        }

        public Guid CategoryId
        {
            get { return categoryId; }
            set { categoryId = value; }
        }

        public Guid DeptId
        {
            get { return deptId; }
            set { deptId = value; }
        }

        public Guid ClassId
        {
            get { return classId; }
            set { classId = value; }
        }

        public string CategoryCode
        {
            get { return categoryCode; }
            set { categoryCode = value; }
        }

        public string CategoryName
        {
            get { return categoryName; }
            set { categoryName = value; }
        }

        public string CategoryName_Chs
        {
            get { return categoryName_Chs; }
            set { categoryName_Chs = value; }
        }

        public string CategoryName_Cht
        {
            get { return categoryName_Cht; }
            set { categoryName_Cht = value; }
        }

        public int CostingMethod
        {
            get { return costingMethod; }
            set { costingMethod = value; }
        }

        public int InventoryMethod
        {
            get { return inventoryMethod; }
            set { inventoryMethod = value; }
        }

        public string TaxMethod
        {
            get { return taxMethod; }
            set { taxMethod = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;

            SqlHelper.Default.ExecuteNonQuery("spT_Category_InsRec", "@CategoryId", out returnedValue, parameterValues);

            categoryId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();

            SqlHelper.Default.ExecuteNonQuery("spT_Category_UpdRec", parameterValues);
        }

        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[10];
            prams[0] = GetSqlParameter("@CategoryId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.CategoryId);
            prams[1] = GetSqlParameter("@DeptId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.DeptId);
            prams[2] = GetSqlParameter("@ClassId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.ClassId);
            prams[3] = GetSqlParameter("@CategoryCode", ParameterDirection.Input, SqlDbType.VarChar, 3, this.CategoryCode);
            prams[4] = GetSqlParameter("@CategoryName", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.CategoryName);
            prams[5] = GetSqlParameter("@CategoryName_Chs", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.CategoryName_Chs);
            prams[6] = GetSqlParameter("@CategoryName_Cht", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.CategoryName_Cht);
            prams[7] = GetSqlParameter("@CostingMethod", ParameterDirection.Input, SqlDbType.Int, 4, this.CostingMethod);
            prams[8] = GetSqlParameter("@InventoryMethod", ParameterDirection.Input, SqlDbType.Int, 4, this.InventoryMethod);
            prams[9] = GetSqlParameter("@TaxMethod", ParameterDirection.Input, SqlDbType.VarChar, 1, this.TaxMethod);
            return prams;
        }

        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }

        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[]
            {
                GetSqlParameterWithoutDirection("@CategoryId", SqlDbType.UniqueIdentifier, 16, this.CategoryId),
                GetSqlParameterWithoutDirection("@DeptId", SqlDbType.UniqueIdentifier, 16, this.DeptId),
                GetSqlParameterWithoutDirection("@ClassId", SqlDbType.UniqueIdentifier, 16, this.ClassId),
                GetSqlParameterWithoutDirection("@CategoryCode", SqlDbType.VarChar, 3, this.CategoryCode),
                GetSqlParameterWithoutDirection("@CategoryName", SqlDbType.NVarChar, 64, this.CategoryName),
                GetSqlParameterWithoutDirection("@CategoryName_Chs", SqlDbType.NVarChar, 64, this.CategoryName_Chs),
                GetSqlParameterWithoutDirection("@CategoryName_Cht", SqlDbType.NVarChar, 64, this.CategoryName_Cht),
                GetSqlParameterWithoutDirection("@CostingMethod", SqlDbType.Int, 4, this.CostingMethod),
                GetSqlParameterWithoutDirection("@InventoryMethod", SqlDbType.Int, 4, this.InventoryMethod),
                GetSqlParameterWithoutDirection("@TaxMethod", SqlDbType.VarChar, 1, this.TaxMethod)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("categoryId: " + categoryId.ToString()).Append("\r\n");
            builder.Append("deptId: " + deptId.ToString()).Append("\r\n");
            builder.Append("classId: " + classId.ToString()).Append("\r\n");
            builder.Append("categoryCode: " + categoryCode.ToString()).Append("\r\n");
            builder.Append("categoryName: " + categoryName.ToString()).Append("\r\n");
            builder.Append("categoryName_Chs: " + categoryName_Chs.ToString()).Append("\r\n");
            builder.Append("categoryName_Cht: " + categoryName_Cht.ToString()).Append("\r\n");
            builder.Append("costingMethod: " + costingMethod.ToString()).Append("\r\n");
            builder.Append("inventoryMethod: " + inventoryMethod.ToString()).Append("\r\n");
            builder.Append("taxMethod: " + taxMethod.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }

        #region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            string[] textField = { TextField };
            LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            if (SwitchLocale)
            {
                TextField = GetSwitchLocale(TextField);
            }
            ddList.Items.Clear();

            T_CategoryCollection source;

            if (OrderBy == null || OrderBy.Length == 0)
            {
                OrderBy = TextField;
            }

            if (WhereClause.Length > 0)
            {
                source = T_Category.LoadCollection(WhereClause, OrderBy, true);
            }
            else
            {
                source = T_Category.LoadCollection(OrderBy, true);
            }

            Common.ComboList sourceList = new Common.ComboList();

            if (BlankLine)
            {
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
            }

            foreach (T_Category item in source)
            {
                bool filter = false;
                if (ParentFilter.Trim() != String.Empty)
                {
                    filter = true;
                    if (item.DeptId != Guid.Empty)
                    {
                        filter = IgnorThis(item, ParentFilter);
                    }
                }
                if (!(filter))
                {
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.CategoryId));
                }
            }

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";

            if (ddList.Items.Count > 0)
            {
                ddList.SelectedIndex = 0;
            }
        }

        #endregion


        private static bool IgnorThis(T_Category target, string parentFilter)
        {
            bool result = true;
            parentFilter = parentFilter.Replace(" ", "");       // remove spaces
            parentFilter = parentFilter.Replace("'", "");       // remove '
            string[] parsed = parentFilter.Split('=');          // parse

            if (target.DeptId == Guid.Empty)
            {
                PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
                string filterField = (string)pi.GetValue(target, null);
                if (filterField.ToLower() == parsed[1].ToLower())
                {
                    result = false;
                }
            }
            else
            {
                T_Category parentTemplate = T_Category.Load(target.DeptId);
                result = IgnorThis(parentTemplate, parentFilter);
            }
            return result;
        }

        private static string GetFormatedText(T_Category target, string[] textField, string textFormatString)
        {
            for (int i = 0; i < textField.Length; i++)
            {
                PropertyInfo pi = target.GetType().GetProperty(textField[i]);
                textFormatString = textFormatString.Replace("{" + i.ToString() + "}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
            }
            return textFormatString;
        }

        private static string[] GetSwitchLocale(string[] source)
        {
            switch (Common.Config.CurrentLanguageId)
            {
                case 2:
                    source[source.Length - 1] += "_Chs";
                    break;
                case 3:
                    source[source.Length - 1] += "_Cht";
                    break;
            }
            return source;
        }
    }


    /// <summary>
    /// Represents a collection of <see cref="T_Category">T_Category</see> objects.
    /// </summary>
    public class T_CategoryCollection : BindingList<T_Category>
    {
    }
}
