using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace xPort5.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.T_Charge.
    /// Date Created:   2020-03-02 02:42:01
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class T_Charge
    {
        private Guid key = Guid.Empty;
        private Guid chargeId = Guid.Empty;
        private Guid parentCharge = Guid.Empty;
        private string chargeCode = String.Empty;
        private string chargeName = String.Empty;
        private string chargeName_Chs = String.Empty;
        private string chargeName_Cht = String.Empty;
        private string aCCode = String.Empty;
        private string dCCode = String.Empty;

        /// <summary>
        /// Initialize an new empty T_Charge object.
        /// </summary>
        public T_Charge()
        {
        }

        /// <summary>
        /// Initialize a new T_Charge object with the given parameters.
        /// </summary>
        public T_Charge(Guid chargeId, Guid parentCharge, string chargeCode, string chargeName, string chargeName_Chs, string chargeName_Cht, string aCCode, string dCCode)
        {
            this.chargeId = chargeId;
            this.parentCharge = parentCharge;
            this.chargeCode = chargeCode;
            this.chargeName = chargeName;
            this.chargeName_Chs = chargeName_Chs;
            this.chargeName_Cht = chargeName_Cht;
            this.aCCode = aCCode;
            this.dCCode = dCCode;
        }

        /// <summary>
        /// Loads a T_Charge object from the database using the given ChargeId
        /// </summary>
        /// <param name="chargeId">The primary key value</param>
        /// <returns>A T_Charge object</returns>
        public static T_Charge Load(Guid chargeId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@ChargeId", chargeId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spT_Charge_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    T_Charge result = new T_Charge();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a T_Charge object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A T_Charge object</returns>
        public static T_Charge LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spT_Charge_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    T_Charge result = new T_Charge();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a collection of T_Charge objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_Charge objects in the database.</returns>
        public static T_ChargeCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] { };
            return LoadCollection("spT_Charge_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_Charge objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the T_Charge objects in the database ordered by the columns specified.</returns>
        public static T_ChargeCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spT_Charge_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_Charge objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_Charge objects in the database.</returns>
        public static T_ChargeCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spT_Charge_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_Charge objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the T_Charge objects in the database ordered by the columns specified.</returns>
        public static T_ChargeCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spT_Charge_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_Charge objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_Charge objects in the database.</returns>
        public static T_ChargeCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            T_ChargeCollection result = new T_ChargeCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    T_Charge tmp = new T_Charge();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a T_Charge object from the database.
        /// </summary>
        /// <param name="chargeId">The primary key value</param>
        public static void Delete(Guid chargeId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@ChargeId", chargeId) };
            SqlHelper.Default.ExecuteNonQuery("spT_Charge_DelRec", parameterValues);
        }


        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) chargeId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) parentCharge = reader.GetGuid(1);
                if (!reader.IsDBNull(2)) chargeCode = reader.GetString(2);
                if (!reader.IsDBNull(3)) chargeName = reader.GetString(3);
                if (!reader.IsDBNull(4)) chargeName_Chs = reader.GetString(4);
                if (!reader.IsDBNull(5)) chargeName_Cht = reader.GetString(5);
                if (!reader.IsDBNull(6)) aCCode = reader.GetString(6);
                if (!reader.IsDBNull(7)) dCCode = reader.GetString(7);
            }
        }

        public void Delete()
        {
            Delete(this.ChargeId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != ChargeId)
                    this.Delete();
                Update();
            }
        }

        public Guid ChargeId
        {
            get { return chargeId; }
            set { chargeId = value; }
        }

        public Guid ParentCharge
        {
            get { return parentCharge; }
            set { parentCharge = value; }
        }

        public string ChargeCode
        {
            get { return chargeCode; }
            set { chargeCode = value; }
        }

        public string ChargeName
        {
            get { return chargeName; }
            set { chargeName = value; }
        }

        public string ChargeName_Chs
        {
            get { return chargeName_Chs; }
            set { chargeName_Chs = value; }
        }

        public string ChargeName_Cht
        {
            get { return chargeName_Cht; }
            set { chargeName_Cht = value; }
        }

        public string ACCode
        {
            get { return aCCode; }
            set { aCCode = value; }
        }

        public string DCCode
        {
            get { return dCCode; }
            set { dCCode = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;

            SqlHelper.Default.ExecuteNonQuery("spT_Charge_InsRec", "@ChargeId", out returnedValue, parameterValues);

            chargeId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();

            SqlHelper.Default.ExecuteNonQuery("spT_Charge_UpdRec", parameterValues);
        }

        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[8];
            prams[0] = GetSqlParameter("@ChargeId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.ChargeId);
            prams[1] = GetSqlParameter("@ParentCharge", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.ParentCharge);
            prams[2] = GetSqlParameter("@ChargeCode", ParameterDirection.Input, SqlDbType.VarChar, 6, this.ChargeCode);
            prams[3] = GetSqlParameter("@ChargeName", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.ChargeName);
            prams[4] = GetSqlParameter("@ChargeName_Chs", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.ChargeName_Chs);
            prams[5] = GetSqlParameter("@ChargeName_Cht", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.ChargeName_Cht);
            prams[6] = GetSqlParameter("@ACCode", ParameterDirection.Input, SqlDbType.VarChar, 10, this.ACCode);
            prams[7] = GetSqlParameter("@DCCode", ParameterDirection.Input, SqlDbType.VarChar, 1, this.DCCode);
            return prams;
        }

        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }

        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[]
            {
                GetSqlParameterWithoutDirection("@ChargeId", SqlDbType.UniqueIdentifier, 16, this.ChargeId),
                GetSqlParameterWithoutDirection("@ParentCharge", SqlDbType.UniqueIdentifier, 16, this.ParentCharge),
                GetSqlParameterWithoutDirection("@ChargeCode", SqlDbType.VarChar, 6, this.ChargeCode),
                GetSqlParameterWithoutDirection("@ChargeName", SqlDbType.NVarChar, 64, this.ChargeName),
                GetSqlParameterWithoutDirection("@ChargeName_Chs", SqlDbType.NVarChar, 64, this.ChargeName_Chs),
                GetSqlParameterWithoutDirection("@ChargeName_Cht", SqlDbType.NVarChar, 64, this.ChargeName_Cht),
                GetSqlParameterWithoutDirection("@ACCode", SqlDbType.VarChar, 10, this.ACCode),
                GetSqlParameterWithoutDirection("@DCCode", SqlDbType.VarChar, 1, this.DCCode)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("chargeId: " + chargeId.ToString()).Append("\r\n");
            builder.Append("parentCharge: " + parentCharge.ToString()).Append("\r\n");
            builder.Append("chargeCode: " + chargeCode.ToString()).Append("\r\n");
            builder.Append("chargeName: " + chargeName.ToString()).Append("\r\n");
            builder.Append("chargeName_Chs: " + chargeName_Chs.ToString()).Append("\r\n");
            builder.Append("chargeName_Cht: " + chargeName_Cht.ToString()).Append("\r\n");
            builder.Append("aCCode: " + aCCode.ToString()).Append("\r\n");
            builder.Append("dCCode: " + dCCode.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }

        #region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            string[] textField = { TextField };
            LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            if (SwitchLocale)
            {
                TextField = GetSwitchLocale(TextField);
            }
            ddList.Items.Clear();

            T_ChargeCollection source;

            if (OrderBy == null || OrderBy.Length == 0)
            {
                OrderBy = TextField;
            }

            if (WhereClause.Length > 0)
            {
                source = T_Charge.LoadCollection(WhereClause, OrderBy, true);
            }
            else
            {
                source = T_Charge.LoadCollection(OrderBy, true);
            }

            Common.ComboList sourceList = new Common.ComboList();

            if (BlankLine)
            {
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
            }

            foreach (T_Charge item in source)
            {
                bool filter = false;
                if (ParentFilter.Trim() != String.Empty)
                {
                    filter = true;
                    if (item.ParentCharge != Guid.Empty)
                    {
                        filter = IgnorThis(item, ParentFilter);
                    }
                }
                if (!(filter))
                {
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.ChargeId));
                }
            }

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";

            if (ddList.Items.Count > 0)
            {
                ddList.SelectedIndex = 0;
            }
        }

        #endregion


        private static bool IgnorThis(T_Charge target, string parentFilter)
        {
            bool result = true;
            parentFilter = parentFilter.Replace(" ", "");       // remove spaces
            parentFilter = parentFilter.Replace("'", "");       // remove '
            string[] parsed = parentFilter.Split('=');          // parse

            if (target.ParentCharge == Guid.Empty)
            {
                PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
                string filterField = (string)pi.GetValue(target, null);
                if (filterField.ToLower() == parsed[1].ToLower())
                {
                    result = false;
                }
            }
            else
            {
                T_Charge parentTemplate = T_Charge.Load(target.ParentCharge);
                result = IgnorThis(parentTemplate, parentFilter);
            }
            return result;
        }

        private static string GetFormatedText(T_Charge target, string[] textField, string textFormatString)
        {
            for (int i = 0; i < textField.Length; i++)
            {
                PropertyInfo pi = target.GetType().GetProperty(textField[i]);
                textFormatString = textFormatString.Replace("{" + i.ToString() + "}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
            }
            return textFormatString;
        }

        private static string[] GetSwitchLocale(string[] source)
        {
            switch (Common.Config.CurrentLanguageId)
            {
                case 2:
                    source[source.Length - 1] += "_Chs";
                    break;
                case 3:
                    source[source.Length - 1] += "_Cht";
                    break;
            }
            return source;
        }
    }


    /// <summary>
    /// Represents a collection of <see cref="T_Charge">T_Charge</see> objects.
    /// </summary>
    public class T_ChargeCollection : BindingList<T_Charge>
    {
    }
}
