using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace xPort5.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.T_Currency.
    /// Date Created:   2020-03-02 02:40:13
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class T_Currency
    {
        private Guid key = Guid.Empty;
        private Guid currencyId = Guid.Empty;
        private string currencyCode = String.Empty;
        private string currencyName = String.Empty;
        private string currencyName_Chs = String.Empty;
        private string currencyName_Cht = String.Empty;
        private decimal foreignCny;
        private decimal localCny;
        private int xchgBase = 0;
        private decimal xchgRate;
        private bool localCurrency;

        /// <summary>
        /// Initialize an new empty T_Currency object.
        /// </summary>
        public T_Currency()
        {
        }

        /// <summary>
        /// Initialize a new T_Currency object with the given parameters.
        /// </summary>
        public T_Currency(Guid currencyId, string currencyCode, string currencyName, string currencyName_Chs, string currencyName_Cht, decimal foreignCny, decimal localCny, int xchgBase, decimal xchgRate, bool localCurrency)
        {
            this.currencyId = currencyId;
            this.currencyCode = currencyCode;
            this.currencyName = currencyName;
            this.currencyName_Chs = currencyName_Chs;
            this.currencyName_Cht = currencyName_Cht;
            this.foreignCny = foreignCny;
            this.localCny = localCny;
            this.xchgBase = xchgBase;
            this.xchgRate = xchgRate;
            this.localCurrency = localCurrency;
        }

        /// <summary>
        /// Loads a T_Currency object from the database using the given CurrencyId
        /// </summary>
        /// <param name="currencyId">The primary key value</param>
        /// <returns>A T_Currency object</returns>
        public static T_Currency Load(Guid currencyId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@CurrencyId", currencyId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spT_Currency_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    T_Currency result = new T_Currency();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a T_Currency object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A T_Currency object</returns>
        public static T_Currency LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spT_Currency_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    T_Currency result = new T_Currency();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a collection of T_Currency objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_Currency objects in the database.</returns>
        public static T_CurrencyCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] { };
            return LoadCollection("spT_Currency_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_Currency objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the T_Currency objects in the database ordered by the columns specified.</returns>
        public static T_CurrencyCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spT_Currency_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_Currency objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_Currency objects in the database.</returns>
        public static T_CurrencyCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spT_Currency_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_Currency objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the T_Currency objects in the database ordered by the columns specified.</returns>
        public static T_CurrencyCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spT_Currency_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_Currency objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_Currency objects in the database.</returns>
        public static T_CurrencyCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            T_CurrencyCollection result = new T_CurrencyCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    T_Currency tmp = new T_Currency();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a T_Currency object from the database.
        /// </summary>
        /// <param name="currencyId">The primary key value</param>
        public static void Delete(Guid currencyId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@CurrencyId", currencyId) };
            SqlHelper.Default.ExecuteNonQuery("spT_Currency_DelRec", parameterValues);
        }


        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) currencyId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) currencyCode = reader.GetString(1);
                if (!reader.IsDBNull(2)) currencyName = reader.GetString(2);
                if (!reader.IsDBNull(3)) currencyName_Chs = reader.GetString(3);
                if (!reader.IsDBNull(4)) currencyName_Cht = reader.GetString(4);
                if (!reader.IsDBNull(5)) foreignCny = reader.GetDecimal(5);
                if (!reader.IsDBNull(6)) localCny = reader.GetDecimal(6);
                if (!reader.IsDBNull(7)) xchgBase = reader.GetInt32(7);
                if (!reader.IsDBNull(8)) xchgRate = reader.GetDecimal(8);
                if (!reader.IsDBNull(9)) localCurrency = reader.GetBoolean(9);
            }
        }

        public void Delete()
        {
            Delete(this.CurrencyId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != CurrencyId)
                    this.Delete();
                Update();
            }
        }

        public Guid CurrencyId
        {
            get { return currencyId; }
            set { currencyId = value; }
        }

        public string CurrencyCode
        {
            get { return currencyCode; }
            set { currencyCode = value; }
        }

        public string CurrencyName
        {
            get { return currencyName; }
            set { currencyName = value; }
        }

        public string CurrencyName_Chs
        {
            get { return currencyName_Chs; }
            set { currencyName_Chs = value; }
        }

        public string CurrencyName_Cht
        {
            get { return currencyName_Cht; }
            set { currencyName_Cht = value; }
        }

        public decimal ForeignCny
        {
            get { return foreignCny; }
            set { foreignCny = value; }
        }

        public decimal LocalCny
        {
            get { return localCny; }
            set { localCny = value; }
        }

        public int XchgBase
        {
            get { return xchgBase; }
            set { xchgBase = value; }
        }

        public decimal XchgRate
        {
            get { return xchgRate; }
            set { xchgRate = value; }
        }

        public bool LocalCurrency
        {
            get { return localCurrency; }
            set { localCurrency = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;

            SqlHelper.Default.ExecuteNonQuery("spT_Currency_InsRec", "@CurrencyId", out returnedValue, parameterValues);

            currencyId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();

            SqlHelper.Default.ExecuteNonQuery("spT_Currency_UpdRec", parameterValues);
        }

        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[10];
            prams[0] = GetSqlParameter("@CurrencyId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.CurrencyId);
            prams[1] = GetSqlParameter("@CurrencyCode", ParameterDirection.Input, SqlDbType.VarChar, 3, this.CurrencyCode);
            prams[2] = GetSqlParameter("@CurrencyName", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.CurrencyName);
            prams[3] = GetSqlParameter("@CurrencyName_Chs", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.CurrencyName_Chs);
            prams[4] = GetSqlParameter("@CurrencyName_Cht", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.CurrencyName_Cht);
            prams[5] = GetSqlParameter("@ForeignCny", ParameterDirection.Input, SqlDbType.Decimal, 9, this.ForeignCny);
            prams[6] = GetSqlParameter("@LocalCny", ParameterDirection.Input, SqlDbType.Decimal, 9, this.LocalCny);
            prams[7] = GetSqlParameter("@XchgBase", ParameterDirection.Input, SqlDbType.Int, 4, this.XchgBase);
            prams[8] = GetSqlParameter("@XchgRate", ParameterDirection.Input, SqlDbType.Decimal, 9, this.XchgRate);
            prams[9] = GetSqlParameter("@LocalCurrency", ParameterDirection.Input, SqlDbType.Bit, 1, this.LocalCurrency);
            return prams;
        }

        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }

        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[]
            {
                GetSqlParameterWithoutDirection("@CurrencyId", SqlDbType.UniqueIdentifier, 16, this.CurrencyId),
                GetSqlParameterWithoutDirection("@CurrencyCode", SqlDbType.VarChar, 3, this.CurrencyCode),
                GetSqlParameterWithoutDirection("@CurrencyName", SqlDbType.NVarChar, 64, this.CurrencyName),
                GetSqlParameterWithoutDirection("@CurrencyName_Chs", SqlDbType.NVarChar, 64, this.CurrencyName_Chs),
                GetSqlParameterWithoutDirection("@CurrencyName_Cht", SqlDbType.NVarChar, 64, this.CurrencyName_Cht),
                GetSqlParameterWithoutDirection("@ForeignCny", SqlDbType.Decimal, 9, this.ForeignCny),
                GetSqlParameterWithoutDirection("@LocalCny", SqlDbType.Decimal, 9, this.LocalCny),
                GetSqlParameterWithoutDirection("@XchgBase", SqlDbType.Int, 4, this.XchgBase),
                GetSqlParameterWithoutDirection("@XchgRate", SqlDbType.Decimal, 9, this.XchgRate),
                GetSqlParameterWithoutDirection("@LocalCurrency", SqlDbType.Bit, 1, this.LocalCurrency)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("currencyId: " + currencyId.ToString()).Append("\r\n");
            builder.Append("currencyCode: " + currencyCode.ToString()).Append("\r\n");
            builder.Append("currencyName: " + currencyName.ToString()).Append("\r\n");
            builder.Append("currencyName_Chs: " + currencyName_Chs.ToString()).Append("\r\n");
            builder.Append("currencyName_Cht: " + currencyName_Cht.ToString()).Append("\r\n");
            builder.Append("foreignCny: " + foreignCny.ToString()).Append("\r\n");
            builder.Append("localCny: " + localCny.ToString()).Append("\r\n");
            builder.Append("xchgBase: " + xchgBase.ToString()).Append("\r\n");
            builder.Append("xchgRate: " + xchgRate.ToString()).Append("\r\n");
            builder.Append("localCurrency: " + localCurrency.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }

        #region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            string[] textField = { TextField };
            LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            if (SwitchLocale)
            {
                TextField = GetSwitchLocale(TextField);
            }
            ddList.Items.Clear();

            T_CurrencyCollection source;

            if (OrderBy == null || OrderBy.Length == 0)
            {
                OrderBy = TextField;
            }

            if (WhereClause.Length > 0)
            {
                source = T_Currency.LoadCollection(WhereClause, OrderBy, true);
            }
            else
            {
                source = T_Currency.LoadCollection(OrderBy, true);
            }

            Common.ComboList sourceList = new Common.ComboList();

            if (BlankLine)
            {
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
            }

            foreach (T_Currency item in source)
            {
                bool filter = false;
                if (ParentFilter.Trim() != String.Empty)
                {
                    filter = IgnorThis(item, ParentFilter);
                }
                if (!(filter))
                {
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.CurrencyId));
                }
            }

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";

            if (ddList.Items.Count > 0)
            {
                ddList.SelectedIndex = 0;
            }
        }

        #endregion


        private static bool IgnorThis(T_Currency target, string parentFilter)
        {
            bool result = true;
            parentFilter = parentFilter.Replace(" ", "");       // remove spaces
            parentFilter = parentFilter.Replace("'", "");       // remove '
            string[] parsed = parentFilter.Split('=');          // parse

            PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
            string filterField = (string)pi.GetValue(target, null);
            if (filterField.ToLower() == parsed[1].ToLower())
            {
                result = false;
            }
            return result;
        }

        private static string GetFormatedText(T_Currency target, string[] textField, string textFormatString)
        {
            for (int i = 0; i < textField.Length; i++)
            {
                PropertyInfo pi = target.GetType().GetProperty(textField[i]);
                textFormatString = textFormatString.Replace("{" + i.ToString() + "}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
            }
            return textFormatString;
        }

        private static string[] GetSwitchLocale(string[] source)
        {
            switch (Common.Config.CurrentLanguageId)
            {
                case 2:
                    source[source.Length - 1] += "_Chs";
                    break;
                case 3:
                    source[source.Length - 1] += "_Cht";
                    break;
            }
            return source;
        }
    }


    /// <summary>
    /// Represents a collection of <see cref="T_Currency">T_Currency</see> objects.
    /// </summary>
    public class T_CurrencyCollection : BindingList<T_Currency>
    {
    }
}
