using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace xPort5.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.T_Origin.
    /// Date Created:   2020-03-02 02:38:53
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class T_Origin
    {
        private Guid key = Guid.Empty;
        private Guid originId = Guid.Empty;
        private Guid parentOrigin = Guid.Empty;
        private string originCode = String.Empty;
        private string originName = String.Empty;
        private string originName_Chs = String.Empty;
        private string originName_Cht = String.Empty;

        /// <summary>
        /// Initialize an new empty T_Origin object.
        /// </summary>
        public T_Origin()
        {
        }

        /// <summary>
        /// Initialize a new T_Origin object with the given parameters.
        /// </summary>
        public T_Origin(Guid originId, Guid parentOrigin, string originCode, string originName, string originName_Chs, string originName_Cht)
        {
            this.originId = originId;
            this.parentOrigin = parentOrigin;
            this.originCode = originCode;
            this.originName = originName;
            this.originName_Chs = originName_Chs;
            this.originName_Cht = originName_Cht;
        }

        /// <summary>
        /// Loads a T_Origin object from the database using the given OriginId
        /// </summary>
        /// <param name="originId">The primary key value</param>
        /// <returns>A T_Origin object</returns>
        public static T_Origin Load(Guid originId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@OriginId", originId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spT_Origin_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    T_Origin result = new T_Origin();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a T_Origin object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A T_Origin object</returns>
        public static T_Origin LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spT_Origin_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    T_Origin result = new T_Origin();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a collection of T_Origin objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_Origin objects in the database.</returns>
        public static T_OriginCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] { };
            return LoadCollection("spT_Origin_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_Origin objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the T_Origin objects in the database ordered by the columns specified.</returns>
        public static T_OriginCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spT_Origin_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_Origin objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_Origin objects in the database.</returns>
        public static T_OriginCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spT_Origin_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_Origin objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the T_Origin objects in the database ordered by the columns specified.</returns>
        public static T_OriginCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spT_Origin_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_Origin objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_Origin objects in the database.</returns>
        public static T_OriginCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            T_OriginCollection result = new T_OriginCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    T_Origin tmp = new T_Origin();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a T_Origin object from the database.
        /// </summary>
        /// <param name="originId">The primary key value</param>
        public static void Delete(Guid originId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@OriginId", originId) };
            SqlHelper.Default.ExecuteNonQuery("spT_Origin_DelRec", parameterValues);
        }


        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) originId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) parentOrigin = reader.GetGuid(1);
                if (!reader.IsDBNull(2)) originCode = reader.GetString(2);
                if (!reader.IsDBNull(3)) originName = reader.GetString(3);
                if (!reader.IsDBNull(4)) originName_Chs = reader.GetString(4);
                if (!reader.IsDBNull(5)) originName_Cht = reader.GetString(5);
            }
        }

        public void Delete()
        {
            Delete(this.OriginId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != OriginId)
                    this.Delete();
                Update();
            }
        }

        public Guid OriginId
        {
            get { return originId; }
            set { originId = value; }
        }

        public Guid ParentOrigin
        {
            get { return parentOrigin; }
            set { parentOrigin = value; }
        }

        public string OriginCode
        {
            get { return originCode; }
            set { originCode = value; }
        }

        public string OriginName
        {
            get { return originName; }
            set { originName = value; }
        }

        public string OriginName_Chs
        {
            get { return originName_Chs; }
            set { originName_Chs = value; }
        }

        public string OriginName_Cht
        {
            get { return originName_Cht; }
            set { originName_Cht = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;

            SqlHelper.Default.ExecuteNonQuery("spT_Origin_InsRec", "@OriginId", out returnedValue, parameterValues);

            originId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();

            SqlHelper.Default.ExecuteNonQuery("spT_Origin_UpdRec", parameterValues);
        }

        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[6];
            prams[0] = GetSqlParameter("@OriginId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.OriginId);
            prams[1] = GetSqlParameter("@ParentOrigin", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.ParentOrigin);
            prams[2] = GetSqlParameter("@OriginCode", ParameterDirection.Input, SqlDbType.VarChar, 6, this.OriginCode);
            prams[3] = GetSqlParameter("@OriginName", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.OriginName);
            prams[4] = GetSqlParameter("@OriginName_Chs", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.OriginName_Chs);
            prams[5] = GetSqlParameter("@OriginName_Cht", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.OriginName_Cht);
            return prams;
        }

        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }

        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[]
            {
                GetSqlParameterWithoutDirection("@OriginId", SqlDbType.UniqueIdentifier, 16, this.OriginId),
                GetSqlParameterWithoutDirection("@ParentOrigin", SqlDbType.UniqueIdentifier, 16, this.ParentOrigin),
                GetSqlParameterWithoutDirection("@OriginCode", SqlDbType.VarChar, 6, this.OriginCode),
                GetSqlParameterWithoutDirection("@OriginName", SqlDbType.NVarChar, 64, this.OriginName),
                GetSqlParameterWithoutDirection("@OriginName_Chs", SqlDbType.NVarChar, 64, this.OriginName_Chs),
                GetSqlParameterWithoutDirection("@OriginName_Cht", SqlDbType.NVarChar, 64, this.OriginName_Cht)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("originId: " + originId.ToString()).Append("\r\n");
            builder.Append("parentOrigin: " + parentOrigin.ToString()).Append("\r\n");
            builder.Append("originCode: " + originCode.ToString()).Append("\r\n");
            builder.Append("originName: " + originName.ToString()).Append("\r\n");
            builder.Append("originName_Chs: " + originName_Chs.ToString()).Append("\r\n");
            builder.Append("originName_Cht: " + originName_Cht.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }

        #region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            string[] textField = { TextField };
            LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            if (SwitchLocale)
            {
                TextField = GetSwitchLocale(TextField);
            }
            ddList.Items.Clear();

            T_OriginCollection source;

            if (OrderBy == null || OrderBy.Length == 0)
            {
                OrderBy = TextField;
            }

            if (WhereClause.Length > 0)
            {
                source = T_Origin.LoadCollection(WhereClause, OrderBy, true);
            }
            else
            {
                source = T_Origin.LoadCollection(OrderBy, true);
            }

            Common.ComboList sourceList = new Common.ComboList();

            if (BlankLine)
            {
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
            }

            foreach (T_Origin item in source)
            {
                bool filter = false;
                if (ParentFilter.Trim() != String.Empty)
                {
                    filter = true;
                    if (item.ParentOrigin != Guid.Empty)
                    {
                        filter = IgnorThis(item, ParentFilter);
                    }
                }
                if (!(filter))
                {
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.OriginId));
                }
            }

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";

            if (ddList.Items.Count > 0)
            {
                ddList.SelectedIndex = 0;
            }
        }

        #endregion


        private static bool IgnorThis(T_Origin target, string parentFilter)
        {
            bool result = true;
            parentFilter = parentFilter.Replace(" ", "");       // remove spaces
            parentFilter = parentFilter.Replace("'", "");       // remove '
            string[] parsed = parentFilter.Split('=');          // parse

            if (target.ParentOrigin == Guid.Empty)
            {
                PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
                string filterField = (string)pi.GetValue(target, null);
                if (filterField.ToLower() == parsed[1].ToLower())
                {
                    result = false;
                }
            }
            else
            {
                T_Origin parentTemplate = T_Origin.Load(target.ParentOrigin);
                result = IgnorThis(parentTemplate, parentFilter);
            }
            return result;
        }

        private static string GetFormatedText(T_Origin target, string[] textField, string textFormatString)
        {
            for (int i = 0; i < textField.Length; i++)
            {
                PropertyInfo pi = target.GetType().GetProperty(textField[i]);
                textFormatString = textFormatString.Replace("{" + i.ToString() + "}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
            }
            return textFormatString;
        }

        private static string[] GetSwitchLocale(string[] source)
        {
            switch (Common.Config.CurrentLanguageId)
            {
                case 2:
                    source[source.Length - 1] += "_Chs";
                    break;
                case 3:
                    source[source.Length - 1] += "_Cht";
                    break;
            }
            return source;
        }
    }


    /// <summary>
    /// Represents a collection of <see cref="T_Origin">T_Origin</see> objects.
    /// </summary>
    public class T_OriginCollection : BindingList<T_Origin>
    {
    }
}
