using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace xPort5.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.T_PaymentTerms.
    /// Date Created:   2020-03-02 02:37:59
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class T_PaymentTerms
    {
        private Guid key = Guid.Empty;
        private Guid termsId = Guid.Empty;
        private Guid parentTerms = Guid.Empty;
        private string termsType = String.Empty;
        private string termsCode = String.Empty;
        private string termsName = String.Empty;
        private string termsName_Chs = String.Empty;
        private string termsName_Cht = String.Empty;
        private int creditDays = 0;
        private bool monthlyAC;

        /// <summary>
        /// Initialize an new empty T_PaymentTerms object.
        /// </summary>
        public T_PaymentTerms()
        {
        }

        /// <summary>
        /// Initialize a new T_PaymentTerms object with the given parameters.
        /// </summary>
        public T_PaymentTerms(Guid termsId, Guid parentTerms, string termsType, string termsCode, string termsName, string termsName_Chs, string termsName_Cht, int creditDays, bool monthlyAC)
        {
            this.termsId = termsId;
            this.parentTerms = parentTerms;
            this.termsType = termsType;
            this.termsCode = termsCode;
            this.termsName = termsName;
            this.termsName_Chs = termsName_Chs;
            this.termsName_Cht = termsName_Cht;
            this.creditDays = creditDays;
            this.monthlyAC = monthlyAC;
        }

        /// <summary>
        /// Loads a T_PaymentTerms object from the database using the given TermsId
        /// </summary>
        /// <param name="termsId">The primary key value</param>
        /// <returns>A T_PaymentTerms object</returns>
        public static T_PaymentTerms Load(Guid termsId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@TermsId", termsId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spT_PaymentTerms_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    T_PaymentTerms result = new T_PaymentTerms();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a T_PaymentTerms object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A T_PaymentTerms object</returns>
        public static T_PaymentTerms LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spT_PaymentTerms_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    T_PaymentTerms result = new T_PaymentTerms();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a collection of T_PaymentTerms objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_PaymentTerms objects in the database.</returns>
        public static T_PaymentTermsCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] { };
            return LoadCollection("spT_PaymentTerms_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_PaymentTerms objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the T_PaymentTerms objects in the database ordered by the columns specified.</returns>
        public static T_PaymentTermsCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spT_PaymentTerms_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_PaymentTerms objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_PaymentTerms objects in the database.</returns>
        public static T_PaymentTermsCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spT_PaymentTerms_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_PaymentTerms objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the T_PaymentTerms objects in the database ordered by the columns specified.</returns>
        public static T_PaymentTermsCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spT_PaymentTerms_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_PaymentTerms objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_PaymentTerms objects in the database.</returns>
        public static T_PaymentTermsCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            T_PaymentTermsCollection result = new T_PaymentTermsCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    T_PaymentTerms tmp = new T_PaymentTerms();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a T_PaymentTerms object from the database.
        /// </summary>
        /// <param name="termsId">The primary key value</param>
        public static void Delete(Guid termsId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@TermsId", termsId) };
            SqlHelper.Default.ExecuteNonQuery("spT_PaymentTerms_DelRec", parameterValues);
        }


        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) termsId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) parentTerms = reader.GetGuid(1);
                if (!reader.IsDBNull(2)) termsType = reader.GetString(2);
                if (!reader.IsDBNull(3)) termsCode = reader.GetString(3);
                if (!reader.IsDBNull(4)) termsName = reader.GetString(4);
                if (!reader.IsDBNull(5)) termsName_Chs = reader.GetString(5);
                if (!reader.IsDBNull(6)) termsName_Cht = reader.GetString(6);
                if (!reader.IsDBNull(7)) creditDays = reader.GetInt32(7);
                if (!reader.IsDBNull(8)) monthlyAC = reader.GetBoolean(8);
            }
        }

        public void Delete()
        {
            Delete(this.TermsId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != TermsId)
                    this.Delete();
                Update();
            }
        }

        public Guid TermsId
        {
            get { return termsId; }
            set { termsId = value; }
        }

        public Guid ParentTerms
        {
            get { return parentTerms; }
            set { parentTerms = value; }
        }

        public string TermsType
        {
            get { return termsType; }
            set { termsType = value; }
        }

        public string TermsCode
        {
            get { return termsCode; }
            set { termsCode = value; }
        }

        public string TermsName
        {
            get { return termsName; }
            set { termsName = value; }
        }

        public string TermsName_Chs
        {
            get { return termsName_Chs; }
            set { termsName_Chs = value; }
        }

        public string TermsName_Cht
        {
            get { return termsName_Cht; }
            set { termsName_Cht = value; }
        }

        public int CreditDays
        {
            get { return creditDays; }
            set { creditDays = value; }
        }

        public bool MonthlyAC
        {
            get { return monthlyAC; }
            set { monthlyAC = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;

            SqlHelper.Default.ExecuteNonQuery("spT_PaymentTerms_InsRec", "@TermsId", out returnedValue, parameterValues);

            termsId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();

            SqlHelper.Default.ExecuteNonQuery("spT_PaymentTerms_UpdRec", parameterValues);
        }

        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[9];
            prams[0] = GetSqlParameter("@TermsId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.TermsId);
            prams[1] = GetSqlParameter("@ParentTerms", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.ParentTerms);
            prams[2] = GetSqlParameter("@TermsType", ParameterDirection.Input, SqlDbType.VarChar, 1, this.TermsType);
            prams[3] = GetSqlParameter("@TermsCode", ParameterDirection.Input, SqlDbType.VarChar, 6, this.TermsCode);
            prams[4] = GetSqlParameter("@TermsName", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.TermsName);
            prams[5] = GetSqlParameter("@TermsName_Chs", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.TermsName_Chs);
            prams[6] = GetSqlParameter("@TermsName_Cht", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.TermsName_Cht);
            prams[7] = GetSqlParameter("@CreditDays", ParameterDirection.Input, SqlDbType.Int, 4, this.CreditDays);
            prams[8] = GetSqlParameter("@MonthlyAC", ParameterDirection.Input, SqlDbType.Bit, 1, this.MonthlyAC);
            return prams;
        }

        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }

        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[]
            {
                GetSqlParameterWithoutDirection("@TermsId", SqlDbType.UniqueIdentifier, 16, this.TermsId),
                GetSqlParameterWithoutDirection("@ParentTerms", SqlDbType.UniqueIdentifier, 16, this.ParentTerms),
                GetSqlParameterWithoutDirection("@TermsType", SqlDbType.VarChar, 1, this.TermsType),
                GetSqlParameterWithoutDirection("@TermsCode", SqlDbType.VarChar, 6, this.TermsCode),
                GetSqlParameterWithoutDirection("@TermsName", SqlDbType.NVarChar, 64, this.TermsName),
                GetSqlParameterWithoutDirection("@TermsName_Chs", SqlDbType.NVarChar, 64, this.TermsName_Chs),
                GetSqlParameterWithoutDirection("@TermsName_Cht", SqlDbType.NVarChar, 64, this.TermsName_Cht),
                GetSqlParameterWithoutDirection("@CreditDays", SqlDbType.Int, 4, this.CreditDays),
                GetSqlParameterWithoutDirection("@MonthlyAC", SqlDbType.Bit, 1, this.MonthlyAC)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("termsId: " + termsId.ToString()).Append("\r\n");
            builder.Append("parentTerms: " + parentTerms.ToString()).Append("\r\n");
            builder.Append("termsType: " + termsType.ToString()).Append("\r\n");
            builder.Append("termsCode: " + termsCode.ToString()).Append("\r\n");
            builder.Append("termsName: " + termsName.ToString()).Append("\r\n");
            builder.Append("termsName_Chs: " + termsName_Chs.ToString()).Append("\r\n");
            builder.Append("termsName_Cht: " + termsName_Cht.ToString()).Append("\r\n");
            builder.Append("creditDays: " + creditDays.ToString()).Append("\r\n");
            builder.Append("monthlyAC: " + monthlyAC.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }

        #region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            string[] textField = { TextField };
            LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            if (SwitchLocale)
            {
                TextField = GetSwitchLocale(TextField);
            }
            ddList.Items.Clear();

            T_PaymentTermsCollection source;

            if (OrderBy == null || OrderBy.Length == 0)
            {
                OrderBy = TextField;
            }

            if (WhereClause.Length > 0)
            {
                source = T_PaymentTerms.LoadCollection(WhereClause, OrderBy, true);
            }
            else
            {
                source = T_PaymentTerms.LoadCollection(OrderBy, true);
            }

            Common.ComboList sourceList = new Common.ComboList();

            if (BlankLine)
            {
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
            }

            foreach (T_PaymentTerms item in source)
            {
                bool filter = false;
                if (ParentFilter.Trim() != String.Empty)
                {
                    filter = true;
                    if (item.ParentTerms != Guid.Empty)
                    {
                        filter = IgnorThis(item, ParentFilter);
                    }
                }
                if (!(filter))
                {
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.TermsId));
                }
            }

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";

            if (ddList.Items.Count > 0)
            {
                ddList.SelectedIndex = 0;
            }
        }

        #endregion


        private static bool IgnorThis(T_PaymentTerms target, string parentFilter)
        {
            bool result = true;
            parentFilter = parentFilter.Replace(" ", "");       // remove spaces
            parentFilter = parentFilter.Replace("'", "");       // remove '
            string[] parsed = parentFilter.Split('=');          // parse

            if (target.ParentTerms == Guid.Empty)
            {
                PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
                string filterField = (string)pi.GetValue(target, null);
                if (filterField.ToLower() == parsed[1].ToLower())
                {
                    result = false;
                }
            }
            else
            {
                T_PaymentTerms parentTemplate = T_PaymentTerms.Load(target.ParentTerms);
                result = IgnorThis(parentTemplate, parentFilter);
            }
            return result;
        }

        private static string GetFormatedText(T_PaymentTerms target, string[] textField, string textFormatString)
        {
            for (int i = 0; i < textField.Length; i++)
            {
                PropertyInfo pi = target.GetType().GetProperty(textField[i]);
                textFormatString = textFormatString.Replace("{" + i.ToString() + "}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
            }
            return textFormatString;
        }

        private static string[] GetSwitchLocale(string[] source)
        {
            switch (Common.Config.CurrentLanguageId)
            {
                case 2:
                    source[source.Length - 1] += "_Chs";
                    break;
                case 3:
                    source[source.Length - 1] += "_Cht";
                    break;
            }
            return source;
        }
    }


    /// <summary>
    /// Represents a collection of <see cref="T_PaymentTerms">T_PaymentTerms</see> objects.
    /// </summary>
    public class T_PaymentTermsCollection : BindingList<T_PaymentTerms>
    {
    }
}
