using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace xPort5.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.T_Region.
    /// Date Created:   2020-03-02 02:36:36
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class T_Region
    {
        private Guid key = Guid.Empty;
        private Guid regionId = Guid.Empty;
        private Guid parentRegion = Guid.Empty;
        private string regionCode = String.Empty;
        private string regionName = String.Empty;
        private string regionName_Chs = String.Empty;
        private string regionName_Cht = String.Empty;

        /// <summary>
        /// Initialize an new empty T_Region object.
        /// </summary>
        public T_Region()
        {
        }

        /// <summary>
        /// Initialize a new T_Region object with the given parameters.
        /// </summary>
        public T_Region(Guid regionId, Guid parentRegion, string regionCode, string regionName, string regionName_Chs, string regionName_Cht)
        {
            this.regionId = regionId;
            this.parentRegion = parentRegion;
            this.regionCode = regionCode;
            this.regionName = regionName;
            this.regionName_Chs = regionName_Chs;
            this.regionName_Cht = regionName_Cht;
        }

        /// <summary>
        /// Loads a T_Region object from the database using the given RegionId
        /// </summary>
        /// <param name="regionId">The primary key value</param>
        /// <returns>A T_Region object</returns>
        public static T_Region Load(Guid regionId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@RegionId", regionId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spT_Region_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    T_Region result = new T_Region();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a T_Region object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A T_Region object</returns>
        public static T_Region LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spT_Region_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    T_Region result = new T_Region();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a collection of T_Region objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_Region objects in the database.</returns>
        public static T_RegionCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] { };
            return LoadCollection("spT_Region_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_Region objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the T_Region objects in the database ordered by the columns specified.</returns>
        public static T_RegionCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spT_Region_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_Region objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_Region objects in the database.</returns>
        public static T_RegionCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spT_Region_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_Region objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the T_Region objects in the database ordered by the columns specified.</returns>
        public static T_RegionCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spT_Region_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_Region objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_Region objects in the database.</returns>
        public static T_RegionCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            T_RegionCollection result = new T_RegionCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    T_Region tmp = new T_Region();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a T_Region object from the database.
        /// </summary>
        /// <param name="regionId">The primary key value</param>
        public static void Delete(Guid regionId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@RegionId", regionId) };
            SqlHelper.Default.ExecuteNonQuery("spT_Region_DelRec", parameterValues);
        }


        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) regionId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) parentRegion = reader.GetGuid(1);
                if (!reader.IsDBNull(2)) regionCode = reader.GetString(2);
                if (!reader.IsDBNull(3)) regionName = reader.GetString(3);
                if (!reader.IsDBNull(4)) regionName_Chs = reader.GetString(4);
                if (!reader.IsDBNull(5)) regionName_Cht = reader.GetString(5);
            }
        }

        public void Delete()
        {
            Delete(this.RegionId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != RegionId)
                    this.Delete();
                Update();
            }
        }

        public Guid RegionId
        {
            get { return regionId; }
            set { regionId = value; }
        }

        public Guid ParentRegion
        {
            get { return parentRegion; }
            set { parentRegion = value; }
        }

        public string RegionCode
        {
            get { return regionCode; }
            set { regionCode = value; }
        }

        public string RegionName
        {
            get { return regionName; }
            set { regionName = value; }
        }

        public string RegionName_Chs
        {
            get { return regionName_Chs; }
            set { regionName_Chs = value; }
        }

        public string RegionName_Cht
        {
            get { return regionName_Cht; }
            set { regionName_Cht = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;

            SqlHelper.Default.ExecuteNonQuery("spT_Region_InsRec", "@RegionId", out returnedValue, parameterValues);

            regionId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();

            SqlHelper.Default.ExecuteNonQuery("spT_Region_UpdRec", parameterValues);
        }

        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[6];
            prams[0] = GetSqlParameter("@RegionId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.RegionId);
            prams[1] = GetSqlParameter("@ParentRegion", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.ParentRegion);
            prams[2] = GetSqlParameter("@RegionCode", ParameterDirection.Input, SqlDbType.VarChar, 6, this.RegionCode);
            prams[3] = GetSqlParameter("@RegionName", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.RegionName);
            prams[4] = GetSqlParameter("@RegionName_Chs", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.RegionName_Chs);
            prams[5] = GetSqlParameter("@RegionName_Cht", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.RegionName_Cht);
            return prams;
        }

        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }

        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[]
            {
                GetSqlParameterWithoutDirection("@RegionId", SqlDbType.UniqueIdentifier, 16, this.RegionId),
                GetSqlParameterWithoutDirection("@ParentRegion", SqlDbType.UniqueIdentifier, 16, this.ParentRegion),
                GetSqlParameterWithoutDirection("@RegionCode", SqlDbType.VarChar, 6, this.RegionCode),
                GetSqlParameterWithoutDirection("@RegionName", SqlDbType.NVarChar, 64, this.RegionName),
                GetSqlParameterWithoutDirection("@RegionName_Chs", SqlDbType.NVarChar, 64, this.RegionName_Chs),
                GetSqlParameterWithoutDirection("@RegionName_Cht", SqlDbType.NVarChar, 64, this.RegionName_Cht)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("regionId: " + regionId.ToString()).Append("\r\n");
            builder.Append("parentRegion: " + parentRegion.ToString()).Append("\r\n");
            builder.Append("regionCode: " + regionCode.ToString()).Append("\r\n");
            builder.Append("regionName: " + regionName.ToString()).Append("\r\n");
            builder.Append("regionName_Chs: " + regionName_Chs.ToString()).Append("\r\n");
            builder.Append("regionName_Cht: " + regionName_Cht.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }

        #region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            string[] textField = { TextField };
            LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            if (SwitchLocale)
            {
                TextField = GetSwitchLocale(TextField);
            }
            ddList.Items.Clear();

            T_RegionCollection source;

            if (OrderBy == null || OrderBy.Length == 0)
            {
                OrderBy = TextField;
            }

            if (WhereClause.Length > 0)
            {
                source = T_Region.LoadCollection(WhereClause, OrderBy, true);
            }
            else
            {
                source = T_Region.LoadCollection(OrderBy, true);
            }

            Common.ComboList sourceList = new Common.ComboList();

            if (BlankLine)
            {
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
            }

            foreach (T_Region item in source)
            {
                bool filter = false;
                if (ParentFilter.Trim() != String.Empty)
                {
                    filter = true;
                    if (item.ParentRegion != Guid.Empty)
                    {
                        filter = IgnorThis(item, ParentFilter);
                    }
                }
                if (!(filter))
                {
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.RegionId));
                }
            }

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";

            if (ddList.Items.Count > 0)
            {
                ddList.SelectedIndex = 0;
            }
        }

        #endregion


        private static bool IgnorThis(T_Region target, string parentFilter)
        {
            bool result = true;
            parentFilter = parentFilter.Replace(" ", "");       // remove spaces
            parentFilter = parentFilter.Replace("'", "");       // remove '
            string[] parsed = parentFilter.Split('=');          // parse

            if (target.ParentRegion == Guid.Empty)
            {
                PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
                string filterField = (string)pi.GetValue(target, null);
                if (filterField.ToLower() == parsed[1].ToLower())
                {
                    result = false;
                }
            }
            else
            {
                T_Region parentTemplate = T_Region.Load(target.ParentRegion);
                result = IgnorThis(parentTemplate, parentFilter);
            }
            return result;
        }

        private static string GetFormatedText(T_Region target, string[] textField, string textFormatString)
        {
            for (int i = 0; i < textField.Length; i++)
            {
                PropertyInfo pi = target.GetType().GetProperty(textField[i]);
                textFormatString = textFormatString.Replace("{" + i.ToString() + "}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
            }
            return textFormatString;
        }

        private static string[] GetSwitchLocale(string[] source)
        {
            switch (Common.Config.CurrentLanguageId)
            {
                case 2:
                    source[source.Length - 1] += "_Chs";
                    break;
                case 3:
                    source[source.Length - 1] += "_Cht";
                    break;
            }
            return source;
        }
    }


    /// <summary>
    /// Represents a collection of <see cref="T_Region">T_Region</see> objects.
    /// </summary>
    public class T_RegionCollection : BindingList<T_Region>
    {
    }
}
