using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace xPort5.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.T_ShippingMark.
    /// Date Created:   2020-03-02 02:32:18
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class T_ShippingMark
    {
        private Guid key = Guid.Empty;
        private Guid shippingMarkId = Guid.Empty;
        private Guid parentShippingMark = Guid.Empty;
        private string shippingMarkCode = String.Empty;
        private string shippingMarkName = String.Empty;
        private string shippingMarkName_Chs = String.Empty;
        private string shippingMarkName_Cht = String.Empty;

        /// <summary>
        /// Initialize an new empty T_ShippingMark object.
        /// </summary>
        public T_ShippingMark()
        {
        }

        /// <summary>
        /// Initialize a new T_ShippingMark object with the given parameters.
        /// </summary>
        public T_ShippingMark(Guid shippingMarkId, Guid parentShippingMark, string shippingMarkCode, string shippingMarkName, string shippingMarkName_Chs, string shippingMarkName_Cht)
        {
            this.shippingMarkId = shippingMarkId;
            this.parentShippingMark = parentShippingMark;
            this.shippingMarkCode = shippingMarkCode;
            this.shippingMarkName = shippingMarkName;
            this.shippingMarkName_Chs = shippingMarkName_Chs;
            this.shippingMarkName_Cht = shippingMarkName_Cht;
        }

        /// <summary>
        /// Loads a T_ShippingMark object from the database using the given ShippingMarkId
        /// </summary>
        /// <param name="shippingMarkId">The primary key value</param>
        /// <returns>A T_ShippingMark object</returns>
        public static T_ShippingMark Load(Guid shippingMarkId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@ShippingMarkId", shippingMarkId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spT_ShippingMark_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    T_ShippingMark result = new T_ShippingMark();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a T_ShippingMark object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A T_ShippingMark object</returns>
        public static T_ShippingMark LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spT_ShippingMark_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    T_ShippingMark result = new T_ShippingMark();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a collection of T_ShippingMark objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_ShippingMark objects in the database.</returns>
        public static T_ShippingMarkCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] { };
            return LoadCollection("spT_ShippingMark_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_ShippingMark objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the T_ShippingMark objects in the database ordered by the columns specified.</returns>
        public static T_ShippingMarkCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spT_ShippingMark_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_ShippingMark objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_ShippingMark objects in the database.</returns>
        public static T_ShippingMarkCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spT_ShippingMark_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_ShippingMark objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the T_ShippingMark objects in the database ordered by the columns specified.</returns>
        public static T_ShippingMarkCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spT_ShippingMark_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_ShippingMark objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_ShippingMark objects in the database.</returns>
        public static T_ShippingMarkCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            T_ShippingMarkCollection result = new T_ShippingMarkCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    T_ShippingMark tmp = new T_ShippingMark();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a T_ShippingMark object from the database.
        /// </summary>
        /// <param name="shippingMarkId">The primary key value</param>
        public static void Delete(Guid shippingMarkId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@ShippingMarkId", shippingMarkId) };
            SqlHelper.Default.ExecuteNonQuery("spT_ShippingMark_DelRec", parameterValues);
        }


        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) shippingMarkId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) parentShippingMark = reader.GetGuid(1);
                if (!reader.IsDBNull(2)) shippingMarkCode = reader.GetString(2);
                if (!reader.IsDBNull(3)) shippingMarkName = reader.GetString(3);
                if (!reader.IsDBNull(4)) shippingMarkName_Chs = reader.GetString(4);
                if (!reader.IsDBNull(5)) shippingMarkName_Cht = reader.GetString(5);
            }
        }

        public void Delete()
        {
            Delete(this.ShippingMarkId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != ShippingMarkId)
                    this.Delete();
                Update();
            }
        }

        public Guid ShippingMarkId
        {
            get { return shippingMarkId; }
            set { shippingMarkId = value; }
        }

        public Guid ParentShippingMark
        {
            get { return parentShippingMark; }
            set { parentShippingMark = value; }
        }

        public string ShippingMarkCode
        {
            get { return shippingMarkCode; }
            set { shippingMarkCode = value; }
        }

        public string ShippingMarkName
        {
            get { return shippingMarkName; }
            set { shippingMarkName = value; }
        }

        public string ShippingMarkName_Chs
        {
            get { return shippingMarkName_Chs; }
            set { shippingMarkName_Chs = value; }
        }

        public string ShippingMarkName_Cht
        {
            get { return shippingMarkName_Cht; }
            set { shippingMarkName_Cht = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;

            SqlHelper.Default.ExecuteNonQuery("spT_ShippingMark_InsRec", "@ShippingMarkId", out returnedValue, parameterValues);

            shippingMarkId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();

            SqlHelper.Default.ExecuteNonQuery("spT_ShippingMark_UpdRec", parameterValues);
        }

        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[6];
            prams[0] = GetSqlParameter("@ShippingMarkId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.ShippingMarkId);
            prams[1] = GetSqlParameter("@ParentShippingMark", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.ParentShippingMark);
            prams[2] = GetSqlParameter("@ShippingMarkCode", ParameterDirection.Input, SqlDbType.VarChar, 6, this.ShippingMarkCode);
            prams[3] = GetSqlParameter("@ShippingMarkName", ParameterDirection.Input, SqlDbType.NVarChar, 255, this.ShippingMarkName);
            prams[4] = GetSqlParameter("@ShippingMarkName_Chs", ParameterDirection.Input, SqlDbType.NVarChar, 255, this.ShippingMarkName_Chs);
            prams[5] = GetSqlParameter("@ShippingMarkName_Cht", ParameterDirection.Input, SqlDbType.NVarChar, 255, this.ShippingMarkName_Cht);
            return prams;
        }

        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }

        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[]
            {
                GetSqlParameterWithoutDirection("@ShippingMarkId", SqlDbType.UniqueIdentifier, 16, this.ShippingMarkId),
                GetSqlParameterWithoutDirection("@ParentShippingMark", SqlDbType.UniqueIdentifier, 16, this.ParentShippingMark),
                GetSqlParameterWithoutDirection("@ShippingMarkCode", SqlDbType.VarChar, 6, this.ShippingMarkCode),
                GetSqlParameterWithoutDirection("@ShippingMarkName", SqlDbType.NVarChar, 255, this.ShippingMarkName),
                GetSqlParameterWithoutDirection("@ShippingMarkName_Chs", SqlDbType.NVarChar, 255, this.ShippingMarkName_Chs),
                GetSqlParameterWithoutDirection("@ShippingMarkName_Cht", SqlDbType.NVarChar, 255, this.ShippingMarkName_Cht)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("shippingMarkId: " + shippingMarkId.ToString()).Append("\r\n");
            builder.Append("parentShippingMark: " + parentShippingMark.ToString()).Append("\r\n");
            builder.Append("shippingMarkCode: " + shippingMarkCode.ToString()).Append("\r\n");
            builder.Append("shippingMarkName: " + shippingMarkName.ToString()).Append("\r\n");
            builder.Append("shippingMarkName_Chs: " + shippingMarkName_Chs.ToString()).Append("\r\n");
            builder.Append("shippingMarkName_Cht: " + shippingMarkName_Cht.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }

        #region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            string[] textField = { TextField };
            LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            if (SwitchLocale)
            {
                TextField = GetSwitchLocale(TextField);
            }
            ddList.Items.Clear();

            T_ShippingMarkCollection source;

            if (OrderBy == null || OrderBy.Length == 0)
            {
                OrderBy = TextField;
            }

            if (WhereClause.Length > 0)
            {
                source = T_ShippingMark.LoadCollection(WhereClause, OrderBy, true);
            }
            else
            {
                source = T_ShippingMark.LoadCollection(OrderBy, true);
            }

            Common.ComboList sourceList = new Common.ComboList();

            if (BlankLine)
            {
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
            }

            foreach (T_ShippingMark item in source)
            {
                bool filter = false;
                if (ParentFilter.Trim() != String.Empty)
                {
                    filter = true;
                    if (item.ParentShippingMark != Guid.Empty)
                    {
                        filter = IgnorThis(item, ParentFilter);
                    }
                }
                if (!(filter))
                {
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.ShippingMarkId));
                }
            }

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";

            if (ddList.Items.Count > 0)
            {
                ddList.SelectedIndex = 0;
            }
        }

        #endregion


        private static bool IgnorThis(T_ShippingMark target, string parentFilter)
        {
            bool result = true;
            parentFilter = parentFilter.Replace(" ", "");       // remove spaces
            parentFilter = parentFilter.Replace("'", "");       // remove '
            string[] parsed = parentFilter.Split('=');          // parse

            if (target.ParentShippingMark == Guid.Empty)
            {
                PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
                string filterField = (string)pi.GetValue(target, null);
                if (filterField.ToLower() == parsed[1].ToLower())
                {
                    result = false;
                }
            }
            else
            {
                T_ShippingMark parentTemplate = T_ShippingMark.Load(target.ParentShippingMark);
                result = IgnorThis(parentTemplate, parentFilter);
            }
            return result;
        }

        private static string GetFormatedText(T_ShippingMark target, string[] textField, string textFormatString)
        {
            for (int i = 0; i < textField.Length; i++)
            {
                PropertyInfo pi = target.GetType().GetProperty(textField[i]);
                textFormatString = textFormatString.Replace("{" + i.ToString() + "}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
            }
            return textFormatString;
        }

        private static string[] GetSwitchLocale(string[] source)
        {
            switch (Common.Config.CurrentLanguageId)
            {
                case 2:
                    source[source.Length - 1] += "_Chs";
                    break;
                case 3:
                    source[source.Length - 1] += "_Cht";
                    break;
            }
            return source;
        }
    }


    /// <summary>
    /// Represents a collection of <see cref="T_ShippingMark">T_ShippingMark</see> objects.
    /// </summary>
    public class T_ShippingMarkCollection : BindingList<T_ShippingMark>
    {
    }
}
