using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace xPort5.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.T_UnitOfMeasures.
    /// Date Created:   2020-03-02 02:31:53
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class T_UnitOfMeasures
    {
        private Guid key = Guid.Empty;
        private Guid uomId = Guid.Empty;
        private string uomCode = String.Empty;
        private string uomName = String.Empty;
        private string uomName_Chs = String.Empty;
        private string uomName_Cht = String.Empty;

        /// <summary>
        /// Initialize an new empty T_UnitOfMeasures object.
        /// </summary>
        public T_UnitOfMeasures()
        {
        }

        /// <summary>
        /// Initialize a new T_UnitOfMeasures object with the given parameters.
        /// </summary>
        public T_UnitOfMeasures(Guid uomId, string uomCode, string uomName, string uomName_Chs, string uomName_Cht)
        {
            this.uomId = uomId;
            this.uomCode = uomCode;
            this.uomName = uomName;
            this.uomName_Chs = uomName_Chs;
            this.uomName_Cht = uomName_Cht;
        }

        /// <summary>
        /// Loads a T_UnitOfMeasures object from the database using the given UomId
        /// </summary>
        /// <param name="uomId">The primary key value</param>
        /// <returns>A T_UnitOfMeasures object</returns>
        public static T_UnitOfMeasures Load(Guid uomId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@UomId", uomId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spT_UnitOfMeasures_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    T_UnitOfMeasures result = new T_UnitOfMeasures();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a T_UnitOfMeasures object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A T_UnitOfMeasures object</returns>
        public static T_UnitOfMeasures LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spT_UnitOfMeasures_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    T_UnitOfMeasures result = new T_UnitOfMeasures();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a collection of T_UnitOfMeasures objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_UnitOfMeasures objects in the database.</returns>
        public static T_UnitOfMeasuresCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] { };
            return LoadCollection("spT_UnitOfMeasures_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_UnitOfMeasures objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the T_UnitOfMeasures objects in the database ordered by the columns specified.</returns>
        public static T_UnitOfMeasuresCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spT_UnitOfMeasures_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_UnitOfMeasures objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_UnitOfMeasures objects in the database.</returns>
        public static T_UnitOfMeasuresCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spT_UnitOfMeasures_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_UnitOfMeasures objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the T_UnitOfMeasures objects in the database ordered by the columns specified.</returns>
        public static T_UnitOfMeasuresCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spT_UnitOfMeasures_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of T_UnitOfMeasures objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the T_UnitOfMeasures objects in the database.</returns>
        public static T_UnitOfMeasuresCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            T_UnitOfMeasuresCollection result = new T_UnitOfMeasuresCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    T_UnitOfMeasures tmp = new T_UnitOfMeasures();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a T_UnitOfMeasures object from the database.
        /// </summary>
        /// <param name="uomId">The primary key value</param>
        public static void Delete(Guid uomId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@UomId", uomId) };
            SqlHelper.Default.ExecuteNonQuery("spT_UnitOfMeasures_DelRec", parameterValues);
        }


        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) uomId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) uomCode = reader.GetString(1);
                if (!reader.IsDBNull(2)) uomName = reader.GetString(2);
                if (!reader.IsDBNull(3)) uomName_Chs = reader.GetString(3);
                if (!reader.IsDBNull(4)) uomName_Cht = reader.GetString(4);
            }
        }

        public void Delete()
        {
            Delete(this.UomId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != UomId)
                    this.Delete();
                Update();
            }
        }

        public Guid UomId
        {
            get { return uomId; }
            set { uomId = value; }
        }

        public string UomCode
        {
            get { return uomCode; }
            set { uomCode = value; }
        }

        public string UomName
        {
            get { return uomName; }
            set { uomName = value; }
        }

        public string UomName_Chs
        {
            get { return uomName_Chs; }
            set { uomName_Chs = value; }
        }

        public string UomName_Cht
        {
            get { return uomName_Cht; }
            set { uomName_Cht = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;

            SqlHelper.Default.ExecuteNonQuery("spT_UnitOfMeasures_InsRec", "@UomId", out returnedValue, parameterValues);

            uomId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();

            SqlHelper.Default.ExecuteNonQuery("spT_UnitOfMeasures_UpdRec", parameterValues);
        }

        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[5];
            prams[0] = GetSqlParameter("@UomId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.UomId);
            prams[1] = GetSqlParameter("@UomCode", ParameterDirection.Input, SqlDbType.VarChar, 6, this.UomCode);
            prams[2] = GetSqlParameter("@UomName", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.UomName);
            prams[3] = GetSqlParameter("@UomName_Chs", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.UomName_Chs);
            prams[4] = GetSqlParameter("@UomName_Cht", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.UomName_Cht);
            return prams;
        }

        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }

        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[]
            {
                GetSqlParameterWithoutDirection("@UomId", SqlDbType.UniqueIdentifier, 16, this.UomId),
                GetSqlParameterWithoutDirection("@UomCode", SqlDbType.VarChar, 6, this.UomCode),
                GetSqlParameterWithoutDirection("@UomName", SqlDbType.NVarChar, 64, this.UomName),
                GetSqlParameterWithoutDirection("@UomName_Chs", SqlDbType.NVarChar, 64, this.UomName_Chs),
                GetSqlParameterWithoutDirection("@UomName_Cht", SqlDbType.NVarChar, 64, this.UomName_Cht)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("uomId: " + uomId.ToString()).Append("\r\n");
            builder.Append("uomCode: " + uomCode.ToString()).Append("\r\n");
            builder.Append("uomName: " + uomName.ToString()).Append("\r\n");
            builder.Append("uomName_Chs: " + uomName_Chs.ToString()).Append("\r\n");
            builder.Append("uomName_Cht: " + uomName_Cht.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }

        #region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            string[] textField = { TextField };
            LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            if (SwitchLocale)
            {
                TextField = GetSwitchLocale(TextField);
            }
            ddList.Items.Clear();

            T_UnitOfMeasuresCollection source;

            if (OrderBy == null || OrderBy.Length == 0)
            {
                OrderBy = TextField;
            }

            if (WhereClause.Length > 0)
            {
                source = T_UnitOfMeasures.LoadCollection(WhereClause, OrderBy, true);
            }
            else
            {
                source = T_UnitOfMeasures.LoadCollection(OrderBy, true);
            }

            Common.ComboList sourceList = new Common.ComboList();

            if (BlankLine)
            {
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
            }

            foreach (T_UnitOfMeasures item in source)
            {
                bool filter = false;
                if (ParentFilter.Trim() != String.Empty)
                {
                    filter = IgnorThis(item, ParentFilter);
                }
                if (!(filter))
                {
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.UomId));
                }
            }

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";

            if (ddList.Items.Count > 0)
            {
                ddList.SelectedIndex = 0;
            }
        }

        #endregion


        private static bool IgnorThis(T_UnitOfMeasures target, string parentFilter)
        {
            bool result = true;
            parentFilter = parentFilter.Replace(" ", "");       // remove spaces
            parentFilter = parentFilter.Replace("'", "");       // remove '
            string[] parsed = parentFilter.Split('=');          // parse

            PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
            string filterField = (string)pi.GetValue(target, null);
            if (filterField.ToLower() == parsed[1].ToLower())
            {
                result = false;
            }
            return result;
        }

        private static string GetFormatedText(T_UnitOfMeasures target, string[] textField, string textFormatString)
        {
            for (int i = 0; i < textField.Length; i++)
            {
                PropertyInfo pi = target.GetType().GetProperty(textField[i]);
                textFormatString = textFormatString.Replace("{" + i.ToString() + "}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
            }
            return textFormatString;
        }

        private static string[] GetSwitchLocale(string[] source)
        {
            switch (Common.Config.CurrentLanguageId)
            {
                case 2:
                    source[source.Length - 1] += "_Chs";
                    break;
                case 3:
                    source[source.Length - 1] += "_Cht";
                    break;
            }
            return source;
        }
    }


    /// <summary>
    /// Represents a collection of <see cref="T_UnitOfMeasures">T_UnitOfMeasures</see> objects.
    /// </summary>
    public class T_UnitOfMeasuresCollection : BindingList<T_UnitOfMeasures>
    {
    }
}
