using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace xPort5.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.X_Counter.
    /// Date Created:   2020-03-02 02:30:23
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class X_Counter
    {
        private Guid key = Guid.Empty;
        private Guid counterId = Guid.Empty;
        private int nextSuppCode = 0;
        private int nextStaffCode = 0;
        private int nextCustCode = 0;
        private int nextSKUCode = 0;
        private int nextArticleCode = 0;
        private int nextQTNumber = 0;
        private int nextPLNumber = 0;
        private int nextSCNumber = 0;
        private int nextPCNumber = 0;
        private int nextINNumber = 0;
        private int nextPKNumber = 0;
        private int nextSPNumber = 0;

        /// <summary>
        /// Initialize an new empty X_Counter object.
        /// </summary>
        public X_Counter()
        {
        }

        /// <summary>
        /// Initialize a new X_Counter object with the given parameters.
        /// </summary>
        public X_Counter(Guid counterId, int nextSuppCode, int nextStaffCode, int nextCustCode, int nextSKUCode, int nextArticleCode, int nextQTNumber, int nextPLNumber, int nextSCNumber, int nextPCNumber, int nextINNumber, int nextPKNumber, int nextSPNumber)
        {
            this.counterId = counterId;
            this.nextSuppCode = nextSuppCode;
            this.nextStaffCode = nextStaffCode;
            this.nextCustCode = nextCustCode;
            this.nextSKUCode = nextSKUCode;
            this.nextArticleCode = nextArticleCode;
            this.nextQTNumber = nextQTNumber;
            this.nextPLNumber = nextPLNumber;
            this.nextSCNumber = nextSCNumber;
            this.nextPCNumber = nextPCNumber;
            this.nextINNumber = nextINNumber;
            this.nextPKNumber = nextPKNumber;
            this.nextSPNumber = nextSPNumber;
        }

        /// <summary>
        /// Loads a X_Counter object from the database using the given CounterId
        /// </summary>
        /// <param name="counterId">The primary key value</param>
        /// <returns>A X_Counter object</returns>
        public static X_Counter Load(Guid counterId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@CounterId", counterId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spX_Counter_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    X_Counter result = new X_Counter();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a X_Counter object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A X_Counter object</returns>
        public static X_Counter LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spX_Counter_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    X_Counter result = new X_Counter();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a collection of X_Counter objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the X_Counter objects in the database.</returns>
        public static X_CounterCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] { };
            return LoadCollection("spX_Counter_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of X_Counter objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the X_Counter objects in the database ordered by the columns specified.</returns>
        public static X_CounterCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spX_Counter_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of X_Counter objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the X_Counter objects in the database.</returns>
        public static X_CounterCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spX_Counter_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of X_Counter objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the X_Counter objects in the database ordered by the columns specified.</returns>
        public static X_CounterCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spX_Counter_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of X_Counter objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the X_Counter objects in the database.</returns>
        public static X_CounterCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            X_CounterCollection result = new X_CounterCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    X_Counter tmp = new X_Counter();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a X_Counter object from the database.
        /// </summary>
        /// <param name="counterId">The primary key value</param>
        public static void Delete(Guid counterId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@CounterId", counterId) };
            SqlHelper.Default.ExecuteNonQuery("spX_Counter_DelRec", parameterValues);
        }


        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) counterId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) nextSuppCode = reader.GetInt32(1);
                if (!reader.IsDBNull(2)) nextStaffCode = reader.GetInt32(2);
                if (!reader.IsDBNull(3)) nextCustCode = reader.GetInt32(3);
                if (!reader.IsDBNull(4)) nextSKUCode = reader.GetInt32(4);
                if (!reader.IsDBNull(5)) nextArticleCode = reader.GetInt32(5);
                if (!reader.IsDBNull(6)) nextQTNumber = reader.GetInt32(6);
                if (!reader.IsDBNull(7)) nextPLNumber = reader.GetInt32(7);
                if (!reader.IsDBNull(8)) nextSCNumber = reader.GetInt32(8);
                if (!reader.IsDBNull(9)) nextPCNumber = reader.GetInt32(9);
                if (!reader.IsDBNull(10)) nextINNumber = reader.GetInt32(10);
                if (!reader.IsDBNull(11)) nextPKNumber = reader.GetInt32(11);
                if (!reader.IsDBNull(12)) nextSPNumber = reader.GetInt32(12);
            }
        }

        public void Delete()
        {
            Delete(this.CounterId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != CounterId)
                    this.Delete();
                Update();
            }
        }

        public Guid CounterId
        {
            get { return counterId; }
            set { counterId = value; }
        }

        public int NextSuppCode
        {
            get { return nextSuppCode; }
            set { nextSuppCode = value; }
        }

        public int NextStaffCode
        {
            get { return nextStaffCode; }
            set { nextStaffCode = value; }
        }

        public int NextCustCode
        {
            get { return nextCustCode; }
            set { nextCustCode = value; }
        }

        public int NextSKUCode
        {
            get { return nextSKUCode; }
            set { nextSKUCode = value; }
        }

        public int NextArticleCode
        {
            get { return nextArticleCode; }
            set { nextArticleCode = value; }
        }

        public int NextQTNumber
        {
            get { return nextQTNumber; }
            set { nextQTNumber = value; }
        }

        public int NextPLNumber
        {
            get { return nextPLNumber; }
            set { nextPLNumber = value; }
        }

        public int NextSCNumber
        {
            get { return nextSCNumber; }
            set { nextSCNumber = value; }
        }

        public int NextPCNumber
        {
            get { return nextPCNumber; }
            set { nextPCNumber = value; }
        }

        public int NextINNumber
        {
            get { return nextINNumber; }
            set { nextINNumber = value; }
        }

        public int NextPKNumber
        {
            get { return nextPKNumber; }
            set { nextPKNumber = value; }
        }

        public int NextSPNumber
        {
            get { return nextSPNumber; }
            set { nextSPNumber = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;

            SqlHelper.Default.ExecuteNonQuery("spX_Counter_InsRec", "@CounterId", out returnedValue, parameterValues);

            counterId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();

            SqlHelper.Default.ExecuteNonQuery("spX_Counter_UpdRec", parameterValues);
        }

        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[13];
            prams[0] = GetSqlParameter("@CounterId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.CounterId);
            prams[1] = GetSqlParameter("@NextSuppCode", ParameterDirection.Input, SqlDbType.Int, 4, this.NextSuppCode);
            prams[2] = GetSqlParameter("@NextStaffCode", ParameterDirection.Input, SqlDbType.Int, 4, this.NextStaffCode);
            prams[3] = GetSqlParameter("@NextCustCode", ParameterDirection.Input, SqlDbType.Int, 4, this.NextCustCode);
            prams[4] = GetSqlParameter("@NextSKUCode", ParameterDirection.Input, SqlDbType.Int, 4, this.NextSKUCode);
            prams[5] = GetSqlParameter("@NextArticleCode", ParameterDirection.Input, SqlDbType.Int, 4, this.NextArticleCode);
            prams[6] = GetSqlParameter("@NextQTNumber", ParameterDirection.Input, SqlDbType.Int, 4, this.NextQTNumber);
            prams[7] = GetSqlParameter("@NextPLNumber", ParameterDirection.Input, SqlDbType.Int, 4, this.NextPLNumber);
            prams[8] = GetSqlParameter("@NextSCNumber", ParameterDirection.Input, SqlDbType.Int, 4, this.NextSCNumber);
            prams[9] = GetSqlParameter("@NextPCNumber", ParameterDirection.Input, SqlDbType.Int, 4, this.NextPCNumber);
            prams[10] = GetSqlParameter("@NextINNumber", ParameterDirection.Input, SqlDbType.Int, 4, this.NextINNumber);
            prams[11] = GetSqlParameter("@NextPKNumber", ParameterDirection.Input, SqlDbType.Int, 4, this.NextPKNumber);
            prams[12] = GetSqlParameter("@NextSPNumber", ParameterDirection.Input, SqlDbType.Int, 4, this.NextSPNumber);
            return prams;
        }

        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }

        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[]
            {
                GetSqlParameterWithoutDirection("@CounterId", SqlDbType.UniqueIdentifier, 16, this.CounterId),
                GetSqlParameterWithoutDirection("@NextSuppCode", SqlDbType.Int, 4, this.NextSuppCode),
                GetSqlParameterWithoutDirection("@NextStaffCode", SqlDbType.Int, 4, this.NextStaffCode),
                GetSqlParameterWithoutDirection("@NextCustCode", SqlDbType.Int, 4, this.NextCustCode),
                GetSqlParameterWithoutDirection("@NextSKUCode", SqlDbType.Int, 4, this.NextSKUCode),
                GetSqlParameterWithoutDirection("@NextArticleCode", SqlDbType.Int, 4, this.NextArticleCode),
                GetSqlParameterWithoutDirection("@NextQTNumber", SqlDbType.Int, 4, this.NextQTNumber),
                GetSqlParameterWithoutDirection("@NextPLNumber", SqlDbType.Int, 4, this.NextPLNumber),
                GetSqlParameterWithoutDirection("@NextSCNumber", SqlDbType.Int, 4, this.NextSCNumber),
                GetSqlParameterWithoutDirection("@NextPCNumber", SqlDbType.Int, 4, this.NextPCNumber),
                GetSqlParameterWithoutDirection("@NextINNumber", SqlDbType.Int, 4, this.NextINNumber),
                GetSqlParameterWithoutDirection("@NextPKNumber", SqlDbType.Int, 4, this.NextPKNumber),
                GetSqlParameterWithoutDirection("@NextSPNumber", SqlDbType.Int, 4, this.NextSPNumber)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("counterId: " + counterId.ToString()).Append("\r\n");
            builder.Append("nextSuppCode: " + nextSuppCode.ToString()).Append("\r\n");
            builder.Append("nextStaffCode: " + nextStaffCode.ToString()).Append("\r\n");
            builder.Append("nextCustCode: " + nextCustCode.ToString()).Append("\r\n");
            builder.Append("nextSKUCode: " + nextSKUCode.ToString()).Append("\r\n");
            builder.Append("nextArticleCode: " + nextArticleCode.ToString()).Append("\r\n");
            builder.Append("nextQTNumber: " + nextQTNumber.ToString()).Append("\r\n");
            builder.Append("nextPLNumber: " + nextPLNumber.ToString()).Append("\r\n");
            builder.Append("nextSCNumber: " + nextSCNumber.ToString()).Append("\r\n");
            builder.Append("nextPCNumber: " + nextPCNumber.ToString()).Append("\r\n");
            builder.Append("nextINNumber: " + nextINNumber.ToString()).Append("\r\n");
            builder.Append("nextPKNumber: " + nextPKNumber.ToString()).Append("\r\n");
            builder.Append("nextSPNumber: " + nextSPNumber.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }

        #region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            string[] textField = { TextField };
            LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            if (SwitchLocale)
            {
                TextField = GetSwitchLocale(TextField);
            }
            ddList.Items.Clear();

            X_CounterCollection source;

            if (OrderBy == null || OrderBy.Length == 0)
            {
                OrderBy = TextField;
            }

            if (WhereClause.Length > 0)
            {
                source = X_Counter.LoadCollection(WhereClause, OrderBy, true);
            }
            else
            {
                source = X_Counter.LoadCollection(OrderBy, true);
            }

            Common.ComboList sourceList = new Common.ComboList();

            if (BlankLine)
            {
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
            }

            foreach (X_Counter item in source)
            {
                bool filter = false;
                if (ParentFilter.Trim() != String.Empty)
                {
                    filter = IgnorThis(item, ParentFilter);
                }
                if (!(filter))
                {
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.CounterId));
                }
            }

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";

            if (ddList.Items.Count > 0)
            {
                ddList.SelectedIndex = 0;
            }
        }

        #endregion


        private static bool IgnorThis(X_Counter target, string parentFilter)
        {
            bool result = true;
            parentFilter = parentFilter.Replace(" ", "");       // remove spaces
            parentFilter = parentFilter.Replace("'", "");       // remove '
            string[] parsed = parentFilter.Split('=');          // parse

            PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
            string filterField = (string)pi.GetValue(target, null);
            if (filterField.ToLower() == parsed[1].ToLower())
            {
                result = false;
            }
            return result;
        }

        private static string GetFormatedText(X_Counter target, string[] textField, string textFormatString)
        {
            for (int i = 0; i < textField.Length; i++)
            {
                PropertyInfo pi = target.GetType().GetProperty(textField[i]);
                textFormatString = textFormatString.Replace("{" + i.ToString() + "}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
            }
            return textFormatString;
        }

        private static string[] GetSwitchLocale(string[] source)
        {
            switch (Common.Config.CurrentLanguageId)
            {
                case 2:
                    source[source.Length - 1] += "_Chs";
                    break;
                case 3:
                    source[source.Length - 1] += "_Cht";
                    break;
            }
            return source;
        }
    }


    /// <summary>
    /// Represents a collection of <see cref="X_Counter">X_Counter</see> objects.
    /// </summary>
    public class X_CounterCollection : BindingList<X_Counter>
    {
    }
}
