using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace xPort5.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.Z_Salutation.
    /// Date Created:   2020-03-02 02:27:26
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class Z_Salutation
    {
        private Guid key = Guid.Empty;
        private Guid salutationId = Guid.Empty;
        private string salutationCode = String.Empty;
        private string salutationName = String.Empty;
        private string salutationName_Chs = String.Empty;
        private string salutationName_Cht = String.Empty;

        /// <summary>
        /// Initialize an new empty Z_Salutation object.
        /// </summary>
        public Z_Salutation()
        {
        }

        /// <summary>
        /// Initialize a new Z_Salutation object with the given parameters.
        /// </summary>
        public Z_Salutation(Guid salutationId, string salutationCode, string salutationName, string salutationName_Chs, string salutationName_Cht)
        {
            this.salutationId = salutationId;
            this.salutationCode = salutationCode;
            this.salutationName = salutationName;
            this.salutationName_Chs = salutationName_Chs;
            this.salutationName_Cht = salutationName_Cht;
        }

        /// <summary>
        /// Loads a Z_Salutation object from the database using the given SalutationId
        /// </summary>
        /// <param name="salutationId">The primary key value</param>
        /// <returns>A Z_Salutation object</returns>
        public static Z_Salutation Load(Guid salutationId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@SalutationId", salutationId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spZ_Salutation_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    Z_Salutation result = new Z_Salutation();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a Z_Salutation object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A Z_Salutation object</returns>
        public static Z_Salutation LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spZ_Salutation_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    Z_Salutation result = new Z_Salutation();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a collection of Z_Salutation objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the Z_Salutation objects in the database.</returns>
        public static Z_SalutationCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] { };
            return LoadCollection("spZ_Salutation_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of Z_Salutation objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the Z_Salutation objects in the database ordered by the columns specified.</returns>
        public static Z_SalutationCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spZ_Salutation_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of Z_Salutation objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the Z_Salutation objects in the database.</returns>
        public static Z_SalutationCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spZ_Salutation_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of Z_Salutation objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the Z_Salutation objects in the database ordered by the columns specified.</returns>
        public static Z_SalutationCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spZ_Salutation_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of Z_Salutation objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the Z_Salutation objects in the database.</returns>
        public static Z_SalutationCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            Z_SalutationCollection result = new Z_SalutationCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    Z_Salutation tmp = new Z_Salutation();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a Z_Salutation object from the database.
        /// </summary>
        /// <param name="salutationId">The primary key value</param>
        public static void Delete(Guid salutationId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@SalutationId", salutationId) };
            SqlHelper.Default.ExecuteNonQuery("spZ_Salutation_DelRec", parameterValues);
        }


        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) salutationId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) salutationCode = reader.GetString(1);
                if (!reader.IsDBNull(2)) salutationName = reader.GetString(2);
                if (!reader.IsDBNull(3)) salutationName_Chs = reader.GetString(3);
                if (!reader.IsDBNull(4)) salutationName_Cht = reader.GetString(4);
            }
        }

        public void Delete()
        {
            Delete(this.SalutationId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != SalutationId)
                    this.Delete();
                Update();
            }
        }

        public Guid SalutationId
        {
            get { return salutationId; }
            set { salutationId = value; }
        }

        public string SalutationCode
        {
            get { return salutationCode; }
            set { salutationCode = value; }
        }

        public string SalutationName
        {
            get { return salutationName; }
            set { salutationName = value; }
        }

        public string SalutationName_Chs
        {
            get { return salutationName_Chs; }
            set { salutationName_Chs = value; }
        }

        public string SalutationName_Cht
        {
            get { return salutationName_Cht; }
            set { salutationName_Cht = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;

            SqlHelper.Default.ExecuteNonQuery("spZ_Salutation_InsRec", "@SalutationId", out returnedValue, parameterValues);

            salutationId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();

            SqlHelper.Default.ExecuteNonQuery("spZ_Salutation_UpdRec", parameterValues);
        }

        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[5];
            prams[0] = GetSqlParameter("@SalutationId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.SalutationId);
            prams[1] = GetSqlParameter("@SalutationCode", ParameterDirection.Input, SqlDbType.VarChar, 3, this.SalutationCode);
            prams[2] = GetSqlParameter("@SalutationName", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.SalutationName);
            prams[3] = GetSqlParameter("@SalutationName_Chs", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.SalutationName_Chs);
            prams[4] = GetSqlParameter("@SalutationName_Cht", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.SalutationName_Cht);
            return prams;
        }

        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }

        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[]
            {
                GetSqlParameterWithoutDirection("@SalutationId", SqlDbType.UniqueIdentifier, 16, this.SalutationId),
                GetSqlParameterWithoutDirection("@SalutationCode", SqlDbType.VarChar, 3, this.SalutationCode),
                GetSqlParameterWithoutDirection("@SalutationName", SqlDbType.NVarChar, 64, this.SalutationName),
                GetSqlParameterWithoutDirection("@SalutationName_Chs", SqlDbType.NVarChar, 64, this.SalutationName_Chs),
                GetSqlParameterWithoutDirection("@SalutationName_Cht", SqlDbType.NVarChar, 64, this.SalutationName_Cht)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("salutationId: " + salutationId.ToString()).Append("\r\n");
            builder.Append("salutationCode: " + salutationCode.ToString()).Append("\r\n");
            builder.Append("salutationName: " + salutationName.ToString()).Append("\r\n");
            builder.Append("salutationName_Chs: " + salutationName_Chs.ToString()).Append("\r\n");
            builder.Append("salutationName_Cht: " + salutationName_Cht.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }

        #region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            string[] textField = { TextField };
            LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            if (SwitchLocale)
            {
                TextField = GetSwitchLocale(TextField);
            }
            ddList.Items.Clear();

            Z_SalutationCollection source;

            if (OrderBy == null || OrderBy.Length == 0)
            {
                OrderBy = TextField;
            }

            if (WhereClause.Length > 0)
            {
                source = Z_Salutation.LoadCollection(WhereClause, OrderBy, true);
            }
            else
            {
                source = Z_Salutation.LoadCollection(OrderBy, true);
            }

            Common.ComboList sourceList = new Common.ComboList();

            if (BlankLine)
            {
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
            }

            foreach (Z_Salutation item in source)
            {
                bool filter = false;
                if (ParentFilter.Trim() != String.Empty)
                {
                    filter = IgnorThis(item, ParentFilter);
                }
                if (!(filter))
                {
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.SalutationId));
                }
            }

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";

            if (ddList.Items.Count > 0)
            {
                ddList.SelectedIndex = 0;
            }
        }

        #endregion


        private static bool IgnorThis(Z_Salutation target, string parentFilter)
        {
            bool result = true;
            parentFilter = parentFilter.Replace(" ", "");       // remove spaces
            parentFilter = parentFilter.Replace("'", "");       // remove '
            string[] parsed = parentFilter.Split('=');          // parse

            PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
            string filterField = (string)pi.GetValue(target, null);
            if (filterField.ToLower() == parsed[1].ToLower())
            {
                result = false;
            }
            return result;
        }

        private static string GetFormatedText(Z_Salutation target, string[] textField, string textFormatString)
        {
            for (int i = 0; i < textField.Length; i++)
            {
                PropertyInfo pi = target.GetType().GetProperty(textField[i]);
                textFormatString = textFormatString.Replace("{" + i.ToString() + "}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
            }
            return textFormatString;
        }

        private static string[] GetSwitchLocale(string[] source)
        {
            switch (Common.Config.CurrentLanguageId)
            {
                case 2:
                    source[source.Length - 1] += "_Chs";
                    break;
                case 3:
                    source[source.Length - 1] += "_Cht";
                    break;
            }
            return source;
        }
    }


    /// <summary>
    /// Represents a collection of <see cref="Z_Salutation">Z_Salutation</see> objects.
    /// </summary>
    public class Z_SalutationCollection : BindingList<Z_Salutation>
    {
    }
}
